- examples/cdk/lib/example-function.MyFunction.ts
- packages/metrics/tests/unit/Metrics.test.ts
Rename the term "purge" that was missed by the PR #377 
This will solve issue #423 
```
cd examples/cdk
cdk deploy 
aws lambda invoke --function-name <function_name_should_start_with_CdkAppStack-MyFunction>
```
#377 
#423
---
> fix(metrics): Rename leftover reference to purgeStoredMetrics() function

- docs/core/metrics.md
- examples/cdk/lib/example-function.MyFunction.ts
- examples/cdk/lib/example-function.MyFunctionWithDecorator.ts
- packages/metrics/examples/decorator/empty-metrics.ts
- packages/metrics/examples/empty-metrics.ts
- packages/metrics/src/Metrics.ts
- packages/metrics/src/middleware/middy.ts
- packages/metrics/src/types/Metrics.ts
- packages/metrics/tests/e2e/decorator.test.MyFunction.ts
- packages/metrics/tests/e2e/standardFunctions.test.MyFunction.ts
- packages/metrics/tests/unit/Metrics.test.ts
- packages/metrics/tests/unit/middleware/middy.test.ts
Make sure that all existance of "raiseOnEmptyMetrics" were renamed. 
[#348](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/348)
---
> refactor(metrics): rename option property from raiseOnEmptyMetrics to throwOnEmptyMetrics

- README.md
- docs/index.md
- packages/commons/README.md
- packages/logger/README.md
- packages/metrics/README.md
- packages/tracing/README.md
Changes:
- Update tracer link to go to `https://github.com/awslabs/aws-lambda-powertools-typescript/tree/main/examples/cdk/lib`
- Update docs to resolve lint errors
Build and run the docs and click on the changed links.
---
> docs: Tracer example link goes to a 404

- .husky/pre-push
- packages/metrics/src/Metrics.ts
1. Fix linting issue that is breaking the build > https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/1666735269 
2. Add pre-push hook to run linting
`npm run lerna-lint`
N/A
---
> fix(build): Fix linting issue and add linting to the pre-push hook

- package-lock.json
- package.json
- packages/logger/package-lock.json
- packages/logger/package.json
- packages/logger/src/Logger.ts
- packages/logger/src/log/LogItem.ts
- packages/logger/tests/unit/Logger.test.ts
As detailed in #419 the size of `node_modules` for logger was unnecessarily big, this PR removes the full `lodash` lib in favor of targeted `lodash.x` depenencies brigning down the `node_modules` size to `1.8M` from `139M`.
Detailed list of changes:
- Removed `lodash` & `@types/lodash`
- Added `lodash.clonedeep`, `lodash.merge`, and `lodash.pickby` & respective `@types/lodash.xxx`
- Updated imports to use new deps
- Updated calls for `merge` in main `Logger` class since it was using the `lodash/fp` version [that swaps the argument order](https://www.measurethat.net/Benchmarks/Show/7660/0/lodash-merge-vs-deepmerge-vs-lodashfp-merge).
- Swapped `npm-shrinkwrap.json` for `packages-lock.json` since it was the last utility to still use it.
1. Checkout branch & run unit tests in `logger` to …
> build(logger): reduce node_modules size

- packages/tracing/src/Tracer.ts
- packages/tracing/tests/unit/Tracer.test.ts
As reporded by @ijemmy during manual tests manually instrumenting a function with `Tracer` outside of AWS Lambda was throwing an error due to the lack of traces & context.
This was a bug since `Tracer` should automatically detect its running outside of Lambda and deactivate itself. The bug affected only manual instrumentation while the Middy middleware and Class decorator were unaffected.
Changes:
- Now leveraging the `setContextMissingStrategy()` method [from the Node.js x-ray-sdk](https://github.com/willarmiros/aws-lambda-developer-guide/blob/cb769974339cd46b7264301ab4dbf45cdb7c51df/doc_source/nodejs-tracing.md?plain=1#L41-L42) to disable throwing errors when tracing is disabled.
- Changed behaviour of `Tracer.setSegment()` & `Tracer.getSegment()` to respect value of `Tracer. …
> fix(tracer): avoid throwing errors in manual instrumentation when running outside of AWS Lambda 

- CONTRIBUTING.md
- package.json
- packages/commons/tsconfig.json
- packages/logger/tsconfig.json
- packages/metrics/tsconfig.json
- packages/tracing/tsconfig.json
fix(build): Update contributing.md and fix npm ci
Changes:
- Update CONTRIBUTING.md to use `npm ci`
- Fix `CONTRIBUTING.md` based on markdown lint recommended fixes
- Setup project references
closes #415
`git clean -fdx; npm ci`
#415
---
> fix(build): Update contributing.md and fix npm ci

- CONTRIBUTING.md
- packages/commons/tsconfig.json
- packages/logger/package-lock.json
- packages/logger/package.json
- packages/logger/tsconfig.json
- packages/metrics/package-lock.json
- packages/metrics/package.json
- packages/metrics/tsconfig.json
- packages/tracing/package-lock.json
- packages/tracing/package.json
- packages/tracing/tsconfig.json
This commit was modifying the way `npm pack` structures `commons` package ... which break all deps.
```
cd packages/commons
npm pack
```
check stdout structure and check `/lib/index.js` match package.json `main` path. 
E2E tests:
```  
npm run lerna-package
cd examples/cdk
npm run build
npm install aws-sdk
npm run build
```
TBD
---
> fix(all): fix latest release broken by change of npm pack result on common

- docs/core/logger.md
- packages/logger/src/index.ts
This PR aims at resolving the issue highlighted in #393 that prevented customers to use `LogFormatter` (from `Logger`) as described in the docs.
Build the utility with `npm pack` & install it in other project/examples, then try to use  to see exported class.
See below:
[#393](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/393)  
N/A
---
> fix(logger): correctly export LogFormatter

- examples/cdk/README.md
- examples/cdk/bin/cdk-app.ts
- packages/metrics/src/Metrics.ts
- packages/metrics/tests/e2e/decorator.test.MyFunction.ts
- packages/metrics/tests/e2e/standardFunctions.test.MyFunction.ts
Write a dedicated readme that explains how to deploy and interact with the CDK examples. Also update stack identifiers, e.g. CdkAppStack, to more specific ones, e.g. 'LambdaPowertoolsTypeScript-ExamplesCdkStack', to consider users that are deploying this stack amongst others into their accounts.
The current README is just the default CDK TS readme and is therefore not helpful.
No dependencies for this change.
[#XXXXX](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/XXXXX)  
[#ZZZZZ](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/ZZZZZ)
N/A
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> docs: Improve examples/cdk/README.md

- package-lock.json
- package.json
Following security advisory [GHSA-5v2h-r2cx-5xgj](https://github.com/advisories/GHSA-5v2h-r2cx-5xgj) that impacted `marked` a dependency of `typedoc` which we use to generate the docs for the project's API, this PR bumps the version of `typedoc` to `v0.22.11` which in turn uses `marked@4.0.10` (see [PR](https://github.com/TypeStrong/typedoc/pull/1851)) that patches the vulnerability. 
Checkout branch, run `npm ci` while in root & then run `npm run docs-generateApiDoc` + `npm run docs-runLocalApiDoc`.
N/A
N/A
---
> build(deps-dev): bump typedoc from 0.22.10 to 0.22.11

- docs/index.md
This PR aims at clarifying our explanation about core/non-core utility availability. It follows [this change](https://github.com/awslabs/aws-lambda-powertools-python/commit/3e4e1abaebea360c01752726b62af8b805bbe3ac) made in the Python's Powertools repo.
BEFORE: This project separates core utilities that will be available in other runtimes vs general utilities that might not be available across all runtimes
AFTER: Core utilities such as Tracing, Logging, Metrics, and Event Handler will be available across all Lambda Powertools runtimes. Additional utilities are subjective to each language ecosystem and customer demand.
Checkout branch, run docs locally.
N/A
N/A
---
By submitting this pull request, I confirm that you …
> docs: updated tenets section to conform w other runtimes

- .github/workflows/pr_lint_and_test.yml
PRs from fork are not lint or tested properly with our current workflow. This PR change the trigger to make sure it runs on opened or synchronize (details below).
> `synchronize`: Triggered when a pull request's head branch is updated. For example, when the head branch is updated from the base branch, when new commits are pushed to the head branch, or when the base branch is changed.
(cf. https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)
check tests on this PR: https://github.com/devfest-bugbust/aws-lambda-powertools-typescript/pull/3 (don't look at the changes, what matters are the actions run).
---
By submitting this pull request, I confirm that you can use, …
> chore(cicd): fix trigger for gh actions linting andctesting PR from fork

- .nvmrc
- CONTRIBUTING.md
This PR aims at setting a standard development environment and contributing process for this project.
Main takeaways:
- Node.js 14.x following `lts/fermium` tag (Active LTS version), support for `.nvmrc` file
- Npm 8.x following `@next-8` tag
- Overhauled "Contributing via Pull Requests" section of `CONTRIBUTING.md`
- Expanded "Getting Started" section of `CONTRIBUTING.md`
- Complemented "Local documentation" section of `CONTRIBUTING.md`
Shoutout to the amazing [AWS CDK Contributing guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) from which I have liberally borrowed the structure for these changes.
Check content of `CONTRIBUTING.md`.
[#422](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/422) …
> docs: improve dev setup & contributing info

- examples/cdk/package-lock.json
- examples/cdk/package.json
Currently when a version are bumped, examples cdk package got his dependencies bumped as well to match latest package that are going to be released.
1. This can't be control due to this https://github.com/lerna/lerna/issues/2326 bug.
2. Bumping dependencies can make example code buggy since it won't be updated to go around potential breaking changes ...
This PR leverage [versionning life cycle](https://github.com/lerna/lerna/tree/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/commands/version#lifecycle-scripts) to force versioning of deps and workaround https://github.com/lerna/lerna/issues/2326 .
NB: Examples will always be behind if we don't update manually the dependencies.
Remove `examples/cdk` from lerna.json and add lint, build and test specific scripts to either root `package.json` or in …
> chore(examples): fix version bumping of examples

- packages/logger/src/Logger.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/types/LambdaInterface.ts
- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
As evidenced in #399 `Logger` and `Metrics` were not correctly returning the decorated class when used as decorators. This PR aims at correcting that behaviour and add unit tests to check that to avoid future regressions.
Additionally this PR removes two unused & leftover files in the `Logger` package.
Checkout the branch & run tests or check the GitHub checks results.
[#399](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/399)  
N/A
---
> fix(logger|metrics): return decorated class

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-release-prod.yml
- .github/workflows/run-e2e-tests.yml
- .gitpod.yml
- CONTRIBUTING.md
- examples/cdk/package-lock.json
- examples/cdk/package.json
- package-lock.json
- packages/commons/package-lock.json
- packages/logger/package-lock.json
- packages/logger/src/Logger.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/types/LambdaInterface.ts
- packages/metrics/package-lock.json
- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
- packages/tracing/package-lock.json
This PR adds concurrency limit of 1 to some github workflow. 
This change should prevent race conditions when performing actions over the project.
The behaviour of the affected workflow will be that if one workflow of the same group is already running, the new one will be queued and performed after the old one is done. 
This problem happens often when you merge dependabot PRs one after the other, or it can happen with any PR into main.
Allow applicable for e2e tests.
N/A
N/A
---
> build(all): add concurrency to github workflows

- README.md
- examples/cdk/src/example-function.Tracer.PatchAWSSDKv2.ts
- examples/cdk/src/example-function.Tracer.PatchAWSSDKv3.ts
- examples/cdk/src/example-function.Tracer.PatchAllAWSSDK.ts
- packages/logger/examples/ephemeral-attributes.ts
- packages/logger/examples/inject-context-decorator.ts
- packages/logger/examples/inject-context-middleware.ts
- packages/logger/examples/utils/formatters/CustomLogFormatter.ts
- packages/logger/examples/utils/formatters/MyCompanyLogFormatter.ts
- packages/metrics/examples/cold-start.ts
- packages/metrics/examples/constructor-options.ts
- packages/metrics/examples/decorator/cold-start.ts
- packages/metrics/examples/decorator/constructor-options.ts
- packages/metrics/examples/decorator/default-dimensions-constructor.ts
- packages/metrics/examples/decorator/default-dimensions.ts
- packages/metrics/examples/decorator/dimensions.ts
- packages/metrics/examples/decorator/empty-metrics.ts
- packages/metrics/examples/decorator/hello-world.ts
- packages/metrics/examples/decorator/manual-flushing.ts
- packages/metrics/examples/decorator/manual-metrics-print.ts
- packages/metrics/examples/decorator/single-metric.ts
- packages/metrics/examples/default-dimensions-constructor.ts
- packages/metrics/examples/default-dimensions.ts
- packages/metrics/examples/dimensions.ts
- packages/metrics/examples/empty-metrics.ts
- packages/metrics/examples/hello-world.ts
- packages/metrics/examples/manual-flushing.ts
- packages/metrics/examples/manual-metrics-print.ts
- packages/metrics/examples/single-metric.ts
- Use shortened imports where possible
- Use 'serviceName' instead of 'service'
- Correct some of the relative path imports to work again
- Correct spacing around '}'
- Typo in 'metrics/examples/hello-world.ts'
- Correct link to Tracer examples from Readme
Run `npm test` and open and fix examples in the metrics and logger packages.
- https://github.com/awslabs/aws-lambda-powertools-typescript/issues/510
---
> fix(examples): fix errors in logger and metrics examples

- packages/tracing/src/Tracer.ts
- packages/tracing/tests/e2e/tracer.test.Decorator.ts
- packages/tracing/tests/e2e/tracer.test.DecoratorWithAsyncHandler.ts
- packages/tracing/tests/e2e/tracer.test.Manual.ts
- packages/tracing/tests/e2e/tracer.test.Middleware.ts
- packages/tracing/tests/e2e/tracer.test.ts
- packages/tracing/tests/unit/Tracer.test.ts
This PR aims at fixing the bug identified in #524.
Check GitHub actions execution results, the unit tests now include test cases to assert on the type of client being returned.
[#524](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/524)  
N/A
---
> fix(tracer): properly return DynamoDB.DocumentClient

- packages/commons/src/Utility.ts
- packages/commons/src/index.ts
- packages/commons/tests/unit/LambdaInterface.test.ts
- packages/commons/tests/unit/Utility.test.ts
This PR introduces a new `Utility` class in the `@aws-lambda-powertools/commons` package. This class is designed to be extended by other Powertools utilities that will inherit its shared methods.
In this iteration the `Utility` class brings a centralised cold start heuristic to be shared by all core packages.
The changes in this PR have already been discussed in an internal RFC document reviewed by at least two other maintainers as per `CONTRIBUTING` guidelines.
Clone the repo & check newly introduced unit tests.
Also check the JSDoc documentation written in the class file.
[#484](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/484)  
N/A
---
By submitting this pull request, I confirm that you can …
> feat(commons): centralize cold start heuristic

- docs/core/metrics.md
- packages/metrics/package-lock.json
- packages/metrics/package.json
- packages/metrics/src/Metrics.ts
This PR introduces changes to the `Metrics` module to adopt the forthcoming `Utility` class that will be released in the `@aws-lambda-powertools/commons` package.
See checks running on PR, see screenshot below for e2e tests ran locally:
Optionally re-run e2e on GitHub Action.
[#484](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/484)  
[#547](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/547)
N/A
---
> feat(metrics): adopted Utility class

- docs/core/tracer.md
- packages/tracing/package-lock.json
- packages/tracing/package.json
- packages/tracing/src/Tracer.ts
- packages/tracing/tests/unit/Tracer.test.ts
- packages/tracing/tests/unit/middy.test.ts
This PR introduces changes to the `Tracer` module to adopt the forthcoming `Utility` class that will be released in the `@aws-lambda-powertools/commons` package.
See the checks in the PR, see the screenshot below that shows a successful e2e test run (locally):
Optionally re-run the e2e tests on GitHub Actions.
[#484](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/484)  
[#547](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/547)
N/A
---
> feat(tracer): adopted Utility class & updated unit tests

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/DOC_IMPROVEMENT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/RFC.md
Housekeeping for Github Issues templates, added RFC template.
This change should also make issues' titles clearer when scanning the issues list. 
N/A until merged.
N/A
---
> improv: github issues template, RFC added

- CONTRIBUTING.md
Following some confusion from community contributors and maintainers alike this PR adds a terse TL;DR; (aka too long; didn't read) section at the top of the `CONTRIBUTING.md` document to allow new contributors more easily get started.
Check changes in the Markdown file, preview below:
N/A
***Is this ready for review?:*** YES 
N/A
---
> docs: added summary section to contributing docs

- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-release-prod.yml
- .github/workflows/pr_lint_and_test.yml
- .github/workflows/run-e2e-tests.yml
- CONTRIBUTING.md
- package.json
This PR introduces changes in the workflows ran on GitHub Actions so that they make use of `npm@8.x` which we introduced as recommended version for the project in #492. This means that:
- We don't need to run `npm i` in the `packages/*` folders (which makes redundant the `npm run lerna-ci` step)
- We don't need a `package-lock.json` in each one of them as they are managed in the one at the root of the project
See this test run that I made on a fork of this repo, it uses the changes in this PR and also the ones in the #569 one: https://github.com/dreamorosi/aws-lambda-powertools-typescript/runs/5289484522?check_suite_focus=true
[#569](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/569)
N/A
---
By …
> chore: update actions to npm8

- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-release-prod.yml
- .github/workflows/pr_lint_and_test.yml
- .github/workflows/run-e2e-tests.yml
- docs/core/logger.md
- package-lock.json
- package.json
- packages/logger/package.json
- packages/logger/src/Logger.ts
- packages/logger/tests/e2e/basicFeatures.middy.test.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/helpers.test.ts
This PR introduces changes to the `Logger` module to adopt the forthcoming `Utility` class that will be released in the `@aws-lambda-powertools/commons` package.
See results of PR checks, also see the screenshot below that shows a successful e2e test run (on local):
WIP
Optionally, re-run the e2e tests on GitHub Actions
[#484](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/484)  
[#547](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/547)
N/A
---
> feat(logger): adopted Utility class & updated unit tests

- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
Following the changes introduced in #550 and [this comment](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/550#discussion_r815790620) from @saragerion, this PR introduces a new short "Usage" sub-section under the "Getting Started" section of each utility's page.
The goal of this section is to give a very basic example of the library's usage (just import & initialisation outside of handler) and point out why the utility has to be instantiated outside of the handler, explaining also benefits of doing so.
This wording was initially under the SAM section because that was the first code snippet but given that this _disclaimer_ is not SAM-specific it deserves its own section.
[#550](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/550)  
***Is this ready for …
> docs: Add usage sub-section in docs

- examples/cdk/package.json
With `aws-cdk` as a devDependency and instructing users to run `npm run cdk deploy -all` it can happen that `aws-cdk-lib` stops being compatible. In other words: Pinning the CDK CLI version can lead to issues with the runtime dependency on the CDK library.
I ran into this today with `"aws-cdk": "^2.0.0"` and `"aws-cdk-lib": "2.14.0"`. Receiving the following error on `npm run cdk deploy -all`:
`This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 15.0.0, but found 16.0.0)`
I believe unpinning (^) the CLI for example projects is reasonable and prevents interested users from running into versioning issues on their first contact with the project. …
> chore(examples/cdk): Unpin CDK CLI in devDependencies of CDK examples

- docs/core/logger.md
- packages/logger/examples/additional-keys.ts
- packages/logger/examples/errors.ts
- packages/logger/src/Logger.ts
- packages/logger/src/types/Logger.ts
- packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
- packages/logger/tests/unit/Logger.test.ts
`Logger` accepts a second parameter that allows to append additional keys and values to a single log item.
Currently, there are 5 use cases that are supported for this:
```ts
// 1) object
logger.info('This is the message value', { extra: 'parameter' });
// 2) object, object, ...
logger.info('This is the message value', { parameterOne: 'foo' }, { parameterTwo: 'bar' });
// 3) Object (that contains the message key)
logger.info( { message: 'This is the message value', extra: 'parameter' });
// 4) error
logger.info('This is the message value', new Error('Something happened!') );
// 5) error with custom key
logger.info('This is the message value', { myCustomErrorKey: new Error('Something happened!') });
```
However, the current implementation allows passing simple strings, arrays, and any …
> fix(logger): fix handling of additional log keys

- examples/cdk/package-lock.json
- examples/cdk/package.json
Following the `v0.7.0` release this PR bumps the version of the `@aws-lambda-powertools/*` dependencies along with all the other dependencies used.
Deploy examples & verify that they run.
N/A
N/A
---
> build(deps): updated dependencies in examples

- packages/logger/tests/e2e/basicFeatures.middy.test.ts
- packages/logger/tests/helpers/e2eUtils.ts
This PR addresses the issue of the AWS Lambda function invocation mode in the E2E tests for the **Logger** package.
Previously, multiple function invocations have always been performed in parallel. However, this made all the cold start checks impossible, because parallel invocations cause multiple cold starts.
The `invokeFunction` helper function now has an additional optional parameter `invocationMode` with allowed options  `PARALLEL` or `SEQUENTIAL`. This parameter lets the invokers control how to call the function-under-test.
Note: the parameter is of a union type which differs from the original proposal of a `boolean` parameter.
The reasoning behind it is simple: it makes the code easier to read.
Compare:
```ts
invocationLogs = await invokeFunction(functionName, 2, false); // what …
```
> fix(logger): enable sequential invocation in e2e test

- examples/cdk/package-lock.json
- examples/cdk/package.json
This PR is a follow up to #711 and updates `@types/jest` to a version compatible with `jest` and `ts-jest` bumped previously.
See PR checks.
#706 
#711 
N/A
---
> build(dev-deps): bump @types/jest

- docs/core/tracer.md
- docs/index.md
- package-lock.json
- packages/tracing/package.json
- packages/tracing/src/Tracer.ts
- packages/tracing/src/TracerInterface.ts
- packages/tracing/src/config/ConfigService.ts
- packages/tracing/src/config/ConfigServiceInterface.ts
- packages/tracing/src/config/EnvironmentVariablesService.ts
- packages/tracing/src/provider/ProviderService.ts
- packages/tracing/src/provider/ProviderServiceInterface.ts
- packages/tracing/src/types/Tracer.ts
- packages/tracing/tests/e2e/tracer.test.Decorator.ts
- packages/tracing/tests/e2e/tracer.test.DecoratorWithAsyncHandler.ts
- packages/tracing/tests/e2e/tracer.test.Manual.ts
- packages/tracing/tests/e2e/tracer.test.Middleware.ts
- packages/tracing/tests/e2e/tracer.test.ts
- packages/tracing/tests/helpers/tracesUtils.ts
- packages/tracing/tests/unit/ProviderService.test.ts
- packages/tracing/tests/unit/Tracer.test.ts
- packages/tracing/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/tracing/tests/unit/helpers.test.ts
This PR introduces a new feature for Tracer that allows to trace, by default, all outgoing HTTP(s) requests:
- Customers can opt-out from this feature by setting the `POWERTOOLS_TRACER_CAPTURE_HTTPS_REQUESTS` environment variable or `captureHTTPsRequests` constructor parameter to false when instantiating the Tracer
- The feature relies on `aws-xray-sdk` ability to instrument the standard library's `http` and `https` modules, as Tracer should be able to trace any 3rd party request client library that is built upon these two modules. Support to 3rd party HTTP clients is provided on a best effort basis (this disclaimer is specified in the documentation). `axios` has been tested during development and is included in integration tests.
- Documentation and JSDocs updated
- The feature is …
> feat: added captureHTTPsRequest feature

- .github/dependabot.yml
As discussed in #672 we would like to reduce the noise from Dependabot while still being up to date with the dependency ecosystem. This PR introduces the following changes:
- Set Dependabot to run weekly, on Fridays, at 5AM (`Europe/Amsterdam` tz)
- Set PR limit to 20 **
- Add Dependabot checks for Python dependencies in `docs/requirements.txt`, this was previously ignored.
** I propose to set this number to 20 (default is 5) so to increase the chance that Dependabot will open most/all the PR at once. This will allow the maintainers to have a better idea of the amount of PR to handle on the day (Friday). The current behaviour of 5 at the time made it so that Dependabot would keep opening PRs every time one was merged causing frustration. Read more about this setting …
> chore: updated depdendabot configs

- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-release-prod.yml
As of recently, the `on-merge-to-main` workflow has been failing in the very first step (`actions/checkout@v3`) ([example](https://github.com/awslabs/aws-lambda-powertools-typescript/runs/6155428079?check_suite_focus=true)). I have tried to run it again multiple times and then was able to track down the issue to a recent change in the action’s repo ([PR](https://github.com/actions/checkout/pull/770)).
Based on the content of that PR and related discussion, the GH action introduced a new default value around the `git config safe.directory` setting (`default true`) that seems to be what’s breaking our workflow, as well as others ([one](https://github.com/actions/checkout/issues/767) and [two](https://github.com/fwupd/fwupd/pull/4545)).
I have tried this in a fork, and setting the config to …
> fix(actions): removed token from remaining actions

- .github/workflows/on-release-prod.yml
Currently the `on-release` workflow [is failing](https://github.com/awslabs/aws-lambda-powertools-typescript/runs/6375189252?check_suite_focus=true) due to the following error:
```sh
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 2 approving reviews are required by reviewers with write access.
``` 
After a bit of research it appears that this is happening because the workflow is being executed with an identity that doesn't have enough rights to merge onto `main`, which is a protected branch.
As a part of #805 I removed the token as I didn't know the impact it would have. At the same time we haven't noticed since because we haven't made any release in the past few weeks.
This pr reintroduces the token into the workflow, as well as …
> fix(actions): reintroduce token to checkout repo in release workflow

- docs/core/logger.md
- packages/logger/examples/additional-keys.ts
- packages/logger/src/types/Log.ts
- packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
- packages/logger/tests/e2e/basicFeatures.middy.test.ts
- packages/logger/tests/unit/Logger.test.ts
This PR relaxes the restrictions introduced by #614. In #565, we decided to restrict the additional logging data objects in their shape. It turned out, that this restriction prevents from logging of arbitrary objects, which is inconvenient.  
In this PR, the type restrictions are removed, so it is now possible to specify any object as additional payload when calling the logger methods directly.
- Run unit tests
- Run E2E tests
- Review docs and examples
- Try to log an arbitrary object by providing it as a property of a string-indexed object, e.g.
```typescript
import { Logger } from '@aws-lambda-powertools/logger';
const logger = new Logger({ logLevel: 'DEBUG' });
export const handler = async (event) => {
logger.debug('Lambda invoked', { details: { event } });
};
```
No compile time …
> fix(logger): enable logging of arbitrary objects

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-release-prod.yml
- .github/workflows/pr_lint_and_test.yml
- .github/workflows/run-e2e-tests.yml
- .nvmrc
- CONTRIBUTING.md
- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- examples/cdk/src/example-function.ts
- examples/sam/template.yaml
- package.json
- packages/commons/tests/utils/e2eUtils.ts
- packages/logger/package.json
- packages/logger/tests/e2e/basicFeatures.middy.test.ts
- packages/logger/tests/e2e/childLogger.manual.test.ts
- packages/logger/tests/e2e/sampleRate.decorator.test.ts
- packages/metrics/package.json
- packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
- packages/metrics/tests/e2e/basicFeatures.manual.test.ts
- packages/tracer/package.json
- packages/tracer/tests/e2e/allFeatures.decorator.test.ts
- packages/tracer/tests/e2e/allFeatures.manual.test.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.ts
- packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
- packages/tracer/tests/helpers/populateEnvironmentVariables.ts
- packages/tracer/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/tracer/tests/unit/helpers.test.ts
AWS Lambda announced support for Node JS 16 a few days ago, this PR aims at adding support to that same runtime.
The changes in the PR revolve around:
- Adding the `nodejs16x` runtime to the e2e test matrix
- Making Node JS 16.x the default version for development
- Making Node JS 16.x the default version for CI/CD 
See successful run for GitHub Actions under this PR, as well as a successful run for the e2e tests that now includes the new runtime as part of the matrix ([link to execution](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/2319455980)).
#830
N/A
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> feat(all): nodejs16x support

- examples/cdk/package-lock.json
- examples/cdk/package.json
- examples/sam/package-lock.json
- examples/sam/package.json
In #925 we moved to `es2019` as a build target in an effort to support the Node.js 12.x in AWS Lambda. Now that the version (`v0.10.0`) has been released, this PR bumps the version in the `examples/*` folders to use it.
Check the result of the GitHub Actions that should be passing.
#925 
N/A
---
> build: bump examples version

- package-lock.json
- packages/logger/package.json
- packages/tracer/package.json
As reported in [this issue](https://github.com/dependabot/dependabot-core/issues/5226) there are a number of dependencies declared in packages part of the npm workspaces that are not being bumped by Depdendabot.
This PR bumps these dependencies manually in an effort to keep the dependencies up to date and avoid having noise in the PRs.
List of PRs:
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/938
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/936
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/934
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/932
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/927
https://github.com/awslabs/aws-lambda-powertools-typescript/pull/915
See results of automated checks, …
> build(deps): bump broken Depdendabot deps

- .github/workflows/on-release-prod.yml
- examples/cdk/package-lock.json
- examples/cdk/package.json
- examples/sam/package-lock.json
- examples/sam/package.json
This PR proposes a change that modifies the `lerna` command that is in charge of versioning. This command is executed as part of the `release` action/workflow. The change in this PR adds two flags that allow to perform pre-releases with a custom suffix.
The two flags added are:
- `--conventional-prerelease`
- `--preid rc`, this flag allows to set a custom suffix so that pre-releases will look like `0.11.0-rc.0`
The documentation for both flags can be found [here](https://github.com/lerna/lerna/tree/main/commands/version).
```sh
npx lerna version --conventional-commits --force-publish --conventional-prerelease --preid rc --yes
lerna notice cli v4.0.0
lerna info current version 0.10.0
lerna WARN force-publish all packages
lerna info Assuming all packages changed
lerna info …
```
> chore: updated rc release flow

- docs/core/tracer.md
After some feedback raised by a user we have realised that it's not exactly explicit that [Active Tracing](https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html) should be enabled in your Lambda function in order to see traces in X-Ray. This PR adds a sentence to the already existing note about permission to make this detail explicit in an effort to reduce confusion for future users who might not be familiar with the service.
See the diff, only added a sentence.
N/A
N/A
---
> docs: added note about active tracing

- docs/core/tracer.md
- packages/tracer/src/Tracer.ts
- packages/tracer/tests/unit/helpers.test.ts
As discussed in #1007, the Amplify CLI allows developers to run Lambda functions locally during development. When not running inside the AWS Lambda execution environment the `xray-sdk`, and by extension `Tracer`, will not be able to work properly as there isn't any X-Ray Daemon to connect to and send traces. Unless explicitly accounted for, the default behaviour of the SDK is to throw an exception.
This is a problem as it requires developers using Tracer to make changes to their code only to be able to test locally. Similarly to what we already do with SAM CLI, in this PR I introduced some logic to leverage a special value set by the Amplify CLI in the environment variables ([details here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/po …
> feat(tracer): auto disable when running inside amplify mock

- packages/logger/src/Logger.ts
- packages/logger/src/middleware/middy.ts
- packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.FunctionCode.ts
- packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/middleware/middy.test.ts
This PR aims at fixing a bug that was identified by @saragerion in the logger. In [v0.11.0](https://github.com/awslabs/aws-lambda-powertools-typescript/releases/tag/v0.11.0) we released a feature that allows to log the event parameter of a function handler. This is an opt-in feature that can be enabled by users by either passing a `logEvent` parameter equal to true in the middleware/decorator or by setting a `POWERTOOLS_LOGGER_LOG_EVENT` environment variable also equal to true. In the current iteration of the utility only the first method works.
I was able to reproduce the issue in my own tests.
There were two separate issues that contributed to this bug:
When deciding on whether to log the event or not a function named [`logEventIfEnabled`](https://github.com/awslabs/aws-lambda-powertools …
> fix(logger): POWERTOOLS_LOGGER_LOG_EVENT precedence is respected

- packages/tracer/src/Tracer.ts
- packages/tracer/tests/unit/Tracer.test.ts
As reported by @saragerion, the Tracer method `captureMethod` was incorrectly catching errors thrown within the body/scope of a decorated Class method defined by users. This is not a desired behaviour as the utility should not catch customers' errors but should simply run the logic defined in the decorator function and then throw the error along for customers to handle/throw in their code.
We had this behaviour on the radar as shown by the `TODO` comment present in that part of the code (see diff) but up until now we hadn't noticed / it wasn't reported. Additionally this same change was made to the `captureLambdaHandler` at some point in the past.
This PR modifies the logic of the `captureMethod` decorator and updates the unit tests related to it so that they actually test a method that …
> fix(tracer): capture method throws errors correctly

- examples/cdk/package-lock.json
- examples/cdk/package.json
- examples/sam/package-lock.json
- examples/sam/package.json
This PR updates the version of the Powertools utilities in both the SAM and CDK examples that are part of the repo.
N/A
N/A
N/A
---
> chore(docs): bump version in examples

- README.md
- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- docs/index.md
- docs/stylesheets/extra.css
- mkdocs.yml
- packages/logger/README.md
- packages/metrics/README.md
- packages/tracer/README.md
Changes introduced:
- Clarification that people can use the library in both TypeScript and JavaScript code bases
- References to Serverless TypeScript Demo
- One-liner command to install all three utilities at once 
- Contribute CTA
- Driving our roadmap CTA
- Consistency with messaging of blog post (utilities key features etc)
- Changed font size and remove ToC on the right side to improve readability in smaller screens
Docs:  npm run docs-runLocalDocker
N/A
---
> docs: minor improvements

- packages/tracer/src/Tracer.ts
- packages/tracer/tests/unit/Tracer.test.ts
using the captureMethod decorator the "this" is no longer the original obj so changing to the target fixes this
change the binding of the decorated method back to the target so the below code will work:
```
export class Lambda implements LambdaInterface {
@tracer.captureMethod()
myMethod(){
//other method is undefined as "this" is no longer the Lambda class
this.otherMethod()
}
otherMethod(){}
}
```
#1028 
---
> fix: wrong scope in captureMethod

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .github/scripts/constants.js
- .github/scripts/download_pr_artifact.js
- .github/scripts/label_missing_related_issue.js
- .github/scripts/label_pr_based_on_title.js
- .github/scripts/label_related_issue.js
- .github/scripts/save_pr_details.js
- .github/workflows/on-merge-to-main.yml
- .github/workflows/on_opened_pr.yml
- .github/workflows/record_pr.yml
- .github/workflows/reusable_export_pr_details.yml
- lerna.json
This PR introduces a series of JS scripts under `.github/scripts/*`. These scripts have been lifted from the Powertools for Python repo.
This PR introduces also a few workflows and updates others related to PRs, namely:
- One single workflow called `record_pr.yml` is now run as a result of an opened, modified (description/title only - not code), closed PR. This workflow runs and generates an artefact containing the PR details (i.e. title, number, etc.). This artefact is then used by the subsequent workflows.
- A second workflow called `label_pr_on_title.yml` is run as result of the successful execution of the `record_pr.yml`. It uses the generated artefact to obtain the details of the PR (via `reusable_export_pr_details.yml`) and it labels the PR based on the title. Given that this …
> chore(ci): housekeeping scripts & workflows related to PRs

- .github/workflows/measure-packages-size.yml
- .github/workflows/pr_lint_and_test.yml
- examples/sam/package-lock.json
- examples/sam/package.json
- packages/commons/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/tracer/package.json
This PR proposes changes to the workflow that is run every time a new PR is created & synchronised (aka new commit is pushed). It also spins off in a separate file the workflow that measures the size of the packages as well as changing is trigger from even based to on-demand.
The workflow that runs every time new code is added to a PR was running completely in sequential mode before this PR, aside from the matrix feature that was used to select the runtime. I have applied the same pattern also to the examples and break up the two sections in two different jobs that can now run in parallel:
I also have removed completely all the `lerna`-related commands in favor of the `npm workspaces` related ones. This allows us to select the packages we want to run the commands in. 
Initially I used a …
> chore(build): broke up pr workflow & measure package size

- docs/core/logger.md
Logger documentation update. Reading docs for the first time, this library looks great (looking forward to trying it out) but I believe a few of the log output examples are out of sync with the `handler.ts` code.
- [Appending persistent additional log keys and values](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#appending-persistent-additional-log-keys-and-values)
- example logs: add `"aws_account_id"` to highlighted text as this is also set in `persistentLogAttributes`
- [Appending additional data to a single log item](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#appending-additional-data-to-a-single-log-item)
- example log 2: update message
- example log 3 highlight `"extra"` property instead of `"xray_trace_id"`  
- …
> docs: update logger.md

- .github/workflows/on-merge-to-main.yml
- .github/workflows/reusable-publish-docs.yml
While working on #1053, the PR #1052 introduced a small bug that prevented the last step of the publishing process (the one for the docs) to run as it was incorrectly set as part of the same concurrency group of the workflow that was calling it.
Additionally, there was a leftover dependency from a previous iteration that prevented another workflow to complete.
Both issues are fixed, when merged this PR will close #1053.
See workflow run on merge or on release.
**Issue number:** #1053 
N/A
---
> fix(build): publish workflow concurrency + leftover dependencies

- docs/core/tracer.md
- packages/tracer/src/Tracer.ts
- packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
- packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
- packages/tracer/tests/unit/Tracer.test.ts
This PR fixes bugs in the `tracer.captureMethod()` and `tracer.captureLambdaHandler()` decorators. These decorators provide the class **prototype** as the `this` scope and not the **instance** of the class. While the prototype scope allows member functions to be run, it does not allow the customer to access *instance* member variables, as these instance member variables are not part of the class prototype.
Shout out to @dreamorosi for assistance in building an acceptable proof of concept in Slack.
I have added two new unit tests which reproduce the bug. You may run them to verify the change.
This is related to #1028.  #1026 previously attempted to fix this and got it us part of the way to a fix.
**Issue number:** #1056
***Is it a breaking change?:*** …
> fix(tracer): use instance as `this` in capture decorators

- docs/core/logger.md
- packages/logger/src/Logger.ts
- packages/logger/tests/e2e/sampleRate.decorator.test.FunctionCode.ts
- packages/logger/tests/unit/Logger.test.ts
As described in #1058 the decorator implementation was affected by an issue that prevented the decorated method/class to access other class members as the value of `this` was passed incorrectly.
This PR aims at fixing the issue, creating an unit test case, making minimal changes to the function in the e2e test to verify the change, and update docstrings/docs.
A long form explanation of the issue can be found at #1055, when merged this PR will close #1058. 
See checks below the PR, also see the results of the [e2e test run](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/2855192482).
**Issue number:** #1058  
N/A
---
By submitting this pull request, I confirm that you can use, modify, copy, …
> fix(logger): decorated class methods cannot access `this`

- docs/core/metrics.md
- packages/metrics/src/Metrics.ts
- packages/metrics/tests/e2e/basicFeatures.decorator.test.functionCode.ts
- packages/metrics/tests/unit/Metrics.test.ts
As described in #1057 the decorator implementation was affected by an issue that prevented the decorated method/class to access other class members as the value of `this` was passed incorrectly.
This PR aims at fixing the issue, creating an unit test case, making minimal changes to the function in the e2e test to verify the change, and update docstrings/docs.
A long form explanation of the issue can be found at #1055, when merged this PR will close #1057. 
See checks below the PR, also see the results of the [e2e test run](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/2855116627).
**Issue number:** #1057 
N/A
---
By submitting this pull request, I confirm that you can use, modify, copy, …
> Fix(metrics): decorated class methods cannot access `this`

- .github/workflows/on-merge-to-main.yml
- .github/workflows/publish-docs-on-release.yml
- .github/workflows/reusable-publish-docs.yml
As described in #1063 there were two issues related to the docs publishing after a release. Both issues were due to oversights on my part.
The first one was that I removed a step from the `reusable-publish-docs` ([link](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/reusable-publish-docs.yml)) and this step was the one that published the API docs under the correct version number in the docs. You can verify this by checking the `/latest` version of the docs, which works (while the `v1.1.0` doesn't). Adding back the step fixes the docs missing issue.
The second one was instead due to a behavior of GitHub Actions that I misunderstood.
For context: we have 2 workflows: `make-release` ([link](https://github.com/awslabs/aws-lambda-powertools-typescript/bl …
> fix(docs): docs published with incorrect version number + api docs missing after release

- docs/core/tracer.md
- packages/tracer/src/Tracer.ts
- packages/tracer/src/middleware/middy.ts
- packages/tracer/src/types/Tracer.ts
- packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.decorator.test.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.ts
- packages/tracer/tests/helpers/tracesUtils.ts
- packages/tracer/tests/unit/Tracer.test.ts
- packages/tracer/tests/unit/middy.test.ts
This PR adds options to `tracer.captureMethod()`, `tracer.captureLambdaHandler()` and the `captureLambdaHandler` middleware, allowing the user to disable response capture on a per-method basis. This change helps customers control when the tracer should capture information that might be sensitive or larger than 64K, but without disabling these capture mechanisms globally via `POWERTOOLS_TRACER_CAPTURE_RESPONSE=false` environment variable.
I have added multiple unit tests that simulate adding `captureResponse: false` to `tracer.captureMethod()`, `tracer.captureLambdaHandler()`, and the Middy `captureLambdaHandler` middleware. I have also added e2e tests for all three.
**Issue number:** #1064
---
By submitting this pull …
> feat(tracer): allow disabling result capture for decorators and middleware

- docs/core/metrics.md
- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
Amazon added support to up 30 dimensions per metric. In this PR we increase this limit
Review the code changes and the results of the automated builds.
**Issue number:**  #1044 
N/A
---
> feat(metrics):  increase maximum dimensions to 29

- .github/workflows/make-release.yml
In #1066 we decoupled the release to NPM & docs publishing processes. With that change the release of a new Powertools for TypeScript version works as follows:
- Manually trigger the "Make release" workflow - this will run unit tests, increase the version of the packages in the repo, create a new git tag, & publish the packages to NPM with increased version
- Manually make a release via GitHub releases UI - this will be using the tag created earlier, and once published it will trigger the other workflow that publishes the docs using the correct version number
With this PR I'm removing a leftover step from the "Make Release" workflow that was also publishing the docs.
Run the "Make release" workflow.
**Issue number:** #1063
***Is it a breaking …
> chore(build): update make-release.yml to remove redundant publish step

- .github/scripts/label_related_issue.js
At the moment, the workflow that is run every time a PR is merged attempts to label the issue related to that PR with a `pending-release` tag, to inform the person opening the issue that a change will be released soon.
At the moment the script that is run during this action has a bug coming from a leftover version of the script that makes it fail.
This PR aims at fixing the issue.
Observe the result of the "On PR Merge" workflow at the next PR merged.
**Issue number:** #1076
N/A
---
> fix(build): remove leftover code in action that labels issues on merge

- .github/scripts/get_pr_info.js
- .github/workflows/run-e2e-tests.yml
As described in issue #1077, at the moment it's not possible to run e2e tests on branches that reside on a fork of the repo. This PR, with the changes that are described below, aims at supporting this mechanism so that maintainers can trigger an integration test on PRs coming from the community. 
> **Warning**
> **This GitHub Action can be started only by maintainers of this repository. Maintainers should continue to thoroughly review external contributions to make sure the changes are appropriate prior to running the workflow on a given PR**.
This PR adds an optional input field to the workflow that runs integration tests, **now renamed "Run e2e tests** for consistency:
The field is an integer that represents a PR number from this repository. When a value is provided, **this value takes …
> improv(build): allow to specify PR number when running e2e tests

- packages/logger/src/Logger.ts
- packages/logger/tests/unit/Logger.test.ts
As reported in #1085 the injectLambdaContext decorator, when used on async methods, was not awaiting the method to return before performing other clean-up/post-exec logic. 
This PR introduces an `async/await` in the decorator logic so that the decorated method is always awaited. This should appears to fix #1085.
**Note to reviewers/readers:**
It should be noted that the decorator will now always `await` the decorated method regardless of it being an async function or not. Based on what I was able to find online awaiting a non-promise should be a no-op and should not have a performance impact. If this is not the case please point this out during review and we'll try to implement a conditional logic. At the moment I went with always awaiting for the reason above and also because this is how …
> fix(logger): wait for decorated method return before clearing out state

- packages/metrics/src/middleware/middy.ts
- packages/metrics/tests/unit/Metrics.test.ts
- packages/metrics/tests/unit/middleware/middy.test.ts
Metrics' Middy implementation was checking for `undefined` to evaluate `throwOnEmptyMetrics` and `captureColdStartMetrics`.
1. Get only the unit tests from this PR, see them fail
2. Get the update on `middy.ts`
3. rerun the unit tests and see them passed
Issue number: #1088 
---
> fix(metrics): captureColdStartMetric and throwOnEmptyMetrics when set to false was interpreted as true

- packages/tracer/src/Tracer.ts
- packages/tracer/tests/unit/Tracer.test.ts
In #1093 it has been reported that the `tracer.captureMethod` decorator was not properly detecting the name of the decorated class method, causing the name of the segment and the corresponding metadata entry to have an empty name.
I.e.
```ts
const tracer = new Tracer();
function passThrough() {
// A decorator that calls the original method.
return (_target: unknown, _propertyKey: string, descriptor: PropertyDescriptor) => {
const originalMethod = descriptor.value!;
descriptor.value = function (...args: unknown[]) {
return originalMethod.apply(this, [...args]);
};
};
}
class MyClass {
@tracer.captureMethod()
@passThrough()
async doSomething(): Promise<string> {
return 'foo';
}
}
const myClass = new MyClass();
await myClass.doSomething();
// Segment name will be "### "
/**
* Metadata entry …
```
> fix(tracer): captureMethod detects proper method name when used with external decorators

- layer-publisher/package-lock.json
- layer-publisher/package.json
Layer publisher build is failing due to mismatch between  NodeJS runtime  version and `ts-node` version (see https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3217811362/jobs/5261224013 for more details).
bump `ts-node` to 10.x.x version.
```
cd layer-publisher
npm ci
npm run cdk synth
```
---
> chore(build): fix ts-node version for layer-publisher

- docs/index.md
- layer-publisher/src/powertools-typescript-layer.ts
- layer-publisher/tests/unit/__snapshots__/layer-publisher.test.ts.snap
This PR manually bump the version of the layer in the doc to match the one published against latest version of Lambda PowerTools (1.2.1) https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3221623894.
It also fix the layer bundling.
Latest published version:  https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3221623894/jobs/5269933482#step:9:211
#1095 
---
> doc(layer): bump layer version to 2 to match the one built for latest version (1.2.1)

- layer-publisher/package-lock.json
- layer-publisher/package.json
- layer-publisher/src/powertools-typescript-layer.ts
- layer-publisher/tests/e2e/happy-case.test.lambda.ts
- layer-publisher/tests/unit/__snapshots__/layer-publisher.test.ts.snap
For some reason bundled layer was not updated properly when version change. 
After some investigation it looks like to be related to a bug in lambda.Code.fromAsset which does not take into account a change in bundling local command. Forcing the calculation of the hash based on bundling local command (which include version as well), layer is updated properly.
Check https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3232406370 or run e2e from your computer
Issue Number: #1114 
---
> chore(layer): fix bundling and e2e tests by manually setting hash of asset

- package.json
- packages/commons/package.json
- packages/idempotency/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/tracer/package.json
As reported in #1118 the `version` command present in the `package.json` files of all utilities is referencing another command (`format`) that has been renamed to `lint-fix` in a previous PR (#1105). This causes the release pipeline to fail.
This PR updates the content of the command from `npm run format && git add -A src` to `npm run lint-fix && git add -A src` (`format` becomes `lint-fix`).
See diff, then check next run of the `Make Release` workflow.
**Issue number:** #1118 
N/A
---
> fix(all): update version command to use lint-fix

- docs/index.md
After releasing a new version of the utilities and publishing the Lambda Layers, at least for the time being, we need to manually update the version of the Lambda layer in the documentation.
This PR updates the ARNs of the layer to point to the latest version.
Check that the docs have the latest version.
Optionally run `aws lambda get-layer-version-by-arn --arn arn:aws:lambda:eu-west-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:${VERSION_NUMBER} --region eu-west-1`, download the layer, and check that the version in the `package.json` of the layer corresponds to the latest one on NPM.
N/A
--- …
> docs: update layer version in docs

- docs/core/logger.md
- docs/index.md
This PR fixes some formatting/displaying issues around the layer section of the docs before the announcement.
It also fixes #1121.
Fix layers section:
Fix of #1121
**Issue number:** #1121
N/A
---
> docs(layers): fix format issues

- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- docs/index.md
As described in #1132 there are some changes related to how to support the project that were made in the Python version of Powertools and that needed to be replicated here. This PR addresses that action item.
This PR also cover some minor housekeeping in 3 more sections of the docs.
You can verify this change by running `docs-buildDockerImage` & `docs-runLocalDocker` while in the root folder (requires Docker).
Or check the screenshots provided below (only for main page):
<details>
</details>
**Issue number:** #1132 
N/A
---
> docs: main page updates around support

- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
To fix this bug, `clearDimensions();` and `clearMetadata();` are added to `publishStoredMetrics()` method to clear metadata and dimensions.
Bug described and reproduced in #1115.
**Issue number:** #1115 
---
> fix(metrics): metadata and dimensions not cleared on publish

- docs/index.md
Added code snippet to show how to deploy lambda with the powertools layer using Pulumi
---
> Added Pulumi code to deploy lambda with powertools

- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/workflows/make-release.yml
- .github/workflows/on-merge-to-main.yml
Check `on-merge` action results after this PR is merged.
**Issue number:** #1147 
N/A
---
> chore(internal): update workflow reference

- docs/core/tracer.md
- packages/logger/src/Logger.ts
- packages/logger/src/middleware/middy.ts
- packages/metrics/src/Metrics.ts
- packages/metrics/src/middleware/middy.ts
- packages/tracer/src/Tracer.ts
- packages/tracer/src/middleware/middy.ts
Following the report in #1142 a community member highlighted the fact that some examples in the docstrings of the packages (mainly Tracer) were inconsistent with the ones in the published documentation.
In response to the issue I went through the examples and checked that they were appropriate and consistent, this PR contains the changes related to this review.
Changes:
- Added middleware example to Metrics
- Standardized order of usages in main docstring: middleware, decorator, manual
- Cleaned up imports
- Standardized usage of single quotes 
Check diff.
**Issue number:** #1142 
N/A
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> docs(all): update & revise docstring examples

- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/middleware/middy.test.ts
As described in #1145, `v1.4.0` highlighted a bug that causes the service name to be cleared from metrics after flushing. 
The issue contains examples of the behavior and proposes a fix which has been implemented in this PR.
See checks in PR.
**Issue number:** #1145 
N/A
---
> fix(metrics): store service name in defaultDimensions to avoid clearing it

- docs/index.md
After each release, until #1124 is resolved, we need to manually bump the version of the layers in the docs.
This PR increments the version to 5, which corresponds to `v1.4.1`.
See changes in the diff.
---
> chore(docs): update layer version to 5

- .devcontainer/Dockerfile
- CONTRIBUTING.md
As described in #1154, GitHub announced a free tier for GitHub CodeSpaces. This PR adds a one-click launch button in the Contributing docs so that prospective contributors can get started easily.
See rendered CONTRIBUTING docs, optionally test the setup (it's free).
**Issue number:** #1154
---
> chore: add codespaces badge

- CONTRIBUTING.md
- package.json
As detailed in #1151 there's some room for improvement when specifying the default Node version to use during development.
This PR addresses this issue as well as making the `setup-local` npm command more readable (housekeeping).
Check the rendered version of the document.
**Issue number:** #1151
---
> docs: clarify nodejs16 requirement + fix command

- docs/core/logger.md
- packages/logger/src/Logger.ts
- packages/logger/src/config/ConfigServiceInterface.ts
- packages/logger/src/config/EnvironmentVariablesService.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/logger/tests/unit/helpers.test.ts
- packages/logger/tests/unit/middleware/middy.test.ts
It conditionally initializes console property as an instance of the internal version of Console() class (PR #748) or as the global node console if the `POWERTOOLS_DEV' env variable is set and has a truthy value.
#1030 
---
> feat(logger): disable logs while testing with jest --silent in dev env

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation_improvements.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/auto_assign-issues.yml
- .github/release-drafter.yml
- .github/scripts/constants.js
- .github/scripts/label_pr_based_on_title.js
- .github/scripts/label_related_issue.js
- .github/scripts/post_release.js
- .github/stale.yml
- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- docs/requirements.txt
- docs/roadmap.md
- mkdocs.yml
- packages/commons/README.md
- packages/logger/README.md
- packages/metrics/README.md
- packages/tracer/README.md
This PR includes:
- New public Project board
- New `Roadmap` page on the docs
- New `MAINTAINERS.md` document in the repo
- Updates to some of the scripts executed as part of the workflows & issue templates
- Update to MkDocs (housekeeping)
Technically this is not part of the PR (you won't find it in the diff), however the work done on this is very much related so I'm including it here for context.
I got the idea for this board from @heitorlessa and saw how he (mainly) and the rest of the maintainers use it. This board is meant to replace the two other boards (now closed) that we had for issues and PRs that kind of fell out of usage.
I don't expect other maintainers to use it, but you're welcome to if you'd like. I intend to use it as single pane of glass to monitor the repo and use it to …
> docs: add maintainers and public roadmap

- layer-publisher/src/powertools-typescript-layer.ts
Current bundling of lambda layer is including all dependencies from downstream dependencies including `@types/node` brought in especially by `aws-x-ray-sdk-core` -> `cjs-hooked`.
Simply manually removing `@types` from folder before zipping.
It is not breaking layer capabilities: https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3530267827
You can manually verify the improvment by deploying the layer to your own account (`cd layer-publisher && cdk deploy`) and check either the `cdk.out/assets` or download the published layer from AWS Console.
**Issue number:**  #1171
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> chore(layer): reduce size by 3 by removing @types packages

- .github/workflows/reusable-publish-docs.yml
- packages/idempotency/package.json
- packages/parameters/package.json
This PR reintroduces an install step in the workflow that publishes the docs, which [is currently failing](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/3541373134).
Check the workflow outputs after merging.
**Issue number:** #1182
---
> chore: add install step in docs workflow

- docs/index.md
After each release, until #1124 is resolved, we need to manually bump the version of the layers in the docs.
This PR increments the version to 6, which corresponds to `v1.5.0`.
See changes in the diff.
---
> docs: update layer version to 6

- docs/overrides/main.html
This PR introduces a banner at the top of the documentation website to inform customers that `v1.5.0` will be the last version that supports Nodejs 12 and the `nodejs12.x` AWS Lambda runtime. While we don't have a date scheduled for the next release, I don't expect there to be any release before Jan 2023 (over 2weeks away).
In addition to the banner, I have left a longer comment in the linked issue and made an announcement on the Discord server, as well as Twitter.
See docs local preview or published docs after merge.
**Issue number:** #1061
---
> docs: added Node.js 12 deprecation banner to docs

- packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.decorator.test.ts
- packages/tracer/tests/e2e/allFeatures.manual.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.manual.test.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.ts
- packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
- packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
As described in the linked issue, before this PR the integration tests were using `httpbin.org` as destination for some requests made during the Tracer tests.
This PR replaces that host with the base URL of the project's documentation to avoid reliance on 3rd party services.
See test run of integration tests published in the comments below the PR.
**Issue number:** #1193
---
> chore: remove httpbinorg request from integration tests

- package-lock.json
- packages/parameters/package.json
- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/ExpirableValue.ts
- packages/parameters/src/types/BaseProvider.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
This PR introduces some changes to the typing in `BaseProvider` so that it's now able to handle, transform, or return `Uint8Array` objects without necessarily coercing them to `string`.
The change came from the fact that AWS Secrets Manager can return both `string` (when the secret is stored as `SecretString`) and pure binaries aka `Uint8Array` (when the secret is stored as `SecretBinary`).
Consumers of the library should be able to both retrieve the latter and have them automatically transformed by the Parameters utility but also have them returned as-is (`Uint8Array`) in case they don't want to apply any transform.
The PR enables the behavior described above.
The PR introduces also some light housekeeping around dependencies (switches from `@aws-sdk/util-base64-node` to …
> refactor(parameters): BaseProvider support for Uint8Array

- package-lock.json
- packages/parameters/package.json
- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/SecretsProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/secrets/getSecret.ts
- packages/parameters/src/secrets/index.ts
- packages/parameters/src/types/BaseProvider.ts
- packages/parameters/src/types/SecretsProvider.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
- packages/parameters/tests/unit/SecretsProvider.test.ts
- packages/parameters/tests/unit/getSecret.test.ts
This PR introduces the `SecretsProvider` class which will allow the future Parameters utility to support retrieving secrets from AWS Secrets Manager.
The `SecretsProvider` supports two retrieval modes, both for retrieving one secret at the time. This is in line with the current functionalities supported by the Parameters utility in Powertools for Python.
- `get` this class method allows customers to retrieve a single secret by name and allows to specify aspects like the transformation to apply (none, binary, json, automatic) and max age (aka time to live for the item in the cache).
The class method will be used as such:
```ts
const secrets = new SecretsProvider();
const secret = secrets.get('foo');
console.log(secret); // value as string or binary
```
- `getSecret` utility function that …
> feat(parameters): SecretsProvider support

- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
This PR removes the method overrides from the `get` and `getMultiple` methods in the `BaseProvider` so that children classes can set their own types on these methods. See #1213 for full details.
See existing checks under the PR.
**Issue number:** #1213
---
> refactor: types in BaseProvider + added getMultiple alias to SecretsProvider

- docs/requirements.txt
- mkdocs.yml
This PR bumps the version of `mkdocs-material` to `9.0.2` (from `8.5.9`) and introduces a handful minor tweaks to the docs:
- Consolidate primary & accent colors to `deep orange` in both light & dark themes
- Add option to dismiss announcements / banners
- Add icon links for repo & Discord Server in site footer
See published version after merge.
**Issue number:** #1216
---
> chore(docs): bumped mkdocs-material to latest + small tweaks

- docs/snippets/parameters/adjustingCacheTTL.ts
- docs/snippets/parameters/appConfigProvider.ts
- docs/snippets/parameters/appConfigProviderCustomClient.ts
- docs/snippets/parameters/clientConfig.ts
- docs/snippets/parameters/dynamoDBProvider.ts
- docs/snippets/parameters/dynamoDBProviderCustomClient.ts
- docs/snippets/parameters/dynamoDBProviderCustomizeTable.ts
- docs/snippets/parameters/dynamoDBProviderLocal.ts
- docs/snippets/parameters/dynamoDBProviderMultiple.ts
- docs/snippets/parameters/forceFetch.ts
- docs/snippets/parameters/getAppConfig.ts
- docs/snippets/parameters/getParameter.ts
- docs/snippets/parameters/getParameters.ts
- docs/snippets/parameters/getParametersByName.ts
- docs/snippets/parameters/getParametersByNameGracefulErrorHandling.ts
- docs/snippets/parameters/getSecret.ts
- docs/snippets/parameters/sdkOptions.ts
- docs/snippets/parameters/secretsProvider.ts
- docs/snippets/parameters/secretsProviderCustomClient.ts
- docs/snippets/parameters/ssmProvider.ts
- docs/snippets/parameters/ssmProviderCustomClient.ts
- docs/snippets/parameters/ssmProviderDecryptAndRecursive.ts
- docs/snippets/parameters/transform.ts
- docs/snippets/parameters/transformAuto.ts
- docs/snippets/parameters/transformPartialFailures.ts
- docs/snippets/parameters/transformProvider.ts
- docs/snippets/parameters/tsconfig.json
- docs/utilities/parameters.md
> docs(parameters): main docs for the utility

- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/ssm/getParametersByName.ts
- packages/parameters/src/ssm/index.ts
- packages/parameters/src/types/AppConfigProvider.ts
- packages/parameters/src/types/BaseProvider.ts
- packages/parameters/src/types/SSMProvider.ts
- packages/parameters/src/types/index.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
- packages/parameters/tests/unit/getParametersByName.test.ts
As discussed in #1172, now that the main implementation of the utility is complete, we are able to pencil down the types of the various providers.
This PR removes the `# TODO` items from the code as well as fixing the types and their exports. 
See unit tests.
**Issue number:** #1172 
---
> chore(parameters): revisit utility types

- docs/core/tracer.md
- docs/snippets/tracer/accessRootTraceId.ts
- docs/snippets/tracer/basicUsage.ts
- docs/snippets/tracer/captureAWS.ts
- docs/snippets/tracer/captureAWSAll.ts
- docs/snippets/tracer/captureAWSv3.ts
- docs/snippets/tracer/captureHTTP.ts
- docs/snippets/tracer/captureMethodDecorator.ts
- docs/snippets/tracer/captureMethodManual.ts
- docs/snippets/tracer/decorator.ts
- docs/snippets/tracer/disableCaptureResponseHandler.ts
- docs/snippets/tracer/disableCaptureResponseMethod.ts
- docs/snippets/tracer/disableCaptureResponseMiddy.ts
- docs/snippets/tracer/escapeHatch.ts
- docs/snippets/tracer/manual.ts
- docs/snippets/tracer/middy.ts
- docs/snippets/tracer/putAnnotation.ts
- docs/snippets/tracer/putMetadata.ts
- docs/snippets/tracer/sam.ts
The code snippets are extracted to their own separate files, placed under `docs/snippets/tracer`.
And project documentation in `docs/core/tracer.md` references  the code snippets, which are extracted to their own separate files.
Code snippets of tracer created, in path `docs/snippets/tracer`: 
1. `basicUsage.ts`
2. `sam.ts`
3. `middy.ts`
4. `decorator.ts`
5. `manual.ts`
6. `putAnnotation.ts`
7. `putMetadata.ts`
8. `captureMethodDecorator.ts`
9. `captureMethodManual.ts`
10. `captureAWSv3.ts`
11. `captureAWSAll.ts`
12. `captureAWS.ts`
13. `captureHTTP.ts`
14. `disableCaptureResponseMethod.ts`
15. `disableCaptureResponseHandler.ts`
16. `disableCaptureResponseMiddy.ts`
17. `accessRootTraceId.ts`
18. `escapeHatch.ts`
Each code snippet is referenced as `--8<-- …
> docs(tracer): extract Tracer code snippets in separate files #1219

- docs/core/logger.md
- docs/snippets/logger/appendKeys.ts
- docs/snippets/logger/basicUsage.ts
- docs/snippets/logger/bringYourOwnFormatterClass.ts
- docs/snippets/logger/bringYourOwnFormatterHandler.ts
- docs/snippets/logger/clearStateDecorator.ts
- docs/snippets/logger/clearStateMiddy.ts
- docs/snippets/logger/createChild.ts
- docs/snippets/logger/decorator.ts
- docs/snippets/logger/eventDecorator.ts
- docs/snippets/logger/eventMiddy.ts
- docs/snippets/logger/extraData.ts
- docs/snippets/logger/logError.ts
- docs/snippets/logger/logSampling.ts
- docs/snippets/logger/manual.ts
- docs/snippets/logger/middy.ts
- docs/snippets/logger/sam.ts
- docs/snippets/logger/unitTesting.ts
The code snippets are extracted to their own separate files, placed under `docs/snippets/logger` .
And project documentation in `docs/core/logger.md` references the code snippets, which are extracted to their own separate files.
Code snippets of logger created, in path `docs/snippets/logger`:
1. basicUsage.ts
2. sam.ts
3. middy.ts
4. decorator.ts
5. manual.ts
6. eventMiddy.ts
7. eventDecorator.ts
8. appendKeys.ts
9. clearStateMiddy.ts
10. clearStateDecorator.ts
11. extraData.ts
12. logError.ts
13. createChild.ts
14. logSampling.ts
15. bringYourOwnFormatterHandler.ts
16. bringYourOwnFormatterClass.ts
17. unitTesting.ts
Each code snippet is referenced as --8<-- "docs/snippets/logger/<code-snippet>.ts" in docs/core/logger.md .
TODO items:
1. Lint code snippets created in path …
> docs(logger): extract Logger code snippets in separate files

- packages/commons/src/index.ts
- packages/commons/src/types/middy.ts
- packages/commons/src/utils/middleware/middy.ts
- packages/logger/src/middleware/middy.ts
- packages/metrics/src/middleware/middy.ts
- packages/tracer/src/middleware/middy.ts
Following the discussion in the linked issue (#1068), as well as other issues (#1080, #1081), customers who are using Powertools and bundling their TypeScript project with `tsc`, but that were not using any of the Middy-compatible middleware were having compile issues due to the dependency being missing.
We have investigated several workarounds:
- Adding the `@middy/core` dependency (#1218)
- Changing the exports to isolate the middleware & thus the dependency ([#1068#issuecomment-1377575328](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1068#issuecomment-1377575328))
- Reworking the types (this PR)
The first option was a no-go as it would have introduced an unnecessary dependency for those users having the issue. The second one would have constituted a breaking …
> refactor(all): add middy-like types to commons

- docs/index.md
After each release, until #1124 is resolved, we need to manually bump the version of the layers in the docs.
This PR increments the version to 6, which corresponds to `v1.5.1`.
See changes in the diff.
---
> docs: update layer version to 7

- docs/overrides/main.html
With `v1.5.1` released support for Node.js 12 has ended, so we can remove the deprecation notice that was at the top of the documentation.
Fixes #1236
See updated docs.
**Issue number:** #1236
---
> docs: remove Node.js 12 deprecation notice from docs

- docs/utilities/parameters.md
- package-lock.json
- packages/parameters/package.json
- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
- packages/parameters/tests/unit/DynamoDBProvider.test.ts
As described in the linked issue, the DynamoDBProvider is not currently tokenizing attribute names that contain any of the DynamoDB [reserved words](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html). This should be done by using [`ExpressionAttributeNames`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/interfaces/getitemcommandinput.html#expressionattributenames) in the queries.
This PR makes this change, which will fix #1238.
See updated unit tests that include reserved words and assert that they are tokenized correctly.
**Issue number:** #1238
--- …
> fix(parameters): Tokenize attribute names in `DynamoDBProvider`

- LICENSE-THIRD-PARTY
Following #1225, in which we lifted some types from `@middy/core`, it has correctly been raised by @saragerion in #1248 that we should add the MIT license to our `LICENSE-THIRD-PARTY` file for as long as these types/interface are part of our codebase.
This PR does this and will close #1248 once merged.
See diff.
**Issue number:** #1248
---
> chore(internal): add @middy/core license to proejct third-party licenses

- docs/index.md
Link to Powertools for Java . Http Url is changed from 
https://awslabs.github.io/aws-lambda-powertools-java/latest/
to 
https://awslabs.github.io/aws-lambda-powertools-java/
Run documentation locally  in Homepage read section `Tip` :
Powertools is also available for Python, Java, and .NET .
Click on the Java variant. 
It should navigate to https://awslabs.github.io/aws-lambda-powertools-java/
**Issue number:** #1246
***Is this ready for review?:*** YES 
---
> docs: correct link to Powertools for Java

- docs/Dockerfile
- docs/requirements.txt
- docs/snippets/package.json
- mkdocs.yml
- package-lock.json
- package.json
As part of the efforts described in #729 we are extracting the code snippets present in the docs in their own files, so that we can apply linting as part of our CI.
In order to do that, these code snippets need to:
- have access to external dependencies (i.e. `@middy/core`, `@aws-sdk/client-dynamodb`, etc.)
- have access to the current version of the `@aws-lambda-powertools/*` packages, which might be still not available on npm
- share the same `.eslintrc.js` file as the rest of the monorepo (for best practices)
To comply with these three points, we have decided to add the `docs/snippets` folder to the npm workspace that contains the rest of the utilities (and soon the `layer-publisher` folder too).
This PR does the following:
- initializes a new npm project under `docs/snippets` and …
> chore(docs): add `docs/snippets` to npm workspace

- docs/snippets/logger/bringYourOwnFormatterClass.ts
bringYourOwnFormatterClass code is back. 
see in the docs , Logger, section : Custom Log formatter (Bring Your Own Formatter), code snippet for
This is how the MyCompanyLogFormatter (dummy name) would look like:
...
**Issue number:** #1253
---
> fix(docs): logger bringYourOwnFormatter snippet

- packages/commons/jest.config.js
- packages/idempotency/jest.config.js
- packages/logger/tests/helpers/populateEnvironmentVariables.ts
- packages/metrics/jest.config.js
- packages/metrics/tests/helpers/populate-environment-variables.ts
- packages/metrics/tests/helpers/populateEnvironmentVariables.ts
- packages/metrics/tests/unit/Metrics.test.ts
- packages/parameters/tests/helpers/populateEnvironmentVariables.ts
- packages/tracer/jest.config.js
- packages/tracer/tests/helpers/populateEnvironmentVariables.ts
This maintenance PR fixes an issue highlighted in #1083 by standardizing the setup phase of all the Jest tests in the workspace. This PR makes the AWS Region in which integration tests are run configurable by the user while also setting a default in case no preference is specified.
This PR makes sure the all packages in the monorepo are using the now standard `packages/*/tests/helpers/populateEnvironmentVariables.ts` file which is referenced in the `jest.config.js` file and sets a number of standard environment variables throughout all tests.
One of these variables is the `AWS_REGION` one. Before this PR, some packages (Tracer and Logger) were always setting it while others (Metrics) weren't. This caused some tests to always run in an AWS Region regardless of user explicit settings while …
> chore(tests): standardize env setup for tests

- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/types/AppConfigProvider.ts
- packages/parameters/src/types/DynamoDBProvider.ts
- packages/parameters/src/types/SSMProvider.ts
- packages/parameters/src/types/SecretsProvider.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
- packages/parameters/tests/unit/DynamoDBProvider.test.ts
- packages/parameters/tests/unit/SSMProvider.test.ts
- packages/parameters/tests/unit/SecretsProvider.test.ts
This PR is intended to add support for custom AWS SDK v3 clients for `providers`
Providers covered:
**Issue number:**  #1222 
---
> feat(parameters): add support for custom AWS SDK v3 clients for providers

- .github/workflows/measure-packages-size.yml
With this change we can extend the package measurement workflow for parameters package to provide feedback in PRs. 
**Issue number:** #1036 
---
> chore: integrate parameters into CI/CD package measurement

- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
As described in #1275, now that we have linting for the code examples for the documentation present in `docs/snippets`, we want to have a dedicated line in the PR checks so that it's easier to identify failures during a PR authoring/review.
This PR updates the workflow that runs linting & tests by adding a separate and dedicated step for the linting of `docs/snippets`.
**Issue number:** #1275
---
> chore(docs): moved docs/snippets checks to separate step

- packages/parameters/tests/e2e/secretsProvider.class.test.functionCode.ts
- packages/parameters/tests/e2e/secretsProvider.class.test.ts
I have added a top comment in the e2e test file describing all the cases with setup and verification steps. I have also added a short guidance for future maintainers and contributors when adding new tests. Some of these pointers are generic, i.e. use dedicated resources for each test case. Others are more specific, i.e. we use custom function from `CustomFile.ts` to do X. 
**Issue number:**  #1279 
---
> tests(parameters): add comments to `SecretsProvider` e2e test

- examples/sam/README.md
Multiple users #1273 and #1281 reported having issues with the SAM examples in this repo due to the readme file not being explicit about the minimum version required for SAM CLI.
Node.js 18.x support was released in AWS SAM CLI version 1.65, users running a lower version and trying to compile the version run into the following error during compile:
```
Error: 'nodejs18.x' runtime is not supported
```
This PR adds a visual callout to the readme that specifies the version and links to instruction on how to upgrade.
See the updated readme, which looks like the image below (red box added to highlight changes):
**Issue number:** #1273 
---
By submitting this pull request, I confirm that you can use, modify, copy, and …
> docs(examples): made SAM CLI version requirement more explicit

- packages/parameters/tests/e2e/dynamoDBProvider.class.test.functionCode.ts
- packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
#1244 introduced integration tests for `DynamoDBProvider`, a provider part of the upcoming Parameters utility. At the time, the feature that allowed to inject a custom AWS SDK client was not present. The feature was added in #1222.
This PR adds some missing test cases to the integration tests of the provider to cover both the new feature, as well as testing cache and `forceFetch` behaviors.
See checks under the PR as well as integration tests.
Note that the integration tests for the Parameters utility are not yet connected to the workflow, so here's a screenshot of a successful run from my local environment:
**Issue number:** #1272
---
By submitting this pull request, I confirm that you can use, modify, copy, and …
> tests(parameters): added missing tests for `DynamoDBProvider`

- docs/core/logger.md
- docs/snippets/logger/createChild.ts
This PR is intended to improve docs for child loggers (`createChild` method). It is the last part of improving the child logger implementation, unit tests, and documentation. In the first PR #1178 child Logger implementation was changed, and new tests were introduced, in this PR #1264 implementation was improved, and new tests were introduced that cover all attributes inherited from a parent logger.
**Issue number:** #483 
---
> docs(logger): update child logger docs section and snippets

- docs/index.md
- packages/commons/README.md
- packages/idempotency/README.md
- packages/logger/README.md
- packages/metrics/README.md
- packages/tracer/README.md
As described in #1289, we want to tweak the project's description to better express the focus of the project and disambiguate the fact that Powertools is not just about observability, but instead it's - more broadly - about increasing developer velocity around Serverless workloads.
Closes #1289 
See diff in the PR, or rendered files in the branch.
**Issue number:** #1289
---
> chore(docs): update project's description

- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/ssm/index.ts
- packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
- packages/parameters/tests/e2e/ssmProvider.class.test.functionCode.ts
- packages/parameters/tests/e2e/ssmProvider.class.test.ts
- packages/parameters/tests/helpers/cdkAspectGrantAccess.ts
- packages/parameters/tests/helpers/parametersUtils.ts
- packages/parameters/tests/helpers/ssmSecureStringCdk.ts
This PR introduces the test suite that runs integration tests on the `SSMProvider` which is part of the upcoming Parameters utility. The PR also extends the `ResourceAccessGranter` helper to add compatibility for SSM.
This test suite deploys a CDK stack with a Lambda function and a number of SSM parameters. The function code uses the Parameters utility to retrieve the SSM parameters. It then logs the values to CloudWatch Logs as JSON objects.
Once the stack is deployed, the Lambda function is invoked and the CloudWatch Logs are retrieved. The logs are then parsed and the values are checked against the expected values for each test case.
- Name: param/a - Value: foo
- Name: param/b - Value: bar
- Name: param-encrypted/a - Value: foo-encrypted
- Name: param-encrypted/b - Value: …
> tests(parameters): integration tests for `SSMProvider`

- packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.ts
- packages/parameters/tests/helpers/cdkAspectGrantAccess.ts
- packages/parameters/tests/helpers/parametersUtils.ts
- packages/parameters/tests/helpers/sdkMiddlewareRequestCounter.ts
This PR introduces the test suite that runs integration tests on the `SSMProvider` which is part of the upcoming Parameters utility. The PR also extends the `ResourceAccessGranter` helper to add compatibility for SSM.
This test suite deploys a CDK stack with a Lambda function and a number of AppConfig parameters. The function code uses the Parameters utility to retrieve the parameters. It then logs the values to CloudWatch Logs as JSON objects.
Once the stack is deployed, the Lambda function is invoked and the CloudWatch Logs are retrieved. The logs are then parsed and the values are checked against the expected values for each test case.
The stack creates an AppConfig application and environment, and then creates a number configuration profiles, each with a different type of parameter. …
> tests(parameters): integration tests for `AppConfigProvider`

- .github/workflows/run-e2e-tests.yml
- packages/parameters/package.json
Now that all the integration tests for Parameters have been implemented, the utility can be added to the workflow that runs the e2e tests on GitHub.
This PR makes the changes necessary to run the tests part of this package once the [`run-e2e-tests.yml`](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/run-e2e-tests.yml) workflow is run and will close #1039 once merged.
See integration test run [here](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4234018154)
**Issue number:** #1039
---
> tests(parameters): update package to run as part of e2e tests

- packages/parameters/src/BaseProvider.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
- packages/parameters/tests/unit/getAppConfig.test.ts
As described in #1325, the current implementation of the transformer in the Parameters utility was not handling correctly values returned by AppConfig, which are always of type `Uint8Array`.
The linked issue has a more in-depth explanation, but essentially this PR updates the transformer so that both `json` and `binary` (aka base64) transforms can be used correctly with the provider.
Once merged this PR will close #1325.
See checks below the PR as well as successful integration tests run [here](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4244943927).
**Issue number:** #1325
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> fix(parameters): handle base64/binaries in transformer

- .github/workflows/reusable_deploy_layer_stack.yml
- .husky/pre-push
- docs/index.md
- layers/README.md
I have added three new regions: 
* `eu-south-2`
* `eu-central-2`
* `ap-southeast-4`
in test and prod accounts. I have also bumped the layer version to the same level, current level 8. 
I had to fix the pre-push hook, otherwise I couldn't create the PR. 
**Issue number:** #1169 
---
> feat(layers): add new regions

- .github/workflows/reusable_deploy_layer_stack.yml
- docs/index.md
- layers/README.md
This is a followup PR to #1322 and it adds a missing comma [in the workflow](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4253381544/workflow), as well as applying linting (currently manual) to markdown files.
Once merged, this PR closes #1169.
N/A
**Issue number:** #1169
---
> chore(layers): fix workflow + linting/housekeeping

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR revisits the templates for Issues and PR and once merged resolves #1331.
The changes made to the templates are the following:
- Changed rendering of code snippet in bug report to markdown, so that users can also add text or multiple code snippets
- Added placeholder texts to bug report to help users filling the form
- Added Discord link to issue type choice screen
- Added .NET link to all applicable issues
- Added new input field that whose value will be attached at the bottom of the issue and rendered (see screenshot below)
- Updated PR template to remove PR Status section, we can achieve the same with drafts & review requests
Example of rendered text:
**Issue number:** #1331
--- …
> chore: revisited issue & PR templates

- packages/commons/package.json
- packages/idempotency/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/tracer/package.json
As discussed in the linked issue, the `package.json` files of most all the utilities except Parameters had a wrong value in the `homepage` field which caused a 404 when users clicked on the rendered link on npm.
This PR fixes the url pointing it to the correct branch and resolves #1337.
Check the diff. The new link will be available on npm on the next release.
**Issue number:** #1337
---
> chore: updated `homepage` field in `package.json` files

- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
- packages/logger/tests/unit/helpers.test.ts
- packages/logger/tests/unit/middleware/middy.test.ts
This PR refactors some of the unit tests for Logger as well as applying consistent spacing/naming and simplifying some of the test cases and names. The functionalities and types of tests haven't been changed.
Once merged this PR closes #1332.
See checks below this PR.
**Issue number:** #1332
---
> tests(logger): revisit Logger unit tests

- packages/logger/src/middleware/middy.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/middleware/middy.test.ts
In #1328 it was reported that the Logger middleware `injectLambdaContext` was not clearing correctly the state and potentially leaking attributes set during an execution in the subsequent one.
Prior to this PR the middleware was improperly storing the initial persistent attributes of each logger instance passed to the middleware. This caused issues when clearing the state after each invocation, since the initial persistent attributes were now unusable.
This PR fixes the issue and adds new unit tests. Once merged this PR will close #1328.
<longer explanation coming soon>
Once merged, this PR closes #1328.
See checks under the PR as well as integration [test run here](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4272607387). New unit tests were added to …
> fix(logger): middleware stores initial persistent attributes correctly

- .github/workflows/make-release.yml
- .github/workflows/measure-packages-size.yml
- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-workflows-push-pr.yml
- .github/workflows/publish_layer.yml
- .github/workflows/reusable-publish-docs.yml
- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- .github/workflows/reusable_deploy_layer_stack.yml
- .github/workflows/run-e2e-tests.yml
I have pinned the version of the following actions in our workflows:
* actions/cache
* flochaz/pkg-size-action
* release-drafter/release-drafter
Closes #1025.
I have added the workflow from python repo to check for any unpinned using `zgosalvez/github-actions-ensure-sha-pinned-actions` workflow.
**Issue number:** #1025 
---
> chore(ci): pin 3rd party actions to sha commit

- .github/workflows/stale-issues.yml
- MAINTAINERS.md
As discussed in the linked issue, the stale issue automation that was set up in #1341 had filter that was too broad and that closed issues that shouldn't be closed.
This PR changes the filter to now include only the label `need-more-information` which should solve the issue.
The PR also increases the number of operations allowed to the workflow from 30 to 60.
Resolves #1345
Check output of next run tomorrow.
**Issue number:** #1345
---
> chore(ci): narrow down stale issue filtering

- .github/workflows/on_doc_merge.yml
- .github/workflows/reusable-publish-docs.yml
This PR fixes an issue in the workflow that publishes the docs after a PR that changes files related to them has been merged. As described in #1348, the workflow had a typo that caused it to fail immediately on startup.
The PR corrects the typo and also removes some extra lines, as well as one of the paths that can trigger the workflow (`examples/**`). This path was present in the workflow because in the Python repository the code snippets are under that path. In this repo however the snippets that are placed in the docs are under the `docs` path, so the extra path is unnecessary.
Once merged the PR closes #1348.
Check the next workflow run.
**Issue number:** #1348
---
By submitting this pull request, I confirm that you can use, modify, copy, and …
> chore(ci): fix typo in doc publishing workflow

- docs/index.md
As discussed in the linked issue, at the moment users opting for using the Lambda Layers published by Powertools didn't have clear instructions on how to deal with their local environment and dependencies. While this might be obvious for more experienced developers, there might be some customers that need a refresher, so this PR adds a section that clarifies this.
This PR closes #1357.
See rendered 
**Issue number:** #1357
---
> chore(docs): updated layer info

- .husky/pre-commit
- docs/snippets/package.json
- examples/cdk/package.json
- examples/sam/package.json
- layers/package.json
- package-lock.json
- package.json
- packages/commons/package.json
- packages/idempotency/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/parameters/package.json
- packages/tracer/package.json
As described in the linked issue, the current pre-commit hook was not linting & fixing issues on the staged files but instead was applying the fixes after the commit was made, thus defeating the purpose of the commit hook.
This PR, that fixes #1359, introduces a new developer dependency called [`lint-staged`](https://www.npmjs.com/package/lint-staged) (7M+ downloads/mo) that helps run linting on staged files specifically. In addition to fixing the issue, this library also helps optimize the process by linting only the files/paths touched in the commit. 
Checkout the repo, run `npm run init-environment`, then make a change that would result in a fix (i.e. extra spaces or extra `;`) and try making a commit.
**Issue number:** #1359
---
By submitting this …
> chore(ci): added lint-staged as pre-commit hook

- packages/commons/tests/utils/e2eUtils.ts
- packages/parameters/src/ExpirableValue.ts
- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
Fixes #1363 
When AppConfig parameters were requested beyond the cache expiration, they were returning empty. This was due to AppConfig `GetLatestConfiguration` returning an empty response if the active session already has the latest value.
This change introduces a local cache inside the `AppConfigProvider` that returns the most recent non-empty value in this scenario, matching the behavior of the [Python PowerTools Repository](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/parameters/appconfig.py#L121).
I added unit and e2e tests that cover this scenario. The simplest way is to develop a Lambda that uses the Parameters library with the AppConfig Provider, then invoke it a series of times, waiting beyond the `maxAge` of the configured …
> feat(parameters): AppConfigProvider to return the last valid value when the API returns empty value on subsequent calls

- packages/parameters/jest.config.js
- packages/parameters/package.json
- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/Exceptions.ts
- packages/parameters/src/ExpirableValue.ts
- packages/parameters/src/GetMultipleOptions.ts
- packages/parameters/src/GetOptions.ts
- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/appconfig/getAppConfig.ts
- packages/parameters/src/docs.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/secrets/getSecret.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/ssm/getParameter.ts
- packages/parameters/src/ssm/getParameters.ts
- packages/parameters/src/ssm/getParametersByName.ts
- packages/parameters/src/types/AppConfigProvider.ts
- packages/parameters/src/types/BaseProvider.ts
- packages/parameters/src/types/DynamoDBProvider.ts
- packages/parameters/src/types/SSMProvider.ts
- packages/parameters/src/types/SecretsProvider.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
- typedoc.js
This PR introduces docstrings for the new Parameters utility which are then converted with `typedoc` to the API reference published alongside the docs. In line with the other utilities I have documented all public methods more extensively and written long-form intros/reference for each main class & function. The public methods also have example usages which should help users, while the private/protected methods are documented only for the maintainers' sake.
Once merged, this PR will close #1043.
To help with the review I have published the api docs to [this url](https://dev.d3u1bwbtmwjex2.amplifyapp.com/modules/_aws_lambda_powertools_parameters.html) so that you can see them in your browser.
Note that once the PR is merged the URL will stop working and the docs will be available [on the …
> docs(parameters): add typedoc api docs

- package-lock.json
- packages/tracer/package.json
- packages/tracer/src/Tracer.ts
- packages/tracer/src/TracerInterface.ts
- packages/tracer/src/middleware/middy.ts
- packages/tracer/src/provider/ProviderService.ts
- packages/tracer/src/provider/ProviderServiceInterface.ts
- packages/tracer/tests/unit/ProviderService.test.ts
- packages/tracer/tests/unit/Tracer.test.ts
- packages/tracer/tests/unit/middy.test.ts
As reported in #1356, the current behavior of the Tracer and corresponding middleware is fairly unforgiving when it comes to handling missing segments. Prior to this PR, when calling the `getSegment` method, if a segment is not found, an error would be thrown.
This can happen either when users try to retrieve the current segment outside of the context of a function invocation or when the trace data is malformed and the X-Ray SDK is not able to derive the current segment.
This behavior, if not handled properly, can cause a function invocation to fail, which might not be desirable given that for many customers tracing is considered best-effort.
This PR:
- aligns the Tracer utility with the X-Ray SDK so that if a segment is not found, a warning is logged instead of throwing
- improves the …
> refactor(tracer): log warning instead of throwing when segment is not found

- packages/parameters/src/BaseProvider.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
As described in the linked issue, there's a need for a `clearCaches` helper function in the Parameters utility so that users can easily control cache eviction when testing code that uses the utility.
This PR introduces the function as part of the `BaseProvider` and adds unit tests for it. Once merged this PR will close #1381.
See new unit tests in the PR checks.
**Issue number:** #1381
---
> feat(parameters): add `clearCaches` function

- docs/snippets/package.json
- docs/snippets/parameters/testingYourCodeClearCache.ts
- docs/snippets/parameters/testingYourCodeClientHandler.ts
- docs/snippets/parameters/testingYourCodeClientJestMock.ts
- docs/snippets/parameters/testingYourCodeFunctionsHandler.ts
- docs/snippets/parameters/testingYourCodeFunctionsJestMock.ts
- docs/snippets/parameters/testingYourCodeProvidersHandler.ts
- docs/snippets/parameters/testingYourCodeProvidersJestMock.ts
- docs/utilities/parameters.md
- package-lock.json
This PR introduces a new section to the Parameters docs. This section features examples and recommendations on how to test end users' code that uses the utility. It shows how to test the code at different levels ranging from mocking the module from the imports, to using spies, to using a 3rd party library for a more fully featured mock API.
Once merged this PR closes #1321.
See screenshots below that show most/all the parts of the new section:
**Issue number:** #1321
---
> docs(parameters): add "testing your code" section

- packages/parameters/src/types/AppConfigProvider.ts
package: parameters
`AppConfigProvider.ts` uses incorrect import path for `GetOptionsInterface`.  This fix will use the correct relative path for the import.
This fix is for the issue [#1385](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1385)
**Issue number:** #1385
---
> fix(parameters): fix import path to use relative paths

- docs/index.md
- docs/snippets/parameters/adjustingCacheTTL.ts
- docs/snippets/parameters/ssmProviderDecryptAndRecursive.ts
- docs/utilities/parameters.md
- package-lock.json
- packages/commons/src/config/ConfigService.ts
- packages/commons/src/config/EnvironmentVariablesService.ts
- packages/commons/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/logger/src/config/EnvironmentVariablesService.ts
- packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/parameters/package.json
- packages/parameters/src/BaseProvider.ts
- packages/parameters/src/GetMultipleOptions.ts
- packages/parameters/src/GetOptions.ts
- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/config/ConfigServiceInterface.ts
- packages/parameters/src/config/EnvironmentVariablesService.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/tests/unit/SSMProvider.test.ts
- packages/parameters/tests/unit/config/EnvironmentVariablesService.test.ts
This PR introduces two new environment variables to configure the behavior of the Parameters utility around caching (`maxAge`) and decryption (for SSM only).
Today the utility allows customers to configure caching and decryption via arguments passed to the utility functions or class methods. This allows to configure the retrieval and lifecycle of parameter values in a granular way.
Some customers however want to have shared settings that apply to all parameter values. For this reason we are adding two environment variables: `POWERTOOLS_PARAMETERS_MAX_AGE` and `POWERTOOLS_PARAMETERS_SSM_DECRYPT` that once set will apply to all parameter retrievals.
Prior to this PR the Parameters utility was using environment variables only in one instance and only in the `AppConfigProvider`. With the …
> feat(parameters): ability to set `maxAge` and `decrypt` via environment variables

- .github/workflows/stale-issues.yml
- MAINTAINERS.md
This PR introduces a new `need-response` label that is designed to be used exclusively for the purpose of triggering the stale automation. Issues labeled as `need-response` that haven't had any interaction in 2 weeks will be marked as stale (`status/pending-close-response-required`) and subsequently closed as `status/rejected` after an additional week without interaction.
See the linked issue for full context. Once merged, this PR closes #1389.
**Issue number:** #1389
---
> chore: add new label for stale automation

- .github/workflows/measure-packages-size.yml
- .github/workflows/reusable_export_pr_details.yml
In preparation of the `set-output` [deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) from GitHub, this PR removes all its remaining usages from the workflows in this repo.
The PR applies similar changes to the ones already merged weeks ago in the Python repo awslabs/aws-lambda-powertools-python#1957, as well as updating the commit `sha` for one of the custom actions that was using the deprecated action and that was updated in the meanwhile.
Once merged this PR fixes #1127.
**Issue number:** #1127
---
**Disclaimer**: We value your time and …
> chore(ci): convert deprecated `set-output` command

- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/ssm/getParameter.ts
- packages/parameters/src/ssm/getParameters.ts
- packages/parameters/src/ssm/getParametersByName.ts
- packages/parameters/src/types/BaseProvider.ts
- packages/parameters/src/types/SSMProvider.ts
- packages/parameters/tests/unit/getParameter.test.ts
- packages/parameters/tests/unit/getParameters.test.ts
> **Note**
> To aid with the review I have prepared this [TypeScript playground](https://www.typescriptlang.org/play?ssl=59&ssc=23&pln=59&pc=29#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbA8mYASw1SgF4oByBAV2A0qgB8qAjQpBOERlygKxQlKAbgBQYjsAhw0CAMbQA4hGD4iJFFADeYqPqgB6AFTG9BqMagAJDAHcoAGxIBzKPSgBrCBDDuAFtAAbgiONNAcUPIKgeYGxoZxUNgIAB4Agi4QAPwAXFBINNisMkkmZhaWUADqgcCBcO4YUAAmEPLcBAHQYFwI2FBYBRjASZaJFm0d4MB5UKwYGI4QyGWmY1a1qg1N7oiomDjdUL2IA0NIIxsTBsD76FjYc-DIDzjqxKhiAL4SUjJyRRQFTAF4HR4AKSESCgEFS0iQLS0II+mh0awqFk2dR2Hjur0OA3qPT650al2AUAAFIISABKa5JfHgnBzATQyg-P5IaSyBTKVRgt7YAByzThCKRwNUqNIugszOFcyQECCpV+YlAkGlagInxQAFUkJ9yDqhYSxcwzfdCVCSFaaIiIGgOBAWuJNeBoAAlQVegA8AGlTY62i6VS0ADRQXAhp3ht0APnISVDztdLVh8IgiK0weyUDGBjTCczEpzUtjBZQdw4blyRcqMazkuRgptj0t1drSHrjabBlj5dz1oJkOhUALvvkWBa-prcDr0cdnkudiQyYbA+3lRVargSXygY …
> feat(parameters): stronger types for SSM getParameter

- packages/idempotency/src/IdempotencyConfig.ts
- packages/idempotency/src/persistence/BasePersistenceLayer.ts
- packages/idempotency/src/persistence/IdempotencyRecord.ts
- packages/idempotency/src/persistence/LRUCache.ts
- packages/idempotency/src/types/IdempotencyOptions.ts
- packages/idempotency/src/types/LRUCache.ts
- packages/idempotency/src/types/index.ts
- packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
- packages/idempotency/tests/unit/persistence/LRUCache.test.ts
This PR introduces a [Least Recently Used (LRU)](http://en.wikipedia.org/wiki/Cache_algorithms#Least_Recently_Used) cache to the `BasePersistenceLayer` of the upcoming Idempotency utility. In this type of cache the most recently-used items are kept in the cache while older ones, that have been accessed less recently are evicted as new items come in.
Users can configure any persistence layer that extends the `BasePersistenceLayer` to use this cache, and in doing so they can also specify the maximum amount of items that are kept in the cache:
```ts
const persistenceLayer = new MyPersistenceLayer(); // i.e. DynamoDB
persistenceLayer.configure({
config: new IdempotencyConfig({
useLocalCache: true, // defaults to `false`
maxLocalCacheSize: 50, // defaults to `256`
}),
});
```
When caching is …
> feat(idempotency): add local cache to `BasePersistenceLayer`

- packages/logger/src/Logger.ts
- packages/logger/src/types/Log.ts
- packages/logger/src/types/Logger.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/helpers.test.ts
Currently the Logger utility supports only methods that are also supported by the `Console` object: `warn`, `error`, `info`, and `debug`. On the other hand, Powertools for Python also supports a `critical` method, this is because the `logging` module that is part of the Python language supports it.
When using Powertools for Python, customers can emit structured logs that contain the `"level": "CRITICAL"` key/value. As reported in the linked issue, some of these customers might have setup alarms/metrics/queries that rely on this key/value being present in their logs.
Given that Powertools for TypeScript doesn't support this method/level (yet), these customers are prevented from using both versions of Powertools interchangeably in their serverless workloads.
This PR tries to cater to these …
> feat(logger): add `CRITICAL` log level

- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/secrets/getSecret.ts
- packages/parameters/src/types/SecretsProvider.ts
- packages/parameters/tests/unit/getSecret.test.ts
As discussed in the linked issue, the return types for the `SecretsProvider` part of the Parameters utility were fairly generic and could be improved by applying some heuristics based on the method used and some of the parameters passed. In addition to that, we could also provide a way for users to explicitly set the return type when they know the shape of the values they are retrieving.
This PR introduces new adaptive types for the `getSecret()` function as well as its class-based corespondent SecretsProvider.get()`.
The new types [use generics](https://www.typescriptlang.org/docs/handbook/2/generics.html) and modify the return type of the functions/methods based on the arguments passed to them or based on an explicitly set type.
For instance, if users pass transform: `json`, then we can …
> feat(parameters): add adaptive types to SecretsProvider

- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/idempotentDecorator.ts
- packages/idempotency/src/makeFunctionIdempotent.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
- packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
This is a small PR for the #1303 implementation. Most of the `IdempotencyHandler` was already implemented and aligned with decorator and function wrapper. In addition, I have added a try mechanism to mitigate rare race conditions error, similar to python implementation. 
**Issue number:** closes #1303 
---
> feat(idempotency): implement IdempotencyHandler

- docs/core/metrics.md
The rendering of this banner is wrong as the line below is missing a tab.
BEFORE
AFTER
**Issue number:** #1422 
---
> chore(docs): fix warning format in metrics documentation

- packages/commons/src/config/EnvironmentVariablesService.ts
- packages/commons/tests/unit/config/EnvironmentVariablesService.test.ts
- packages/tracer/src/Tracer.ts
- packages/tracer/src/TracerInterface.ts
- packages/tracer/tests/unit/Tracer.test.ts
This change adds a new `isTraceSampled` method to `Tracer`. It lets users find out if the current trace is sampled or not. This information may be included in structured logs along with the Trace ID.
Set the `Sampled=1` flag in the `_X_AMZN_TRACE_ID` environment variable and assert that `isTraceSampled` returns `true`.
Example:    `Root=1-5759e988-bd862e3fe1be46a994272793;Parent=557abcec3ee5a047;Sampled=1`
**Issue number:** #1378
---
> feat(tracer): add isTraceSampled method

- .github/PULL_REQUEST_TEMPLATE.md
- .github/boring-cyborg.yml
- .github/scripts/constants.js
- .github/scripts/label_missing_related_issue.js
- .github/scripts/label_pr_based_on_title.js
- .github/scripts/label_related_issue.js
- .github/scripts/post_release.js
- .github/semantic.yml
- .github/workflows/post-release.yml
- MAINTAINERS.md
This housekeeping PR introduces a number of changes related to automating issues and PRs:
- configures `boring-cyborg` to add `area/*` labels to a PRs based on the path of the files that have changed
- tweaks the configuration of the automation that adds `type/*` labels to PRs based on the title
- adds scopes to semantic title validation (i.e. `feat(logger)` -> `logger` is a scope)
- improves the regular expression that checks the issue number in the PR body to include [closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)
- improves the automation that labels issues linked to a PR being closed so that it removes any `status/*` label while adding the `status/pending-release` one
- adds a new …
> chore(ci): improve PR, Issues, and release automations

- .github/scripts/constants.js
- .github/scripts/label_missing_related_issue.js
- .github/scripts/label_pr_based_on_title.js
This PR is a followup of #1431 and fixes two issues introduced in that PR, which will close #133.
**Issue number:** #133
---
> chore(ci): fix regex & if statement in related issue script

- .github/workflows/closed-issues-message.yml
- .github/workflows/dispatch_analytics.yml
- .github/workflows/label_pr_on_title.yml
- .github/workflows/make-release.yml
- .github/workflows/measure-packages-size.yml
- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-workflows-push-pr.yml
- .github/workflows/on_opened_pr.yml
- .github/workflows/post-release.yml
- .github/workflows/publish_layer.yml
- .github/workflows/record_pr.yml
- .github/workflows/reusable-publish-docs.yml
- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- .github/workflows/reusable_deploy_layer_stack.yml
- .github/workflows/reusable_export_pr_details.yml
- .github/workflows/reusable_update_layer_arn_docs.yml
- .github/workflows/run-e2e-tests.yml
- .github/workflows/stale-issues.yml
As described in the linked issue, we want to apply a zero-trust policy on all 3rd party GitHub Actions by pinning their commit sha. This allows us to ensure that our workflow use only a version of the action that we know it's legitimate and we trust.
This PR introduces full commit hashes to all 3rd party GitHub Actions used in our workflows.
**Issue number:** #1440
---
> chore(ci): pin all 3rd party actions

- examples/sam/.eslintrc.js
- examples/sam/jest.config.js
- examples/sam/package.json
- examples/sam/src/common/constants.ts
- examples/sam/src/common/dynamodb-client.ts
- examples/sam/src/common/powertools.ts
- examples/sam/src/get-all-items.ts
- examples/sam/src/get-by-id.ts
- examples/sam/src/put-item.ts
- examples/sam/tests/sam.test.ts
This PR is part of a series as described in the linked issue #1456, which aims at adding `prettier` to the project and gradually modify the eslint configs to work with prettier and standardize the style of the project.
**Issue number:** #1456
---
> style(docs): apply standardized formatting

- .github/workflows/on_doc_merge.yml
- .github/workflows/publish_layer.yml
- .github/workflows/rebuild-latest-docs.yml
- .github/workflows/reusable-publish-docs.yml
Adds a new storage location for docs when they’re generated. Three of the files changed are for permissions changes to ensure that the `id-token` has write privileges. This PR uses a new environment (Docs) that has already been created in the repo settings.
**Issue number:** #1467 
---
> chore(ci): add step to publish docs to S3

- .devcontainer/devcontainer.json
- .gitpod.yml
- CONTRIBUTING.md
- README.md
- packages/commons/README.md
- packages/idempotency/README.md
- packages/logger/README.md
- packages/metrics/README.md
- packages/parameters/README.md
- packages/tracer/README.md
The PR updates the contributing docs by clarifying that prospective contributors should be using `npm@9.x`  instead of `8.x` like previously stated.
The change is needed because the `9.x` version comes bundled with the Node.js version used by the project.
Additionally, as housekeeping item, the PR also removes a redundant `{ target="_blank" }` notation in a link that was present in all README files.
Once merged, this PR closes #1477.
**Issue number:** #1477
---
> chore(docs): fix setup steps in contributing doc

- packages/idempotency/src/IdempotencyConfig.ts
- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/config/ConfigServiceInterface.ts
- packages/idempotency/src/config/EnvironmentVariablesService.ts
- packages/idempotency/src/constants.ts
- packages/idempotency/src/makeFunctionIdempotent.ts
- packages/idempotency/src/middleware/index.ts
- packages/idempotency/src/middleware/makeHandlerIdempotent.ts
- packages/idempotency/src/types/AnyFunction.ts
- packages/idempotency/tests/helpers/idempotencyUtils.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
- packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
This PR introduces a new Middy middleware that allows to wrap a Lambda handler and make it idempotent.
The middleware can be used like this:
```ts
import {
makeHandlerIdempotent,
DynamoDBPersistenceLayer,
} from '@aws-lambda-powertools/idempotency';
import middy from '@middy/core';
const dynamoDBPersistenceLayer = new DynamoDBPersistenceLayer({
tableName: 'idempotencyTable',
});
const lambdaHandler = async (_event: unknown, _context: unknown) => {
//...
};
export const handler = middy(lambdaHandler)
.use(makeHandlerIdempotent({ persistenceStore: dynamoDBPersistenceLayer }));
```
The first detail to notice is that contrary to the function wrapper and the class method decorator, this middleware doesn't leverage fully the `IdempotencyHandler` class. The reason for this is that Middy has a …
> feat(idempotency): `makeHandlerIdempotent` middy middleware

- packages/commons/tests/utils/e2eUtils.ts
As documented in the linked issue, when adding the integration tests to the Idempotency utility we mistakenly introduced a bug in the `e2eUtils` module that caused the invocation payload to be discarded when invoking the functions deployed as part of the integration test sequentially.
This PR fixes the issue by tweaking the function to support both sequential and parallel invocations. Once merged the PR will close #1488.
**Issue number:** #1488
---
> chore(tests): restore parameter in e2eUtils

- packages/logger/package.json
Fixed the link in the `package.json` file of the Logger utility, which as explained in the linked issue, was invalid.
**Issue number:** #1498
---
> chore(logger): correct homepage link in logger package.

- .github/scripts/label_related_issue.js
- .github/scripts/post_release.js
This PR aims at fixing the issue described in the linked PR that caused the workflow in charge of leaving a comment & labelling issues related to a release to fail the operation.
Aside from formatting, the changes involve making sure that when the script is running (upon new release) it's considering only closed issues that were labeled as `status/pending-release`. The other main change, that should fix the issue, however involves fixing a bug around how the existing labels were filtered and merged with the new ones.
**Issue number:** #1493
---
**Disclaimer**: We value your time and bandwidth. As such, any pull …
> chore(ci): update post release workflow

- .github/actions/cached-node-modules/action.yml
- .github/scripts/get_pr_info.js
- .github/workflows/run-e2e-tests.yml
- layers/tests/e2e/layerPublisher.test.ts
As described in the linked issue, some recent changes made to the way the packages were built broke the workflow that runs the integration tests. This PR applies the same changes by using the shared GitHub Action that is tasked with restoring the dependencies from cache & building the project.
**Issue number:** #1516
---
> chore(ci): added cached dependencies to e2e workflow

- .github/workflows/reusable-publish-docs.yml
Fixes the alias for "latest" in the versions drop down in the docs
**Issue number:** #1520 
---
> fix(docs): aliases in versions.json

- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- docs/index.md
- docs/snippets/tracer/captureAWS.ts
- docs/snippets/tracer/captureAWSAll.ts
- docs/snippets/tracer/captureAWSv3.ts
- docs/snippets/tracer/middy.ts
- mkdocs.yml
Following internal feedback, this PR addresses the concerns described in the linked issue as well as two other docs-related issues.
The callouts related to Middy in the docs have been updated to clarify that Powertools supports only Middy v3.x (current latest being v4.x). In doing so I updated also the command to install the correct version as well as linking to the new section of the [Middy docs dedicated to Powertools](https://middy.js.org/docs/integrations/lambda-powertools).
The code snippets related to patching/capturing AWS SDK clients have been updated to show a more realistic example of usage. Prior to this change the examples were only showing the capture action but were not explaining how to use the patched client.
Now the snippets use a variable to store the patched client and …
> docs(maintenance): update Middy sections

- .github/workflows/make-release.yml
- package-lock.json
- package.json
This PR introduces the necessary changes to publish packages to npmjs.com together with a provenance statement backed by Sigstore.
Specifically, the PR:
- bumps `lerna` (package used to publish) to version `6.6.2` which is the version that introduced support for the feature
- adds two permissions to the `publish-npm` job, according to the npm docs on the topic: https://docs.npmjs.com/generating-provenance-statements
- sets an environment variable `NPM_CONFIG_PROVENANCE=true`, which according to the npm docs & [the lerna maintainers](https://github.com/lerna/lerna/issues/3657#issuecomment-1535284598) should instruct the script to publish a provenance statement.
**Issue number:** closes #1436 
---
By submitting this pull request, I confirm that you can …
> chore(ci): bump `lerna` & add provenance config

- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/idempotentDecorator.ts
- packages/idempotency/tests/e2e/makeFunctionIdempotent.test.FunctionCode.ts
- packages/idempotency/tests/e2e/makeFunctionIdempotent.test.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
- packages/idempotency/tests/unit/idempotentDecorator.test.ts
- packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
In this PR we fix the issue to pass lambda context remaining execution time to save in progress. This only applies to function wrapper for now. We need to rework the entire decorator signature to extract the context, this will be handled in a separate PR. 
**Issue number:** closes #1482 
---
> fix(idempotency): pass lambda context remaining time to save inprogress

- packages/tracer/src/middleware/middy.ts
- packages/tracer/tests/unit/middy.test.ts
This PR introduces new logic to the `captureLambdaHandler()` Middy middleware offered by Tracer to allow it to close and restore any open segments whenever another middleware down in the stack returns early.
This is made possible by the `cleanupMiddlewares` function shipped in `commons` in the previous release. The new logic sets a reference to a cleanup function in the Middy internal storage using a scoped key. This way, Middy middlewares that want to return early can call the `cleanupMiddlewares` function which will execute all the cleanup functions available. This is useful for those middlewares like Idempotency, that want to return a result bypassing the Lambda handler and the normal Middy request lifecycle.
I have also added a unit test case to verify that the cleanup logic is …
> feat(tracer): close & restore segments when other middlewares return

- .github/workflows/reusable-publish-docs.yml
> fix(docs/ci): change how versions and aliases are inserted into versions.json

- .github/workflows/reusable-publish-docs.yml
Remove GH pages from GH actions. We no longer use GH pages, as we have migrated to our new docs hosting already.
**Issue number:** #1509
---
> chore(ci): remove GH pages

- docs/snippets/parameters/getParametersByName.ts
- docs/snippets/parameters/getParametersByNameGracefulErrorHandling.ts
- docs/utilities/parameters.md
- packages/parameters/README.md
This PR introduces changes to the `README` file of the Parameters utility to refresh its content and include informations relevant to the package, rather than general info about Powertools.
The advantage of doing this is that customers finding the package on npmjs.com can quickly get info on how to use common features of the package, as well as finding links to the docs for more in-depth explanations.
**Issue number:** #1532
---
> docs(parameters): refresh `README` for utility with usage examples

- packages/metrics/src/Metrics.ts
- packages/metrics/src/constants.ts
- packages/metrics/tests/unit/Metrics.test.ts
As reported in the linked issue prior to this PR the Metrics utility allowed to add a number of data points greater than the current 100 limit set by the EMF specification. This PR fixes the issue by ensuring that when a new data point is added and the limit is reached, all the stored metrics are flushed right away.
**Issue number:** fixes #1529
---
> fix(metrics): flush metrics when data points array reaches max size

- packages/idempotency/src/Exceptions.ts
- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/errors.ts
- packages/idempotency/src/index.ts
- packages/idempotency/src/middleware/makeHandlerIdempotent.ts
- packages/idempotency/src/persistence/BasePersistenceLayer.ts
- packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
- packages/idempotency/src/persistence/IdempotencyRecord.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
- packages/idempotency/tests/unit/idempotentDecorator.test.ts
- packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
- packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
- packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
- packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
- packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
We use `IdempotencyPersistenceLayerError` to handle any unknown error that might occur during persistent operations. Examples are IAM permissions, connections, or other configuration issues. Therefore, we need to preserve the original error, so the developer can understand the cause. 
With this PR we introduce a `cause` that enriches the original error. 
I have also renamed the error file to align with the recent refactoring of the parameter utility.
**Issue number:** closes #1530 
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be …
> feat(idempotency): preserve original error when wrapping into `IdempotencyPersistenceLayerError` 

- .github/scripts/release_patch_package_json.js
- README.md
- docs/snippets/package.json
- docs/snippets/parameters/customProviderVault.ts
- docs/snippets/parameters/customProviderVaultTypes.ts
- docs/snippets/parameters/customProviderVaultUsage.ts
- docs/utilities/parameters.md
- package-lock.json
- packages/commons/README.md
- packages/logger/README.md
- packages/metrics/README.md
- packages/parameters/README.md
- packages/tracer/README.md
This PR removes all the beta notices from the Parameters utility across the repo and also introduces a new section to the Parameters documentation that shows an example of creating your own custom parameters provider.
The beta notice has been removed from the readme files and from the documentation.
I have also finally added the remaining missing section from the Parameters docs that shows how to create your own provider, for this I have chosen HashiCorp Vault (like the Python version did).
If you want to test the snippet, you can do so with the following steps:
- Run HashiCorp Vault locally in a container (`finch/docker run -e VAULT_DEV_ROOT_TOKEN_ID=abcde --cap-add=IPC_LOCK -p 8200:8200 --name=dev-vault vault`)
- Change the init configs in the `customProviderVaultUsage.ts` file to …
> docs(parameters): release tasks + add docs on bring your own provider

- .github/workflows/publish_layer.yml
We no longer need the to run the bash script to determine the version for layer build step. Now, the input passed to the layer workflow is a correct version without the `v` prefix. 
**Issue number:** closes #1569 
---
> fix(ci): remove old release tag version for layer

- packages/tracer/src/provider/ProviderService.ts
- packages/tracer/tests/unit/ProviderService.test.ts
applied user agent to tracer
**Issue number:** closes #1539 
---
> chore(tracer): apply UA to AWS SDK clients used by Tracer

- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
- packages/parameters/tests/unit/DynamoDBProvider.test.ts
- packages/parameters/tests/unit/SSMProvider.test.ts
- packages/parameters/tests/unit/SecretsProvider.test.ts
Add user agent to clients user by parameters utility.
**Issue number:** closes #1537 
---
> chore(parameters): apply UA to AWS SDK clients used by Parameters

- .github/workflows/run-e2e-tests.yml
- packages/idempotency/README.md
- packages/idempotency/src/makeIdempotent.ts
- packages/idempotency/src/middleware/makeHandlerIdempotent.ts
- packages/idempotency/src/persistence/BasePersistenceLayerInterface.ts
- packages/idempotency/tests/e2e/makeHandlerIdempotent.test.FunctionCode.ts
- packages/idempotency/tests/e2e/makeHandlerIdempotent.test.ts
- packages/idempotency/tests/e2e/makeIdempotent.test.FunctionCode.ts
- packages/idempotency/tests/e2e/makeIdempotent.test.ts
- packages/idempotency/tests/helpers/idempotencyUtils.ts
- packages/idempotency/tests/unit/makeIdempotent.test.ts
This PR introduces new integration tests for the idempotency utility, and improves the existing ones by expanding the test coverage and assertions.
The integration tests now include both function wrapper and Middy middleware, and across both test suites I have improved the test coverage by including tests for concurrent requests, Lambda timeouts, expired idempotency records, and different combinations of payload selection (`dataIndexArgument`) and filtering (JMESPath expressions).
While working on the unit tests for the Middy middleware I found out that due to the way the middleware was written, if customers configured more than one Lambda handler in the same file, some of the Idempotency settings would leak between handlers, for example, having a single file `index.ts` with two handlers …
> test(idempotency): improve integration tests for utility

- .github/scripts/release_patch_package_json.js
- packages/commons/src/version.ts
- packages/idempotency/package.json
This PR changes the publish settings of the Idempotency utility to make it public (see change in `packages/idempotency/package.json`) as well as update the script executed when bundling so that the utility is marked with the `-beta` suffix.
Given that we haven't yet modified the `make-release` workflow to increment the version in `packages/commons/src/version.ts`, this PR also manually bumps the version (I ran `npx lerna version --conventional-commits --force-publish --no-push --no-git-tag-version --no-commit-hooks` locally to see what is going to be the next version - `1.11.1`).
**Issue number:** #1102
--- …
> chore(idempotency): mark the utility ready public beta

- .github/scripts/setup_tmp_layer_files.sh
- layers/src/canary-stack.ts
- layers/tests/e2e/layerPublisher.class.test.functionCode.ts
This PR removes parameters from the layer and from e2e tests. We ran into an issue for node14 and node16 runtimes for dependencies resolution and need to investigate further. 
**Issue number:** closes #1598 
---
> chore(maintenance): remove parameters utility from layer bundling and layers e2e tests

- .github/workflows/reusable_deploy_layer_stack.yml
This PR fixes the workspace name in the CI command for layer canary deployment.
**Issue number:** closes #1600
---
> chore(ci): fix canary deploy in ci with correct workspace name

- packages/batch/src/BasePartialBatchProcessor.ts
- packages/batch/src/constants.ts
- packages/batch/src/index.ts
- packages/batch/src/processPartialResponse.ts
- packages/batch/src/types.ts
- packages/batch/tests/helpers/factories.ts
- packages/batch/tests/unit/BatchProcessor.test.ts
- packages/batch/tests/unit/processPartialResponse.test.ts
- Renamed `itemIdentifier` and `batchResponse` types to match Python naming
- Renamed testing factories to be more accurate to their function
- Added `processPartialResponse()` function that acts as a function wrapper for batch processing
- Added unit tests for `processPartialResponse()` function
- Added some `TODO` comments for future async/sync function work
**Issue number: #1602** 
---
> feat(batch): Batch processing wrapper function

- packages/batch/src/SqsFifoPartialProcessor.ts
- packages/batch/src/index.ts
- packages/batch/src/processPartialResponse.ts
- packages/batch/tests/unit/SqsFifoPartialProcessor.test.ts
- Implemented `SqsFifoPartialProcessor` class to process messages from SQS FIFO queues
- Implemented unit tests for new class
- Added docstring for `processPartialResponse` method from last PR
**Issue number: #1587 ** 
---
> feat(batch): Implementing SQS FIFO processor class

- package-lock.json
- package.json
This PR removes `proxy-agent` from our dependencies, because we don't use it. I have ran unit and e2e tests and they passed. 
**Issue number:** closes #1610 
---
> chore(maintenance): remove proxy-agent from dependencies

- packages/batch/src/BasePartialProcessor.ts
- packages/batch/src/BatchProcessor.ts
- packages/batch/src/processPartialResponse.ts
- packages/batch/src/types.ts
- packages/batch/tests/helpers/handlers.ts
- packages/batch/tests/unit/BatchProcessor.test.ts
- packages/batch/tests/unit/processPartialResponse.test.ts
- Added BatchProcessingOptions type to hold context and future configuration options
- Added optional parameters to carry `options` parameter
- Added unit tests to check use of `options` parameter
**Issue number: #1607** 
---
> feat(batch): Support for Lambda context access in batch processing

- packages/logger/src/formatter/LogFormatter.ts
- packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
This PR introduces new logic to the `LogFormatter` class to allow the Logger utility to include the `cause` field to logs, when emitting a log that contains an `Error`. The `cause` field was added in Node.js 16 so we need to use a conditional logic to check if the `Error` passed in to the logger has the field or not before attempting to format it and include it in a log entry.
This logic is meant to be temporary and will be removed once we drop support for Node.js 14. This is documented in the docstrings of the new code.
Once this PR is merged, customers can pass an `Error` with a `cause` to the logger, which will format it like so:
```ts
logger.error(
"something went wrong",
new Error("boom", { cause: new Error("foo") })
);
// prints
{
"level": "ERROR",
"message": "something went wrong", …
```
> feat(logger): add `cause` field to formatted error

- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/semantic.yml
- MAINTAINERS.md
- docs/roadmap.md
This PR brings updates to the roadmap document to reflect the current status of the project. In addition to that, it adds the utilities we want to work next to the list of labels and issue templates.
**Issue number:** #1631
---
> chore(docs): update roadmap, labels, and issue templates

- packages/batch/src/AsyncBatchProcessor.ts
- packages/batch/src/BatchProcessor.ts
- packages/batch/tests/helpers/handlers.ts
- Updated `process` for both sync and async invocation
- Updated test context handlers to receive only `Context`
**Issue number: #1635** 
---
> fix(batch): Update processor to pass only context to handler

- .github/workflows/post-release.yml
As detailed in the linked issue, the post release workflow was not working as intended. Due to this, the comment that was left under the issues related to a release did not include the correct release number. This caused the maintainers to have to manually fix all the comments after each release.
This PR introduces a new step to the post-release workflow that checks the presence of the release version, and if it's not present in the inputs (which is the case when the workflow is triggered by a release), it retrieves it from the latest git tag.
This should fix the workflow and make it so that the comments are correct.
**Issue number:** closes #1493
--- …
> chore(ci): fix post release workflow

- docs/snippets/batch/accessProcessedMessages.ts
- docs/snippets/batch/customPartialProcessor.ts
- docs/snippets/batch/gettingStartedDynamoDBStreams.ts
- docs/snippets/batch/gettingStartedErrorHandling.ts
- docs/snippets/batch/gettingStartedKinesis.ts
- docs/snippets/batch/gettingStartedSQS.ts
- docs/utilities/batch.md
This PR introduces the following changes to the Batch Processing documentation page:
- Add tooltips/callouts in the code snippets to better explain certain lines
- Add flow charts to explain the data flow when processing batches & reporting failures
- Added a new error handling section
**Issue number:** #1639
---
> docs(batch): added flow charts

- packages/logger/src/Logger.ts
This PR introduces a minor internal change into the Logger class that, in its current implementation, can help customers who want to customize the utility by extending/subclassing the Logger class.
Prior to this PR when creating a new child logger, the creation of a new Logger instance was inline inside the `createChild` method. Customers wanting to extend the Logger by creating their own subclass were having a difficult time doing so because the child loggers would be creating using the original Logger class.
By extracting that logic into its own `createLogger` protected method customers can override the method and instantiate their own custom logger when creating a child.
> **Warning**
> Extending or depending on internal method comes with risks. Powertools for AWS is committed to avoid …
> chore(logger): extract logger creation into protected method

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation_improvements.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/ISSUE_TEMPLATE/share_your_work.yml
- .github/ISSUE_TEMPLATE/support_powertools.yml
As described in the linked issue GitHub has [added a new field](https://github.blog/changelog/2023-08-10-github-issues-projects-august-10th-update/#updates-to-issue-forms) to the Issue Templates that allows to specify one or more GitHub projects where newly created issues will be added automatically.
This PR sets [the public board](https://github.com/orgs/aws-powertools/projects/7) as default project for all new issues.
**Issue number:** closes #1651
---
> chore(ci): add project config to issue templates

- .github/workflows/reusable_deploy_layer_stack.yml
- docs/index.md
This PR adds `il-central-1` TelAviv region to layer deployment pipeline. After the merge and the first deployment, we will  increment the layer number to the latest version to align it to the same level for all regions.
**Issue number:** closes #1641
---
> chore(ci): add il-central-1 to layer deployment pipeline

- docs/snippets/idempotency/makeIdempotentJmes.ts
- docs/utilities/idempotency.md
This PR brings minor improvements of the idempotency documentation. Here is the list of all the changes to make the review a bit easier:
- add requirements to install the `@aws-sdk/client-dynamodb` package
- add autonumber to sequence diagrams
- remove “New to idempotency callout”
- `expiration` should not be broken in the table
- **MakeIdempotent function wrapper:** move callouts under the example to improve the reader flow
- change Types tab to `types.ts` to make it consistent with the code
- Choosing a payload subset for idempotency:
- change deserialising callout to warning (it’s not a tip)
- Don’t start with the callout, add it to text
- Payment scenario is not a quote
- the header example does not match the text (userid and product)
- Lambda timeouts
- clean up call outs and merge …
> chore(docs): improve idempotency documentation

- .github/actions/cached-node-modules/action.yml
- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
As discussed in the linked issue, npm recently reached version 10 which drops support for Node.js 14 and 16.
In order to continue running our CI, this PR pins the npm version to 9.x for all runtimes.
**Issue number:** closes #1665
---
> chore(ci): pin npm 9.x in workflows

- .github/workflows/run-e2e-tests.yml
- layers/src/layer-publisher-stack.ts
- layers/tests/e2e/layerPublisher.test.ts
- package-lock.json
- packages/logger/tests/e2e/basicFeatures.middy.test.ts
- packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
- packages/parameters/tests/e2e/secretsProvider.class.test.ts
- packages/parameters/tests/e2e/ssmProvider.class.test.ts
- packages/parameters/tests/helpers/resources.ts
- packages/tracer/package.json
- packages/tracer/tests/e2e/allFeatures.decorator.test.ts
- packages/tracer/tests/e2e/allFeatures.manual.test.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.ts
- packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
- packages/tracer/tests/helpers/tracesUtils.ts
In #1661 we have made changes to the integration test and as a result we inadvertently introduced some flakiness. This PR addresses this by applying the following fixes:
- reviewed & made unique all the test suffix across utilities
- introduce runtime key in SSM secret string name/path
- revisited X-Ray trace retrieval and moved to using function name instead of ARN
- unified workflow to use single job
---
> chore(tests): address integration test flakiness

- packages/parameters/src/types/AppConfigProvider.ts
- packages/parameters/src/types/SecretsProvider.ts
As discussed in the linked issue, when using the Parameters providers to retrieve values from Secrets Manager or DynamoDB and passing an options object with no `transform` setting, the return type of the value was mistakenly assigned to `undefined` rather than the default return type for that provider.
This PR fixes the issue by accounting for this case.
**Issue number:** #1670
---
> fix(parameters): return type when options without transform is used

- docs/index.md
- docs/snippets/batch/advancedTracingRecordHandler.ts
- docs/snippets/batch/customPartialProcessor.ts
- docs/stylesheets/extra.css
- docs/utilities/batch.md
- docs/utilities/parameters.md
- mkdocs.yml
This PR introduces a new section to the Batch Processing docs that details how to create dedicated subsegments for each record processed in a batch. I decided to include a dedicated section since the operation might not immediately be straightforward due to the presence of an iteration.
```ts
// ... imports omitted for brevity see docs/snippets/batch/advancedTracingRecordHandler.ts for full snippet
const processor = new BatchProcessor(EventType.SQS);
const tracer = new Tracer({ serviceName: 'serverlessAirline' });
const recordHandler = (record: SQSRecord): void => {
const subsegment = tracer.getSegment()?.addNewSubsegment('### recordHandler'); 
subsegment?.addAnnotation('messageId', record.messageId); 
const payload = record.body;
if (payload) {
try {
const item = JSON.parse(payload);
// …
```
> docs(batch): add section on how to trace batch processing

- docs/snippets/idempotency/workingWithBatch.ts
- docs/utilities/idempotency.md
This PR adds an example how to use batch processing in combination with idempotency. 
**Issue number:** closes #1675 
---
> docs(idempotency): add batch integration to idempotency docs

- docs/utilities/idempotency.md
- package-lock.json
- packages/commons/tests/unit/userAgentMiddleware.test.ts
- packages/idempotency/README.md
- packages/idempotency/package.json
- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/constants.ts
- packages/idempotency/src/index.ts
- packages/idempotency/src/persistence/BasePersistenceLayer.ts
- packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
- packages/idempotency/src/persistence/IdempotencyRecord.ts
- packages/idempotency/src/types/IdempotencyRecord.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
- packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
- packages/idempotency/tests/unit/makeIdempotent.test.ts
- packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
- packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
- packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
- packages/parameters/tests/unit/SSMProvider.test.ts
- packages/parameters/tests/unit/getAppConfig.test.ts
As discussed in the linked issue this PR targets three areas of the Idempotency package. All the change aim at improving the DX for customers who decide to bring their own persistence layer, the documentation on how to actually write your own persistence layer will be addressed in a future PR.
The `DynamoDBPersistenceLayer` relies on two AWS SDK modules: `@aws-sdk/client-dynamodb` and `@aws-sdk/lib-dynamodb`.
Before this PR the latter was listed as dependency while the other was only a development dependency. This mean that one was installed automatically upon installing the Idempotency utility while the other was to be installed manually by customers.
This PR marks both modules as `devDependencies` so that both must be installed explicitly by customers. This not only is in line with all …
> improv(idempotency): expose record status & expiry config + make DynamoDB Client optional

- docs/snippets/idempotency/advancedBringYourOwnPersistenceLayer.ts
- docs/snippets/idempotency/advancedBringYourOwnPersistenceLayerProvider.ts
- docs/snippets/idempotency/advancedBringYourOwnPersistenceLayerUsage.ts
- docs/snippets/idempotency/makeIdempotentJmes.ts
- docs/snippets/idempotency/samples/makeIdempotentJmes.json
- docs/snippets/idempotency/samples/workingWIthIdempotencyRequiredKeyError.json
- docs/snippets/idempotency/samples/workingWIthIdempotencyRequiredKeySuccess.json
- docs/snippets/idempotency/samples/workingWithBatch.json
- docs/snippets/idempotency/templates/tableCdk.ts
- docs/snippets/idempotency/templates/tableSam.yaml
- docs/snippets/idempotency/templates/tableTerraform.tf
- docs/snippets/idempotency/types.ts
- docs/snippets/package.json
- docs/utilities/idempotency.md
- package-lock.json
This PR introduces a new section to the docs that discusses how to build your own Persistence Layer for the Idempotency utility.
The section follows closely the structure of the same section found in [the Python docs](https://docs.powertools.aws.dev/lambda/python/latest/utilities/idempotency/#bring-your-own-persistent-store) but instead it shows how to implement the alternative persistence layer with a generic key-value store.
The PR also:
- extracts all the JSON events and infra snippets (i.e. SAM, Terraform, etc.) to their own dedicated files so that they can be linted/formatted
- adds a missing CDK sample to show how to create the table required for Idempotency
**Issue number:** #1484
---
By submitting this pull request, I confirm that you can use, …
> docs(idempotency): bring your own persistent store

- docs/requirements.txt
- docs/stylesheets/extra.css
We had a custom css for code highlight in light mode which was also applied in the dark mode, making the code unreadable. 
This issue has been fixed recently in [this PR](https://github.com/squidfunk/mkdocs-material/pull/6024). We can now upgrade MkDocs to 9.3.2 and apply custom CSS only to light mode, leaving dark mode code highlight as default. 
**Issue number:** closes #1693 
---
> docs: upgrade mkdocs to fix dark mode custom highlight style

- README.md
- docs/index.md
- packages/batch/README.md
- packages/commons/README.md
- packages/idempotency/README.md
This PR removes the beta warning from the README in batch and idemoptency utility. 
**Issue number:** closes #1690 
---
> docs: remove beta warning from batch and idempotency readme

- package-lock.json
- packages/idempotency/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/parameters/package.json
- packages/tracer/package.json
This PR removes the upper bound of the peer dependency on Middy that was introduced in the latest release.
As described in the linked issue, Powertools for AWS (TypeScript) is officially compatible only with Middy 3.x. This is documented both [our documentation](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#capturing-lambda-context-info)(see callout titled "A note about Middy") as well as Middy's documentation ([here](https://middy.js.org/docs/integrations/lambda-powertools)).
This is due to [Middy's release cycle](https://middy.js.org/docs/intro/release-cycle) that favors more recent Node.js versions, which is not compatible with our current release cycle which instead is aligned with Node.js versions supported by AWS Lambda.
After making the release however, …
> fix(maintenance): remove upper peer dependency Middy

- docs/core/tracer.md
- docs/snippets/tracer/putAnnotation.ts
- docs/snippets/tracer/putMetadata.ts
This PR introduces changes to the code snippets found in the Tracer documentation and related to adding annotations and metadata to a segment.
The original snippets were mistakenly not handling the opening and closing of a custom subsegment and were instead suggesting to attempt annotating the `facade` segment.
This is a mistake because that segment is managed by the service and cannot be modified, resulting in an error.
The PR fixes this and shows the full code snippet.
**Issue number:** #1699
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not …
> docs(tracer): update annotation & metadata docs to include full code

- .github/scripts/update_layer_arn.sh
- docs/index.md
According to the docs it should be {aws:region} [Reference](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#referencing-aws-specific-variables)
**Issue number:**  #1706 
---
> docs: typo for serverless framework

- packages/commons/src/types/utils.ts
Fixes #1689
**Issue number**: closes #1689
---
> improv(commons): add number key type to JSONObject type

- .github/workflows/run-e2e-tests.yml
- packages/idempotency/tests/e2e/constants.ts
- packages/logger/tests/e2e/constants.ts
- packages/metrics/tests/e2e/constants.ts
- packages/parameters/tests/e2e/constants.ts
- packages/parameters/tests/helpers/resources.ts
- packages/testing/src/constants.ts
- packages/testing/src/helpers.ts
- packages/testing/src/resources/TestNodejsFunction.ts
- packages/tracer/tests/e2e/constants.ts
This PR adds the AWS Lambda `arm64` architecture to the test matrix for our integration tests.
With this addition the tests are now run on both architectures and for all the supported runtimes. 
Since we don't use any architecture-specific package, nor any binary or native module, at least for the time being we can afford bundling the utilities once and using the same bundle on both `x86_64` and `arm64`.
The goal of these tests is to continuously verify that the utilities are compatible on both architectures on Lambda.
The PR also shortens the prefixes of all tests by removing the `E2E` string from the name, changing them from `Logger-E2E` to just `Logger`. This is done to account for the addition of the architecture in the name. The full name for the Stack and resources deployed as part …
> feat(layers): add `arm64` to integration test matrix

- .github/workflows/make-v2-release.yml
This PR introduces a new workflow that allows to publish pre-releases of our Powertools utilities to the npm registry.
The workflow is expected to last for the duration of the pre-release period and for this reason it takes some important shortcuts that make it deviate from the original release workflow. Contrary to most of the PRs related to v2 this one must be merged to `main` otherwise GitHub won't show the workflow as available.
Nevertheless, the workflow is expected to run always using the `feat/v2` branch and never on `main`.
The workflow doesn't generate git tags, change logs, nor version increment commit.
Since the workflow is expected to run on the v2 branch, which might have been rebased with `main` more or less recently, it always assumes that the version present in the …
> chore(ci): create v2 alpha release workflow

- packages/tracer/src/Tracer.ts
- packages/tracer/src/middleware/middy.ts
- packages/tracer/src/provider/ProviderService.ts
- packages/tracer/tests/unit/ProviderService.test.ts
- packages/tracer/tests/unit/Tracer.test.ts
- packages/tracer/tests/unit/middy.test.ts
This PR introduces some `try/catch` logic to the parts of the code that are in charge of closing a subsegment in decorators and middleware usage.
As reported in the linked issue, if the segment contains metadata that cannot be serialized calling the `subsegment.close()` (or `subsegment.flush()`) method will throw an error.
This happens because the segment is serialized using `JSON.stringify()` twice right before being emitted and so if the stringify method encounters an entity that doesn't know how to serialize, it'll throw an error.
Even though the linked issue propsosed to add this `try/catch` logic to the `tracer.putMetdata()` method, this would be useless as the serialization is done just-in-time before emitting the segment.
For this reason we must guard against runtime errors when …
> feat(tracer): add try/catch logic to decorator and middleware close

- docs/snippets/idempotency/idempotentDecoratorBase.ts
- docs/utilities/idempotency.md
- packages/idempotency/README.md
- packages/idempotency/src/idempotencyDecorator.ts
- packages/idempotency/src/index.ts
- packages/idempotency/tests/e2e/idempotentDecorator.test.FunctionCode.ts
- packages/idempotency/tests/e2e/idempotentDecorator.test.ts
- packages/idempotency/tests/unit/idempotencyDecorator.test.ts
This PR adds `@idempotent` decorator to the utility. We initially implemented it, but removed later due to uncertainty about decorator interface with TypeScript 5.x upgrade. Now we can restore and simplify the old implementation, by internally calling `makeIdempotent`, making it syntactic sugar for this functionality. This also means that most of e2e tests are very similar to the `makeIdempotent` tests, but we still need to make sure that it works when wrapping around decorator.
**Issue number:** closes #1700 
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged …
> feat(idempotency): add idempotency decorator

- packages/batch/jest.config.cjs
- packages/batch/package.json
- packages/batch/src/BasePartialBatchProcessor.ts
- packages/batch/src/BasePartialProcessor.ts
- packages/batch/src/BatchProcessor.ts
- packages/batch/src/BatchProcessorSync.ts
- packages/batch/src/SqsFifoPartialProcessor.ts
- packages/batch/src/constants.ts
- packages/batch/src/errors.ts
- packages/batch/src/index.ts
- packages/batch/src/processPartialResponse.ts
- packages/batch/src/processPartialResponseSync.ts
- packages/batch/tests/helpers/handlers.ts
- packages/batch/tests/unit/BasePartialProcessor.test.ts
- packages/batch/tests/unit/BatchProcessor.test.ts
- packages/batch/tests/unit/BatchProcessorSync.test.ts
- packages/batch/tests/unit/SqsFifoPartialProcessor.test.ts
- packages/batch/tests/unit/processPartialResponse.test.ts
- packages/batch/tests/unit/processPartialResponseSync.test.ts
- packages/batch/tsconfig.esm.json
- packages/batch/tsconfig.json
This PR introduces hybrid bundling (aka dual bundling) to the `@aws-lambda-powertools/batch` package. This adds support to ES Modules alongside the already existing CommonJS build.
The PR is inspired by the work done by @antstanley in #1734 and incorporates work done previously by @shdq and discussed in #521.
The main changes included in the PR are:
- add a new `tsconfig.esm.json` file in the `packages/batch` folder which extends the main `tsconfig.esm.json` at the root of the project, this file is used during the ESM build
- add new npm scripts to the package to handle the dual bundling
- add `exports` and `typesVersions` sections to the `package.json` to allow module resolution and TS types discovery based on module type (`commonjs` or `module`)
- update `prepack` npm script to clean …
> feat(batch): add esmodule support

- packages/tracer/src/Tracer.ts
- packages/tracer/src/middleware/middy.ts
- packages/tracer/tests/unit/Tracer.test.ts
- packages/tracer/tests/unit/middy.test.ts
As discussed in the linked issue, the Tracer utility logs a warning when it can't manipulate a segment. This is done to avoid throwing an error and blocking customer code and he log includes the name of the segment that threw an error.
Prior to this PR the name of the segment is included by concatenating a string with a non-literal variable, which according to [Semgrep guidance](https://semgrep.dev/r?q=javascript.lang.security.audit.unsafe-formatstring.unsafe-formatstring) can allow an attacker to inject a format specifier in the string and forge the log message.
This PR removes the string concatenation in favor of using the format function on the console object (i.e. `console.warn('hello %s', 'Bob');`) so that the string interpolation is handled by the language.
**Issue number:** #1749 …
> chore(tracer): update warning to better format segment name

- packages/idempotency/src/idempotencyDecorator.ts
- packages/logger/src/Logger.ts
- packages/metrics/src/Metrics.ts
- packages/tracer/src/Tracer.ts
As described in the linked issue, the VSCode intellisense, aka the tooltips that show documentation when you hover a method, were not playing well with code blocks containing a decorator due to it starting with `@`.
This caused the code block for decorators to render incorrectly and disrupt the indentation for the rest of the docstring. This was purely a cosmetic issue and the content of the docstring, nor runtime behavior, were affected.
The issue is caused by TypeScript & its docstring parsing, which interpret the `@` as the beginning of a keyword (i.e. `@note`, `@link`, etc.) instead of a decorator.
We have been tracking the issue since early 2022 (microsoft/TypeScript#47679) but a fix was never implemented. A couple of days ago however another user commented under the issue sharing …
> chore(docs): add invisible unicode char to decorator docstrings

- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/base/BaseProvider.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
This PR introduces a slight refactor to the constructor of all the Parameters providers  so that the respective AWS SDK client is instantiated only when strictly needed.
Before this PR we were instatianting a new client optimistically and then overwriting it with the customer-provided one if one was passed.
This, while simplifying the flow of the code, caused an unnecessary runtime penalty for advanced customers who were providing their own client and that now were instantiating two clients only for one to be discarded.
While doing this refactor I have also taken the opportunity to generalize the logic that creates a new client or checks the existing one, as well as the one that adds the UA to it, and move it to the `BaseProvider` class. This way I was able to shave a few kb (~9kb) from …
> chore(parameters): refactor provider constructor to init client as needed

- packages/commons/src/awsSdk/userAgentMiddleware.ts
- packages/commons/tests/unit/awsSdk.test.ts
This PR modifies the logic used to detect whether or not an AWS SDK client already has a Powertools User Agent middleware attached to it or not. This logic is needed because middlewares added to the client middleware stack must be unique.
The change in the PR switches the logic from an exact match that includes the name of the middleware and its tags, to instead use only the name. This will make the comparison more robust.
**Issue number:** closes #1761
---
> chore(commons): update Powertools UA middleware detection

- packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
This PR introduces a slight refactor to the constructor of the Idempotency persistence layer so that the DynamoDB AWS SDK client is instantiated only when strictly needed.
Before this PR we were instatianting a new client optimistically and then overwriting it with the customer-provided one if one was passed.
This, while simplifying the flow of the code, caused an unnecessary runtime penalty for advanced customers who were providing their own client and that now were instantiating two clients only for one to be discarded
**Issue number:** #1767
---
**Disclaimer**: We value your time and bandwidth. As such, any …
> chore(idempotency): refactor aws sdk init logic

- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- docs/utilities/idempotency.md
The class method decorators offered by the project are currently implemented in a way that fits asynchronous methods. When decorating an asynchronous method everything works as intended. When instead decorating a synchronous method, the decorator replaces its implementation with an asynchronous one causing the caller to have to `await` the now decorated method.
This was previously not explicitly called out and caused confusion for some customers. 
This PR adds a callout in the docs to document this behavior.
**Issue number:** closes #1204
---
**Disclaimer**: We value your time and bandwidth. As such, any pull …
> docs(maintenance): add clarification about async decorators

- .gitpod.Dockerfile
- .gitpod.yml
This PR modifies the Gitpod configuration to pin a specific base image for the workspace and configure dependencies in it. 
Prior to this PR Gitpod was starting a workspace using the latest image available, which in some cases like now it's not desirable. Following the same practices that we use in other areas like dependencies and GitHub Actions, I have changed the configuration so that we are pinning a specific version of a specific Docker image identified by its `sha` number. I got this idea [from the Python repository](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.gitpod.Dockerfile) which does the same. 
The new setup specifies a Dockerfile which uses the base workspace image and builds on top of it. I decided not to use the node image provided by Gitpod …
> chore(maintenance): improve Gitpod config

- packages/logger/src/Logger.ts
- packages/logger/src/config/EnvironmentVariablesService.ts
- packages/logger/src/formatter/LogFormatter.ts
- packages/logger/src/types/Log.ts
- packages/logger/tests/unit/EnvironmentVariablesService.test.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/tracer/tests/helpers/tracesUtils.ts
By default the AWS Lambda execution environment has the `TZ` variable set to `UTC` ([source](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime)). Likewise, the Logger utility emits logs with timestamps formatted as UTC.
**This PR does not change the behavior of the Logger utility** but only:
- Adds a method to the `EnvironmentVariablesService` so that the `TZ` value can be fetched, with fallback on the `UTC` value
- Adds an `envVarsService` property and constructor option to the `LogFormatter` class so that I can accept a reference to an instance of `EnvironmentVariablesService` when instantiated. This property is optional.
At the moment the none of the additions is used by the Logger directly as the default behaviors in both Lambda and …
> chore(logger): set default UTC timezone

- .github/workflows/ossf_scorecard.yml
> chore(ci): Add OSSF Scorecard Workflow

- .github/workflows/closed-issues-message.yml
- .github/workflows/label_pr_on_title.yml
- .github/workflows/make-release.yml
- .github/workflows/make-v2-release.yml
- .github/workflows/measure-packages-size.yml
- .github/workflows/on-doc-v2-merge.yml
- .github/workflows/on-merge-to-main.yml
- .github/workflows/on-workflows-push-pr.yml
- .github/workflows/on_doc_merge.yml
- .github/workflows/on_opened_pr.yml
- .github/workflows/post-release.yml
- .github/workflows/pr-run-linting-check-and-unit-tests.yml
- .github/workflows/rebuild-latest-docs.yml
- .github/workflows/record_pr.yml
- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- .github/workflows/reusable_deploy_layer_stack.yml
- .github/workflows/reusable_export_pr_details.yml
- .github/workflows/run-e2e-tests.yml
- .github/workflows/stale-issues.yml
Adds a root `permissions` to the base of every workflow that was missing one.
**Issue number:** #1799 
---
> chore(ci): sets base permissions on all workflows

- examples/cdk/src/example-stack.ts
The version for the layer was changed from version 18 to 24.
**Issue number:** fixes #1793
---
> chore(docs): fix layer version in CDK example

- docs/core/logger.md
This PR removes the `logEvent` and `sampleRateValue` values from the sections of required parameters. I have introduced a new section **Environment variables** to collect all the option in one place. In addition, I added a small clarification that `POWERTOOLS_LOGGER_LOG_EVENT` only works with `injectLambdaContext` to avoid misunderstanding. 
**Issue number:**  closes #1814
---
> docs(logger): remove logEvent from required settings

- docs/core/logger.md
- docs/core/tracer.md
- docs/maintainers.md
Fixing some typos on docs.
I skipped creating a issue. :pray:
---
> docs: fix some typos

- docs/maintainers.md
- docs/roadmap.md
- docs/snippets/batch/gettingStartedErrorHandling.ts
- docs/utilities/idempotency.md
This PR fixes additional typos that were missed in the previous PR: #1824 
**Issue number:**  closes #1825 
---
> docs: fix typos

- .github/semantic.yml
Updates Semantic PR config to allow dependabot PRs with `deps` scope.
**Issue number:** #1859
---
> chore(ci): allow dependabot PRs

- .github/semantic.yml
Adding `deps-dev` for semantic PR config.
**Issue number:** #1859 
---
> chore(ci): allow deps-dev for semantic PR

- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/constants.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
As discussed in the linked issue, the AppConfig provider in the Parameters utility stores a session token returned by the service that should be used for the subsequent call. By default the token has a [duration of up to 24hrs](https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_appconfigdata_StartConfigurationSession.html#API_appconfigdata_StartConfigurationSession_ResponseElements) and if the provider attempts to retrieve a configuration using an expired token it'll result in a bad request exception.
For most Lambda-based workloads this is not an issue since the execution environment is likely to have been recycled before the token has the chance to expire. For those customers who use provisioned concurrency or who decide to use the Parameters utility outside of Lambda …
> fix(parameters): refresh AppConfig session token after 24 hrs

- .github/workflows/make-release.yml
- .github/workflows/make-v2-release.yml
This PR adds a new environment scope to the release workflows so that the npm token used to make releases can be accessed only by said workflows.
**Issue number:** #1956
---
> chore(maintenance): add environment scope to npm token

- .github/dependabot.yml
This PR adds the `aws-cdk` dependency to the Dependabot group that previously contained only `aws-cdk-lib` and dependencies starting with the `@aws-cdk/**` pattern (experimental constructs). In some less common cases, an update of library might not work with the cli, so bumping these two dependencies together makes more sense.
**Issue number:** #1858
---
> chore(maintenance): group CDK cli with other CDK dependencies

- .github/workflows/make-v2-release.yml
- .github/workflows/on_doc_merge.yml
- .github/workflows/publish_layer.yml
- .github/workflows/rebuild_latest_docs.yml
- .github/workflows/reusable_publish_docs.yml
This PR follows #1978 and makes additional changes to the workflows, namely:
- remove the `contents: write` permission from the workflow used to make v2 releases since there's no commit
- remove `actions: write` from the docs-related workflows - initially I thought this was needed but looking at other workflows that are known to be working (i.e. `reusable_export_pr_details`) and that also upload artifacts, I don't think it's actually needed
- correct workflow reference in workflow (fixes issue I introduced in previous PR after renaming)
- reduce permission scope of Layers workflow
**Issue number:** #1799
--- …
> chore(ci): refactor more workflows to scope permissions

- docs/versioning.md
- mkdocs.yml
Formalize our versioning policy with a dedicated page similar to the AWS SDK, adjusted to Powertools for AWS Lambda (TypeScript) and our community.
**Issue number:** #1995
---
> docs(maintenance): add versioning and maintenance policy

- .github/workflows/on_doc_merge.yml
- .github/workflows/rebuild_latest_docs.yml
This PR adds new permissions to the `rebuild_latest_docs.yml` and `on_doc_merge.yml` to match the permissions requested by the reusable workflow called by both (`reusable_publish_docs.yml`).
The reusable workflow requires `contents: read` to be able to read the repository contents, however the two caller workflows were not specifying any `content` related permission at the job level, implicitly setting it to `none` and thus causing the workflow runs to fail ([example](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/7724705134)).
With this change the workflows should be able to publish docs again.
**Issue number:** #1799
--- …
> chore(ci): fix docs workflow permissions

- .github/scripts/label_missing_acknowledgement_section.js
- .github/workflows/reusable_publish_docs.yml
This PR fixes two more issues with the CI workflows: one related to origin checks, and the other with a broken link.
For some workflows that have access to privileged environments we use `if` statements to check that the workflow is running in the correct repository. The workflow used to publish the docs was doing this check but incorrectly using the Python repo name, this was the result of a wrong copy/paste.
Additionally, the URL for the acknowledgement section in the pull request template was incorrect. This PR updates the URL to the correct location.
**Issue number:** #1799
---
**Disclaimer**: We value your …
> chore(ci): fix repo references

- .github/workflows/make-release.yml
- .github/workflows/make-version.yml
- .github/workflows/publish_layer.yml
- .github/workflows/reusable_update_layer_arn_docs.yml
In this PR we refactor the release workflow to reduce the permission scope and add additional review step for the layer arn docs changes. The changes include
**Issue number:** #1799 
---
> chore(ci): refactor release workflow

- .github/workflows/pr-run-linting-check-and-unit-tests.yml
- README.md
- Add badges to readme
**Issue number:** #2045 
---
> chore(docs): include badges in readme

- packages/idempotency/tests/e2e/idempotentDecorator.test.FunctionCode.ts
- packages/idempotency/tests/e2e/idempotentDecorator.test.ts
- packages/idempotency/tests/e2e/makeHandlerIdempotent.test.FunctionCode.ts
- packages/idempotency/tests/e2e/makeHandlerIdempotent.test.ts
- packages/testing/src/TestInvocationLogs.ts
> [!IMPORTANT]
> This PR reverts #2074
After running more tests it appears that the changes introduced in #2074 were not necessary, so we I am reverting them.
**Issue number:** #2076
---
> chore(tests): revert change timeout reporting in idempotency e2e tests

- docs/overrides/main.html
This PR fixes the broken relative link to the v2 upgrade guide in the docs (see image below for reference). 
Before merging the PR with the banner I tested it locally and verified that the link was working fine, however while working on this PR I verified again and realized that it's not possible to test this type of url locally because when running the docs locally we are missing the `/<version>` path from the url.
In most of the doc links this is not a problem, however for links interpolated in the `overrides` this seems to be an issue.
I couldn't find the proper way of doing it according to MKDocs Material conventions so I opted for hardcoding the `/latest` path; mainly because this is a temporary one-off link.
**Issue number:** #2090
---
By …
> chore(docs): fix broken upgrade guide link in banner

- .github/workflows/make-version.yml
In a previous PR I have changed `github.ref` to `github.sha` because this is more contained for workflow. Because using sha worked in our release workflow and we don't allow lerna to push back to the git repo, I have assumed that `lerna version` will behave similar, because we use `--no-git-tag-version --no-push`, which means there is no need to for git history or any additional information `lerna` to just bump the version. 
It turns out, that this is an open issue since the dawn of time, https://github.com/lerna/lerna/issues/2443 and lerna wants to have git history, even if you pass the flag not to operate on git. 
I have tested the publish with `github.sha` checkout option and it worked, so we can keep the `make-release` workflow as it is.
**Issue number:** closes #2092 
***Is it a …
> chore(ci): fix make-version workflow on detached head

- .github/workflows/publish_layer.yml
- .github/workflows/reusable_deploy_layer_stack.yml
This PR slightly modifies the implementation of the CI workflows that handle the Lambda layer publishing and subsequent documentation updates.
Whenever we publish a new Lambda layer version we need to update the ARNs in the documentation. This is done via a combination of [CFN outputs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CfnOutput.html), [CDK output](https://docs.aws.amazon.com/cdk/v2/guide/cli.html) file, and [GitHub artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts).
Since the layer publishing happens for multiple AWS Regions in parallel, the Layer ARN for each region gets added to a text file that should be uploaded as GitHub artifact. Prior to this PR the artifacts were overwriting each others and ultimately we were …
> fix(ci): create one layer artifact per region & merge

- .github/CODEOWNERS
This PR adds the `@aws-powertools/core` GitHub team to the `CODEOWNERS` file so that if one of the members of that team reviews a PR, the requirement of having at least one approver is fulfilled.
This is not the case today, and this essentially equates to requiring multiple reviews which is not what we want at this stage. 
**Issue number:** closes #2098
---
> chore(maintenance): add core team to code owners

- .github/workflows/publish_layer.yml
This PR adds a new `contents:read` permission the two jobs that call the lambda layer publish reusable workflows.
**Issue number:** #2111
---
> chore(ci): fix release workflow permission

- docs/upgrade.md
This PR adds `ContextExamples` to the upgrade guide. If customers imported it from the `commons` package before, they'd need to create the object in their tests. 
**Issue number:** closes #2195 
---
> chore(docs): add `ContextExamples` to upgrade guide

- docs/core/tracer.md
FIxed small typo in tracer docs: `...your use this utility...` --> `...you use this utility...`
None
---
> chore(docs): fix typo in tracer.md

- packages/jmespath/src/Functions.ts
- packages/jmespath/src/constants.ts
- packages/jmespath/src/errors.ts
- packages/jmespath/src/types.ts
- packages/jmespath/typedoc.json
This PR adds the base components for the JMESPath utility. These includes constants, types, and error definitions.
The types include all the data structures used in the utility, most of which will be exposed to customers.
The error definitions include all the possible error types that can be thrown by the utility either during parsing, tokenization, or data extraction.
Finally, the constants includes the grammar for the JMESPath query language implemented [according to spec](https://jmespath.org/specification.html#grammar):
- Allowed characters/tokens/identifiers
- Supported digits and alphabet
- Binding power hash map - this hash map determines which tokens are processed together with others or as separate operations.
The PR also includes a stub for a module called `Functions` that will …
> feat(jmespath): add base types and errors

- packages/jmespath/typedoc.json
This PR removes `readme` field from the api `typedoc` configuration. This will unblock the docs workflow, so we can publish docs until #2186 is merged.
**Issue number:** closes #2199 
---
> chore(docs): remove missing README from typedoc for jmespath temporarily

- docs/overrides/main.html
- docs/upgrade.md
- docs/versioning.md
This PR updates the documentation to reflect the status of the v1.x and v2.x releases.
Specifically, I have updated the banner at the top of the docs to reflect the fact that v2 is now GA and available.
I have also updated the upgrade guide and the versioning pages to reflect this, as well as the fact that v1 entered maintenance mode and will reach end-of-life on September 1st, 2024.
**Issue number:** #2225
---
> docs(maintenance): update v1 and v2 status

- tsconfig.esm.json
This PR modifies the base `tsconfig.json` file used to transform our source code to ESM builds so that private class fields are downleveled correctly.
As described at length in the linked issue, the combination of the setting `noEmitHelpers: true` with the target being set to `ES2021` (Node.js 16) caused an unexpected behavior that led to runtime errors for those customers who use ESM bundles with the Idempotency utility.
The bug was introduced due to a potentially incorrect assumption that since [the feature is stated to be supported for Node.js 14+](https://v8.dev/features/class-fields#support), we wouldn't need to emit specific helpers to polyfill it. Based on this, I assumed that setting `noEmitHelpers` to `true` would be fine since our target version in the same config is Node.js 16. …
> fix(idempotency): transform private class fields

- layers/src/layer-publisher-stack.ts
This PR introduces a new step in the layer publisher workflow that should fix a bug affecting customers using the Powertools Lambda Layers with functions bundled using ESM format.
As described in the linked issue, when the above conditions are met, the function throws a runtime error with the stack trace pointing at the `/opt/nodejs/node_modules`, which is where the code for our utilities is stored when using Layers.
The fix mirrors [the recommendation](https://docs.powertools.aws.dev/lambda/typescript/latest/upgrade/#unable-to-use-esm) that we give to customers having to support the `require` keyword and adds a polyfill at the top of the file causing the issue.
The step adds this banner dynamically when the Lambda layers are built and it does so only on the ESM build and on one specific …
> fix(layers): add `createRequire` banner in esm

- packages/jmespath/src/ast.ts
This PR introduces the definition of the components that make up the Abstract Syntax Tree (AST) for the JMESPath utility.
As discussed in the linked utility the AST is a hierarchical representation of the syntactic structure of a JMESPath expression and abstracts away from the specifics of the input text, capturing the components and relationships between them.
Each node in the AST follows a similar structure and is composed by three fields:
- `type` a string literal holding the name of the node (i.e. `comparator`, `field`, `filter_projection`, etc.)
- `children` an array containing the child nodes of this node (if any) - this helps establish the hierarchy
- `value` the value of the node (i.e. any JSON serializable value)
**Issue number:** #2210
---
By …
> feat(jmespath): add abstract syntax tree definition

- packages/jmespath/src/Lexer.ts
This PR includes the implementation of the `Lexer` component, part of the JMESPath utility.
As discussed in the linked issue, the purpose of a lexer is to break down the input JMESPath expression into smaller meaningful units (tokens). These tokens represent the building blocks of the JMESPath language and are defined in the language grammar (#2192).
The `Lexer`'s main method (`public *tokenize()` is implemented as a generator. This pattern allows the lexer to _walk_ the expression iteratively and yield (aka return) tokens as it goes. While not a direct equivalent, the closest patten to describe this implementation would be a recursive function that maintains an external state (aka a reducer).
At each step, the lexer interprets a certain character and based on its type it performs certain …
> feat(jmespath): add lexer component

- packages/jmespath/src/Functions.ts
This PR adds a new `Functions` class to the JMESPath utility. This class holds the implementation for all the built-in functions listed in the [JMESPath specification](https://jmespath.org/specification.html#built-in-functions) as well as a class method decorator to validate function arguments.
Customers are not expected to use this class directly, instead the logic in it will allow them to use function expressions in their JMESPath expressions, for example:
```ts
const payload = {
grades: [1, 5, 2, 10],
};
const maxGrade = search('max(grades)', payload); // 10
const minGrade = search('min(grades)', payload); // 1
const avgGrade = search('avg(grades)', payload); // 4.5
const roundedUpAvgGrade = search('ceil(avg(grades))', payload); // 5
const roundedDownAvgGrade = …
```
> feat(jmespath): add built in functions

- packages/logger/src/Logger.ts
Updated the logging for warning message that indicates a mismatch with the Advanced Logging Controls minimum log level. Now, a template literal is used instead of the format function from the `node:util` package. This change addresses the sole instance where the `node:util` package was used, which prevented the use with [LLRT](https://github.com/awslabs/llrt).
**Issue number:** #2050
---
> refactor(logger): use template literal instead of node:util format

- packages/idempotency/package.json
- packages/parameters/package.json
This PR modifies some of the type exports for the Parameters and Idempotency packages which, as reported in the linked issue, were incorrect.
The misconfiguration was not causing any runtime issue because it affected only exports that are ever used only during development (types are not used at runtime and in most cases are removed from the code altogether).
The PR aligns the type exports in the two packages to the ones found in all the other packages.
**Issue number:** #2284
---
> chore(maintenance): adjust type exports in parameters & idempotency

- docs/core/metrics.md
- docs/index.md
- docs/utilities/idempotency.md
This PR changes the wording for the middyjs support version to `up to v4.x` and defaults to v4.x.
**Issue number:** closes #2300 
---
> chore(docs): fix middy v4 version support

- packages/idempotency/src/persistence/BasePersistenceLayer.ts
- packages/idempotency/tests/e2e/makeIdempotent.test.FunctionCode.ts
- packages/idempotency/tests/unit/makeIdempotent.test.ts
- packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
This PR fixes a bug in the Idempotency utility that caused retries performed while the utility's in-memory cache was enabled to be rejected as "already in-progress" rather than returning the value from the previous execution.
Due to this bug happening exclusively on repeated (aka subsequent) idempotent requests it's highly unlikely that customers might have experienced data loss but instead they would have observed an artificially high number of [`IdempotencyAlreadyInProgressError`](https://docs.powertools.aws.dev/lambda/typescript/latest/api/classes/_aws_lambda_powertools_idempotency.index.IdempotencyAlreadyInProgressError.html) errors as if the previous execution was not yet complete, which is still not great.
The PR addresses the bug by returning the value from cache whenever one is …
> fix(idempotency): return correct value from in-memory cache

- docs/maintainers.md
This PR adds a new section to the maintainer's handbook to document the process of adding a new AWS Region to the Lambda Layers we publish.
Once rendered, the section looks like this:
**Issue number:** #1981
---
> chore(maintenance): document process to add a new region to layers

- packages/parser/src/envelopes/apigw.ts
- packages/parser/src/envelopes/apigwv2.ts
- packages/parser/src/envelopes/cloudwatch.ts
- packages/parser/src/envelopes/dynamodb.ts
- packages/parser/src/envelopes/envelope.ts
- packages/parser/src/envelopes/event-bridge.ts
- packages/parser/src/envelopes/kafka.ts
- packages/parser/src/envelopes/kinesis-firehose.ts
- packages/parser/src/envelopes/kinesis.ts
- packages/parser/src/envelopes/lambda.ts
- packages/parser/src/envelopes/sns.ts
- packages/parser/src/envelopes/sqs.ts
- packages/parser/src/envelopes/vpc-lattice.ts
- packages/parser/src/envelopes/vpc-latticev2.ts
- packages/parser/src/errors.ts
- packages/parser/src/index.ts
- packages/parser/src/parser.ts
- packages/parser/tests/unit/envelope.test.ts
- packages/parser/tests/unit/envelopes/apigwt.test.ts
- packages/parser/tests/unit/envelopes/cloudwatch.test.ts
- packages/parser/tests/unit/envelopes/dynamodb.test.ts
- packages/parser/tests/unit/envelopes/eventbridge.test.ts
- packages/parser/tests/unit/envelopes/kinesis.test.ts
- packages/parser/tests/unit/envelopes/sns.test.ts
- packages/parser/tests/unit/envelopes/sqs.test.ts
- packages/parser/tests/unit/parser.decorator.test.ts
This PR adds `ParseError` as a wrapper around `ZodError`. The goal ist to have a boundary that we control in this utility and can change the behaviour in the future without introducing breaking changes. We preserve the `ZodError` for any recovery, troubleshooting or additional logging, so customers can fall back. 
**Issue number:** closes #2317 
---
> feat(parser): add parse error and remove all traces of ZodError

- packages/parser/src/schemas/sqs.ts
- packages/parser/tests/events/sqsEvent.json
This PR adds `DeadLetterQueueSourceArn` field to SQS message attributes. 
**Issue number:** closes #2361 
---
> chore(parser): add DeadLetterQueueSourceArn attribute

- packages/jmespath/src/Functions.ts
- packages/jmespath/tests/unit/index.test.ts
This PR fixes a bug that caused JMESPath custom functions to fail to be detected and throw a runtime error when running on minified functions.
The previous logic relied on the name of the class (via `prototype.constructor.name`) which caused it to fail when the code is minified since entities are aliased to use shorter names.
The new logic introduced in this PR uses an identity check (`value instanceof Class`) which minification-proof since even when aliased both classes will still maintain their inheritance.
**Issue number:** #2383
--- …
> fix(jmespath): refactor custom function introspection to work with minification

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation_improvements.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/boring-cyborg.yml
- .github/release-drafter.yml
- .github/scripts/constants.js
- .github/scripts/label_pr_based_on_title.js
- .github/scripts/label_related_issue.js
- .github/workflows/stale-issues.yml
- docs/maintainers.md
This PR updates the labels in the scripts and configuration, as well as in the maintainers playbook to align with the new conventions.
**Issue number:** #2418
---
> chore(maintenance): update labels in automation

- packages/parser/src/schemas/s3.ts
- packages/parser/tests/events/s3EventBridgeNotificationObjectDeletedEvent.json
In this PR we set etag to optional. We initially discussed in #2410 that it'd be best to split s3 event notification schema into separate objects for event types (delete, create, update, lifecycle, etc) similar to how `@types/aws-lambda` does it.
However `@types/aws-lambda` is not correct for the s3 notification, i.e. etag is a required field in `DeleteObject` events, thus we can't rely on them. In addition, splitting the event types would introduce either redundancy between the events of the common fields, or additional complexity if we decide to split them based on base and specific fields. It'd be hard to read them.
**Issue number:** closes #2410 
--- …
> fix(parser): set etag optional for delete object notifications

- packages/parser/src/schemas/apigwv2.ts
- packages/parser/tests/unit/schema/lambda.test.ts
This PR closes #2427 . I have used `optional` in most of the places where we don't expect to have a value, but this did not cover the `null` value case. 
**Issue number:** closes #2427
---
> fix(parser): lambda function url cognitoIdentity and principalOrgId nullable

- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- .markdownlint.yaml
- .markdownlintignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- SECURITY.md
- docs/.markdownlint.yaml
- docs/contributing/conventions.md
- docs/contributing/getting_started.md
- docs/contributing/setup.md
- docs/contributing/testing.md
- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- docs/index.md
- docs/maintainers.md
- docs/roadmap.md
- docs/upgrade.md
- docs/utilities/batch.md
- docs/utilities/idempotency.md
- docs/utilities/jmespath.md
- docs/utilities/parameters.md
- docs/utilities/parser.md
- docs/we_made_this.md
- layers/README.md
- package-lock.json
- package.json
This PR introduces markdown linting to the project. This will enforce an objective baseline for style and format of markdown files.
To support this I have added [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) to the workspace, this is the same CLI used by Powertools for AWS Lambda (Python) from which I also copied the rule set.
Linting is run automatically as `pre-commit` hook via `lint-staged`, which will lint and fix only on staged files that are about to be committed (remember to run `npx husky` to make it take effect), and also as PR check. The latter runs on all markdown files in scope.
The tool supports an ignore file, which I also added to the project, however I was able to make this file work only with the IDE extension but not the CLI, for this reason I …
> chore(maintenance): add markdownlint

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation_improvements.yml
- .github/ISSUE_TEMPLATE/maintenance.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR introduces changes to the PR and Issue templates used to render them.
As discussed in the linked issue, the goal is to make the PR template less verbose and cumbersome while still maintaining all the sections & callouts we need.
The changes introduced are in line with the ones discussed in the issue.
**Issue number:** closes #2411
---
> chore(maintenance): revamp PR & issue templates

- packages/parser/src/schemas/apigw.ts
- packages/parser/tests/events/apiGatewayAuthorizerRequestEvent.json
- packages/parser/tests/unit/envelopes/apigwt.test.ts
The APIGatewayProxyEventSchema has incorrect types for these request keys: `body`, `queryStringParameters`, and `multiValueQueryStringParameters`.
The above fields are incorrectly validating against `z.optional()` (undefined) when they are not present in the request, but API Gateway actually sends these values as `null` in this case.
This PR addresses the issue by changing the Zod schemas to use `z.nullable()` instead. Unit tests are updated to reflect the change.
**Issue number:** #2461 
---
> fix(parser): set APIGatewayProxyEventSchema body and query string keys to be nullable

- .github/scripts/update_layer_arn.sh
In this PR we remove the `cdk` prefix from the pseudo region check when replacing the layer version in the docs. This will fix the reported issue in #2484 .
**Issue number:**  closes #2486 
---
> chore(docs): fix update layer arn for cdk

- packages/tracer/src/Tracer.ts
- packages/tracer/src/provider/ProviderService.ts
As described in the issue, AWS SDK for JavaScript v2 will reach end-of-support in September 8, 2025. In response to this announcement, adding deprecated tags for the Tracer methods used to instrument clients for this version.
Add @deprecated notice on the `captureAWS` & `captureAWSClient` methods.
**Issue number:** #2397 
---
> chore(tracer): mark captureAWS & captureAWSClient functions as deprecated

- layers/package.json
- package.json
- packages/batch/package.json
- packages/commons/package.json
- packages/idempotency/package.json
- packages/jmespath/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/parameters/package.json
- packages/parser/package.json
- packages/testing/package.json
- packages/tracer/package.json
In this PR the suggested aggregation of the lint-staged configuration into the top package.json is implemented. Closes #2312
**Issue number:** #2312
---
> chore(ci): Aggregate lint-staged in top package.json

- packages/tracer/src/provider/ProviderService.ts
This PR makes a minor change in the Tracer X-Ray SDK provider to avoid using the `require` keyword in our codebase. This will help customers identify where the issue is coming from thanks to a more accurate stack trace that reflects the root cause of the issue.
As discussed in the linked issue, the previous implementation hardcoded the `require` keyword in both CJS and ESM builds, which caused a runtime error in ESM customer bundles. This was done under the misguided assumption that the X-Ray SDK monkey patching would not work when importing the `http` and `https` modules with the `import` keyword (my bad).
With this PR we import the modules with the `import` keyword in our source, and then let the TypeScript build operation decide …
> improv(tracer): remove require in tracer provider

- packages/idempotency/src/persistence/BasePersistenceLayer.ts
- packages/idempotency/tests/e2e/makeIdempotent.test.ts
- packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
For consistency, we need to align timestamp formats for `expiration` and `in_progress_expiration` in idempotency table. To achieve this we have to round off `expiration` attribute.
- Round off the return value of `getExpiryTimestamp` function
- Fix failing tests because of the rounding off
**Issue number:**  #2298
---
> chore(idempotency): expiration timestamp rounded to the nearest second 

- package-lock.json
- packages/tracer/package.json
- packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.manual.test.functionCode.ts
- packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
- packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
- packages/tracer/tests/helpers/httpRequest.ts
This PR removes `axios` from the `devDependencies` and replaces its usage with a custom helper function, used only in integration tests, that is based on the `https` built-in module directly.
With this change the tests remain functionally unchanged and the only difference is that we have one less dependency to manage.
**Issue number:** #2558
---
> test(tracer): remove `axios` and use `https` directly

- package-lock.json
- package.json
This PR temporarily pins the `lerna` development dependency to version 8.1.2 due to a known regression in version 8.1.3 and later (lerna/lerna#4026), which caused our release pipeline to fail.
Due to that version depending on a vulnerable dependency, the PR also applies a temporary override on the `tar`  transitive dependency.
**Issue number:** #2645
---
> chore(deps-dev): pin lerna to 8.1.2

- .github/dependabot.yml
This PR updates the Dependabot configuration to group together the `typedoc` module and its plugins so that the bot opens PRs for all the packages together.
This is beneficial since the plugins usually support a specific version or range of `typedoc`, which means upgrading one without the others is not desirable.
Typedoc updates usually come out together with new TypeScript "major" releases, so I could've added TS to the group as well, however I opted not to so that we have a discrete PR for TypeScript, given the large blast radius of a botched upgrade.
While touching the file, I also made two minor changes to other groups:
- Renamed the `aws-sdk` group to `aws-sdk-v3` so to not confuse it with PRs opened for the `aws-sdk` (v2) dependency …
> chore(ci): update Dependabot groups for typedoc

- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/errors.ts
- packages/idempotency/src/index.ts
- packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
- packages/idempotency/tests/unit/makeIdempotent.test.ts
This PR makes changes to the custom errors that can be thrown by the Idempotency utility so that their respective [`name` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name) is set to the actual name of the error, for example:
```diff
class IdempotencyUnknownError extends Error {
public constructor(message?: string, options?: ErrorOptions) {
super(message, options);
+   this.name = 'IdempotencyUnknownError';
}
}
```
This change allows to handle errors without having to import the error class itself, and without having to rely on a [referential identity](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) check (i.e. `error instanceof …
> fix(idempotency): check error identity via names

- docs/core/logger.md
- docs/core/metrics.md
- docs/core/tracer.md
- docs/index.md
- docs/utilities/idempotency.md
- package-lock.json
- package.json
- packages/idempotency/package.json
- packages/logger/package.json
- packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
- packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.FunctionCode.ts
- packages/metrics/package.json
- packages/parameters/package.json
- packages/parser/package.json
- packages/tracer/package.json
- packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
This PR adds support for Middy.js 5.x by including it in some of the integration test cases that are run on the utilities and widening the version range in the peer dependencies from `>= 4.x` to `4.x || 5.x`.
Because we want to continue supporting both versions, I decided to use an npm feature that allows you to install a package under a custom alias. This mechanism allows multiple versions of the same-name package side-by-side, which is what we need in this case.
To modify the `devDependencies` of the project I run these commands:
```sh
npm un @middy/core # remove existing version
npm i -D middy4@npm:@middy/core@4.x
npm i -D middy5@npm:@middy/core@5.x
```
This created two entries in the main `package.json` file, and allows us to import …
> feat(internal): support Middy.js 5.x

- packages/parser/src/errors.ts
- packages/parser/tests/unit/envelope.test.ts
The ParseError links the passed error cause with the thrown error. 
**Issue number:** fixes #2773
---
> fix(parser): links the error cause with ParseError

- packages/logger/src/constants.ts
- packages/logger/src/index.ts
- packages/logger/src/types/Log.ts
- packages/logger/tests/unit/Logger.test.ts
This PR converts the existing LogLevel type definition to a more concise and maintainable enum-like structure using a const object. It also simplifies the LogLevel type to utilize this new structure.
Introduced a new LogLevel const object in `packages/logger/src/constants.ts`:
```typescript
const LogLevel = {
DEBUG: 'DEBUG',
INFO: 'INFO',
WARN: 'WARN',
ERROR: 'ERROR',
SILENT: 'SILENT',
CRITICAL: 'CRITICAL',
} as const;
```
Imported the constants in `packages/logger/src/types/Log.ts` and replace the existing types 
```diff
+import { LogLevel } from '../constants.js';
- type LogLevelDebug = 'DEBUG';
- type LogLevelInfo = 'INFO';
- type LogLevelWarn = 'WARN';
- type LogLevelError = 'ERROR';
- type LogLevelSilent = 'SILENT';
- type LogLevelCritical = 'CRITICAL';
type LogLevel =
-   | …
```
> feat(logger): introduce loglevel constant

- packages/parser/src/envelopes/cloudwatch.ts
- packages/parser/src/envelopes/dynamodb.ts
- packages/parser/src/envelopes/kafka.ts
- packages/parser/src/envelopes/kinesis-firehose.ts
- packages/parser/src/envelopes/kinesis.ts
- packages/parser/src/envelopes/sns.ts
- packages/parser/src/envelopes/sqs.ts
- packages/parser/src/middleware/parser.ts
- packages/parser/src/parserDecorator.ts
- packages/parser/src/types/envelope.ts
- packages/parser/src/types/parser.ts
- packages/parser/tests/unit/parser.decorator.test.ts
- packages/parser/tests/unit/parser.middy.test.ts
This PR introduces type inference for event type of handler when using parser with middy middleware. Based on the combination of provided inputs (schema, envelope, safeParse) the type can change between a single object, an array (i.e. `SqsEnvelope`) and safeParse, where we wrap the result into `ParsedResult`. I have modified the unit tests to use the inference which should have an error, if the type inference breaks.
* fixed return types to array for envelopes that return multiple items of provided schema objects
* added `ParseOutput` to narrow down the type of the modified event
* moved `DynamoDBStreamEnvelopeResponse` to types folder
* replaced eslit comments with type casts in unit tests as mentioned in our docs
> Please add the issue …
> feat(parser): allow parser set event type of handler with middy

- biome.json
- examples/app/cdk/example-stack.ts
- examples/app/functions/commons/helpers/get-item.ts
- examples/app/functions/commons/helpers/put-item.ts
- examples/app/functions/commons/helpers/scan-items.ts
- examples/app/package.json
- package-lock.json
- package.json
This PR introduces `@biomejs/biome` as development dependency to the project as well as a new `biome.json` file that holds the configuration for the tool.
The configuration used for Biome is roughly equivalent with the `eslint`/`prettier` one that we are already using, except a couple notable differences:
- No support for function return type - as of today we have a Eslint rule that reminds us to set the return type of each function. This rule is not yet supported in Biome (see linked issue). The rule seems to be in demand, so there's a chance it will be implemented at some point, in the meanwhile we'll rely on TypeScript and code reviews.
- Standardized import order
- Force `type` usage when importing a type
There might be other subtle …
> chore(maintenance): add biome to the project

- packages/logger/package.json
- packages/logger/src/Logger.ts
- packages/logger/src/config/EnvironmentVariablesService.ts
- packages/logger/src/formatter/LogFormatter.ts
- packages/logger/src/middleware/middy.ts
- packages/logger/src/types/Log.ts
- packages/logger/src/types/Logger.ts
- packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
- packages/logger/tests/e2e/basicFeatures.middy.test.ts
- packages/logger/tests/e2e/childLogger.manual.test.FunctionCode.ts
- packages/logger/tests/e2e/childLogger.manual.test.ts
- packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.FunctionCode.ts
- packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.ts
- packages/logger/tests/e2e/sampleRate.decorator.test.FunctionCode.ts
- packages/logger/tests/e2e/sampleRate.decorator.test.ts
- packages/logger/tests/helpers/resources.ts
- packages/logger/tests/unit/Logger.test.ts
- packages/logger/tests/unit/formatter/PowertoolsLogFormatter.test.ts
- packages/logger/tests/unit/middleware/middy.test.ts
- packages/logger/tsconfig.esm.json
- packages/logger/tsconfig.json
Adds biome to the logger package. Closes #2798 
**Issue number: 2798** 
---
> chore(maintenance): migrate logger utility to biome

- packages/logger/src/types/index.ts
> exports the LoggerInterface
Allows to extend the logger functionality by using the [decorator design pattern](https://en.wikipedia.org/wiki/Decorator_pattern).
**Issue number:** #2828
> improv(logger): export LoggerInterface

- .github/scripts/release_patch_package_json.js
- .markdownlintignore
- packages/parser/README.md
This PR removes the `-beta` suffix from the Parser utility and the notice from its `README` file, to signify to customers that the utility can now be used in production workloads.
With the addition of Biome in previous PRs, I also had to address a couple of changes in the script I modified to ungate the GA - hence the diff on that file.
**Issue number:** #2830
---
> chore(parser): mark parser as GA

- packages/parser/src/envelopes/apigw.ts
This PR fixes the import statement in one of the built-in envelopes of the Parser utility. The import was misconfigured in #2822.
**Issue number:** closes #2837
---
> chore(parser): review imports

- packages/parser/package.json
- packages/parser/src/schemas/index.ts
- packages/parser/src/schemas/kafka.ts
- packages/parser/src/schemas/kinesis-firehose.ts
- packages/parser/src/schemas/ses.ts
- packages/parser/src/schemas/sns.ts
- packages/parser/src/schemas/sqs.ts
- packages/parser/src/types/schema.ts
- packages/parser/tests/unit/schema/kafka.test.ts
- packages/parser/tests/unit/schema/kinesis.test.ts
- packages/parser/tests/unit/schema/ses.test.ts
- packages/parser/tests/unit/schema/sns.test.ts
- packages/parser/tests/unit/schema/sqs.test.ts
Adds the export for the schema and the corresponding types of the `Record` schemas.
**Issue number: closes #2811** 
---
> chore(parser): adds exports for Record schemas

- .github/workflows/reusable_deploy_layer_stack.yml
- docs/index.md
This PR adds the necessary config to the CI workflows to deploy our public Lambda layers to two new commercial regions: `ap-south-2` and `me-central-1`.
**Issue number:** closes #2674
---
> chore(layers): deploy Lambda layers in `ap-south-2` and `me-central-1`

- packages/idempotency/README.md
- packages/metrics/README.md
- packages/metrics/src/Metrics.ts
- packages/metrics/src/config/EnvironmentVariablesService.ts
- packages/metrics/src/middleware/middy.ts
- packages/metrics/typedoc.json
This PR overhauls the JSDoc comments on each type, function, class, and method of the metrics utility so that it provides better and relevant info to customers using the API docs or wanting to get contextual info within their IDE.
**Issue number:** closes #2375
---
> docs(metrics): review API docs & README

- examples/app/functions/commons/helpers/scan-items.ts
- packages/batch/src/BasePartialBatchProcessor.ts
- packages/batch/src/BasePartialProcessor.ts
- packages/commons/src/LRUCache.ts
- packages/commons/src/config/EnvironmentVariablesService.ts
- packages/commons/src/middleware/cleanupMiddlewares.ts
- packages/commons/src/types/ConfigServiceInterface.ts
- packages/commons/src/types/middy.ts
- packages/commons/typedoc.json
- packages/idempotency/src/config/EnvironmentVariablesService.ts
- packages/idempotency/src/types/DynamoDBPersistence.ts
- packages/idempotency/src/types/IdempotencyOptions.ts
- packages/jmespath/src/PowertoolsFunctions.ts
- packages/logger/src/types/Logger.ts
- packages/logger/src/types/index.ts
- packages/logger/typedoc.json
- packages/parameters/src/base/transformValue.ts
- packages/parser/src/middleware/parser.ts
- packages/parser/src/types/index.ts
- packages/tracer/src/provider/ProviderService.ts
- typedoc.json
This PR removes not supported api docs annotations and reverts exports that were previously added. Instead we now use `missing-exports` plugin to collect all implicit exports in api docs.
Current api docs build looks clean:
```
> aws-lambda-powertools-typescript@0.0.1 docs-generateApiDoc
> typedoc .
[info] Loaded plugin typedoc-plugin-zod
[info] Loaded plugin typedoc-plugin-missing-exports
[info] Converting project at ./packages/commons
[info] Converting project at ./packages/jmespath
[info] Converting project at ./packages/logger
[info] Converting project at ./packages/metrics
[info] Converting project at ./packages/tracer
[info] Converting project at ./packages/parameters
[info] Converting project at ./packages/idempotency
[info] …
```
> docs: removed unnecessary exports previously added to api docs

- packages/tracer/src/provider/ProviderService.ts
- packages/tracer/src/provider/utilities.ts
- packages/tracer/tests/e2e/middy.test.ts
- packages/tracer/tests/helpers/mockRequests.ts
- packages/tracer/tests/unit/ProviderService.test.ts
This PR modifies the internal implementation of the Tracer patching for the `fetch` request module so that it includes the pathname of a request in the segment data.
As reported in the linked issue, the current implementation only records the host name, so a request to `https://aws.amazon.com/free` would generate a segment similar to this:
```json
{
"id": "45b22f447784c44f",
"name": "aws.amazon.com",
"start_time": 1724108234.18,
"namespace": "remote",
"http": {
"request": {
"url": "aws.amazon.com",
"method": "GET"
},
"response": {
"status": 301,
"content_length": 0
}
},
"end_time": 1724108234.849
}
```
while it should have generated one like this:
```json
{
"id": "e861c05fa31a14ab",
"name": "aws.amazon.com",
"start_time": 1724108234.856, …
```
> fix(tracer): include request pathname in trace data

- packages/parameters/src/errors.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/ssm/setParameter.ts
This PR is a follow up to #3020 and brings a small DX improvement by including the cause of the error we throw when setting a parameter fails.
Before this PR, when the put parameter operation failed, we threw an opaque `SetParameterError`. Now, we include the original error from the AWS SDK as cause for an easier troubleshooting.
With this PR, the error would instead be:
```json
{
"error":{
"name":"SetParameterError",
"location":"file:///var/task/index.mjs:1317",
"message":"Unable to set parameter with name /my-service/parameter",
"stack":"SetParameterError: Unable to set parameter with name /my-service/parameter\n    at _SSMProvider.set (file:///var/task/index.mjs:1317:13)\n    at process.processTicksAndRejections …
```
> improv(parameters): include cause in set parameter error

- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
- packages/metrics/tests/unit/middleware/middy.test.ts
- packages/metrics/tests/unit/repro.test.ts
This PR improves the Metrics utility by avoiding to log an empty metric when the buffer is flushed and no metric is present.
Before this PR the utility would log an EMF log with no metrics when attempting to flush the buffer and no metrics were set. The PR aligns the behavior with the Python version of Powertools for AWS.
**Issue number:** closes #3023
---
> improv(metrics): avoid emitting empty EMF metric

- packages/tracer/src/Tracer.ts
- packages/tracer/src/index.ts
- packages/tracer/tests/unit/Tracer.test.ts
This PR updates the Tracer utility to set the `AWS_XRAY_CONTEXT_MISSING` environment variable to `IGNORE_ERROR` by default.
This change has been made in response to customers adopting features that rely on top-level await and finding the error logs produced by X-Ray SDK not useful.
The X-Ray SDK for Node.js was not designed with this feature in mind, and by default it logs an error when a code path attempts to send trace data outside of the context of a request.
This is because without the request context, there's no X-Ray Trace ID, and so the SDK is unable to establish the lineage of a segment/span.
In many cases this is a desired behavior (although I'd have preferred it was a warning rather than an error log), however now that making …
> improv(tracer): set `AWS_XRAY_CONTEXT_MISSING` to `IGNORE_ERROR` when no value is set

- package-lock.json
Dependabot is flagging this dependency as vulnerable and needing of update, however it's unable to open a PR automatically for whatever reason.
Instead of wasting time troubleshooting the tool, I just ran `npm audit fix` locally and pushed to this branch - fixing the issue.
**Issue number:** closes #3069
---
> chore(deps-dev): bump path-to-regexp to 6.3.0

- layers/src/canary-stack.ts
- layers/src/layer-publisher-stack.ts
- layers/tests/e2e/layerPublisher.class.test.functionCode.ts
- layers/tests/e2e/layerPublisher.test.ts
Small PR to add the new parser feature to the published lambda layers.
Adds the feature to the layer stacks in the layer package.
**Issue number:** #3100
---
> chore(layers): add Parser to layer

- package-lock.json
- packages/testing/package.json
This PR manually updates the `@aws-cdk/cli-lib-alpha` dependency since it's being excluded by Dependabot updates.
We think this is because the dependency has a pre release suffix in the version number (i.e. `2.160.0-alpha.0`) but we are still investigating and are unsure.
For the meantime, since this is blocking our e2e tests, I am updating this manually.
**Issue number:** closes #3117
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues …
> chore(deps): bump @aws-cdk/cli-lib-alpha to 2.160.0-alpha.0

- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- .husky/pre-push
- packages/logger/package.json
- packages/logger/src/Logger.ts
- packages/logger/tests/tsconfig.json
- packages/logger/tests/unit/configFromEnv.test.ts
- packages/logger/tests/unit/formatters.test.ts
- packages/logger/tests/unit/initializeLogger.test.ts
- packages/logger/tests/unit/injectLambdaContext.test.ts
- packages/logger/tests/unit/logEvent.test.ts
- packages/logger/tests/unit/logLevels.test.ts
- packages/logger/tests/unit/sampling.test.ts
- packages/logger/tests/unit/workingWithkeys.test.ts
- packages/logger/vitest.config.ts
- packages/testing/src/setupEnv.ts
- vitest.config.ts
This PR migrates the unit tests for the Logger utility to use Vitest rather than Jest.
With this change, we can also finally start investing time/effort in custom matchers that can further reduce the boilerplate we write in our tests.
The first example of this are two new custom matchers introduced in this PR:
```ts
process.env.POWERTOOLS_DEV = 'true';
vi.spyOn(console, 'info').mockReturnValue();
// Matches any of the logs emitted
expect(console.info).toHaveLogged(
expect.objectContaining({
message: 'Hello, world!',
})
);
// Matches the log emitted at the specified nth call
expect(console.info).toHaveLoggedNth(
1,
expect.objectContaining({
message: 'Hello, world!',
})
);
```
These two matchers will be available across all the test suites …
> test(logger): migrate to vitest & custom matchers

- packages/logger/src/Logger.ts
- packages/logger/src/types/Logger.ts
- packages/logger/src/types/index.ts
The PR removes the local `LogLevelThreshold` object from `Logger` class and replaces it with `LogLevelThreshold` constant.
- Removed the `LogLevelThreshold` object from the Logger class and replaced it with the `LogLevelThreshold` constant.
- Removed the `LogLevelThresholds` type and its exports.
- Performed housekeeping, the `private logLevel` property of the `Logger` class now uses the value from `LogLevelThreshold` instead of hardcoding the value.
**Issue number:** #2525 
---
> refactor(logger): use `LogLevelThreshold` constant inside `Logger` class 

- package-lock.json
- packages/testing/package.json
This PR manually bumps the `aws-cdk` development dependency used in the `layers` package to deploy the layers during a release.
**Issue number:** closes #3168
---
> chore(deps-dev): bump aws-cdk from 1.155.0 to 1.161.0 in layers

- layers/tests/e2e/layerPublisher.class.test.functionCode.ts
- layers/tests/e2e/layerPublisher.test.ts
This PR removes the schema parsing portion of the test from the canary test of the Lambda layer. As discussed more in depth in the linked issue, with this parsing the canary test expects a payload that is not being sent thus making the canary fail.
While this PR only removes the parsing, we plan on reintroducing a different test in a future PR. For now we are focused on publishing the Lambda layers for the 2.9.0 version that is already on npm.
**Issue number:** fixes #3170
---
**Disclaimer**: We …
> chore(layers): remove schema parsing from layer canary

- packages/logger/src/Logger.ts
fix typo for env variable POWERTOOLS_LOGGER_LOG_EVENT in logger.logEventIfEnabled
Fixed env details on typedoc for `logger.logEventIfEnabled` from `POWERTOOLS_LOG_EVENT` to `POWERTOOLS_LOGGER_LOG_EVENT` per discussion in #3196
**Issue number: #3196**
---
> docs: fix env variable name in `logEventIfEnabled()` docstring

- packages/logger/src/types/Logger.ts
Adding missing function definition `resetKeys()` to the `LoggerInterface` function
**Issue number:** https://github.com/aws-powertools/powertools-lambda-typescript/issues/3212
---
> feat: add resetKeys to LoggerInterface type

- examples/snippets/package.json
- package-lock.json
- packages/parser/package.json
This PR bumps parser to 2.10.0 version for the release, because lerna ignored it.
---
> chore(parser): bump parser to 2.10.0

- .github/workflows/publish-package.yml
This PR adds a workflow to publish a single package to NPM.
**Issue number:**  closes #3231 
---
> chore(ci): add workflow to publish a single package

- .github/workflows/publish-package.yml
Add input type to the publish package workflow
**Issue number:** closes #3231 
---
> chore(ci): add input type to the publish package workflow

- .github/workflows/make-version.yml
This PR adds `--force-publish` flag to `make-version` workflow. This ensures that all packages are bumped during the version to ensure consistency during release.
**Issue number:** closes #3229 
---
> chore(maintenance): add force-publish to bump all packages

- .husky/pre-push
This PR updates the `pre-commit` hook to include a filter for tests run via vitest. With the new filter only unit tests are run, thus excluding e2e tests.
**Issue number:** closes #3239
---
> chore(maintenance): exclude e2e tests from pre-push hook

- packages/parser/src/envelopes/apigw.ts
- packages/parser/src/envelopes/envelope.ts
This PR fixes a regression introduced in #3250 that updated two relative imports and removed the file extension. 
This caused errors to come up during the build of the project ([example here](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/11669742574) - scroll down to the annotations section) due to TypeScript not finding the proper import when building the ESM version of the package..
**Issue number:** fixes #3286
---
**Disclaimer**: We value your time and …
> chore: fix relative import regression

- .husky/pre-push
- packages/parser/src/schemas/kafka.ts
- packages/parser/tests/events/kafkaEventSelfManaged.json
This PR fixes the bug for event type literal for self managed kafka events.
Beside the literal change I had to remove `--changed` flag, as it prevented me from push due to wrong coverage. When running the pre-push tests the coverage for unrelated files which were not affected by the changes were reporting low coverage. In my case it was SQS envelope, which has nothing to do with the kafka schema changes. 
```
✓ |@aws-lambda-powertools/parser| tests/unit/parser.decorator.test.ts (8)
✓ |@aws-lambda-powertools/parser| tests/unit/parser.middy.test.ts (13)
✓ |@aws-lambda-powertools/parser| tests/unit/envelopes/apigw.test.ts (7)
✓ |@aws-lambda-powertools/parser| tests/unit/envelopes/apigwv2.test.ts (7)
✓ |@aws-lambda-powertools/parser| tests/unit/envelopes/cloudwatch.test.ts (5)
✓ …
```
> fix(parser): event type literal for selfManagedKafka

- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
When adding a dimension to my metrics, I should get a warning if the dimension value is invalid aka an empty string ("") or undefined/null, and the dimension should not be added to the EMF blobs emitted by the utility.
- Check for `empty`, `undefined` & `null` values for dimension and if found log warning
- Skip invalid value dimensions to EMF, do this for `addDimension` & `addDimensions`
- Unit test the fix
**Issue number:** #3302 
---
> fix(metrics): skip empty string dimension values

- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/Metrics.test.ts
When working with dimensions with Metrics, the default behavior is to overwrite existing dimensions when a new one with the same name/key is added. Customers have asked us to add a warning when this happens so that they can more easily troubleshoot issues rather than missing data.
```ts
import { Metrics } from '@aws-lambda-powertools/metrics';
const metrics = new Metrics({ singleMetric: true });
metrics.addDimension('test', 'foo');
metrics.addDimension('test', 'bar'); // "bar" silently replaces "foo" as value
```
```ts
import { Metrics } from '@aws-lambda-powertools/metrics';
const metrics = new Metrics({ singleMetric: true });
metrics.addDimension('test', 'foo');
metrics.addDimension('test', 'bar'); // "bar" replaces "foo"
// warning: …
```
> feat(metrics): warn when overwriting dimension

- README.md
Fixing wrong link to parser documentation in the README file.
closes #3402
---
> docs: fix link to parser sub page in the README

- docs/we_made_this.md
This PR adds a videos section [similar to the one](https://docs.powertools.aws.dev/lambda/python/latest/we_made_this/#videos) found in the Powertools for AWS Lambda (Python) docs to showcase videos created by community and maintainers.
The PR includes a video from @RaphaelManke and the recording for the OPN402 session by me, at this year's re:Invent.
**Issue number:** closes #3408
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might …
> docs: add videos section in community

- package-lock.json
- packages/testing/package.json
This PR manually updates the `@aws-cdk/cli-lib-alpha` dependency since it's being excluded by Dependabot updates.
For more info, check the linked issue.
**Issue number:** #3117
---
> chore(deps): bump @aws-cdk/cli-lib-alpha to 2.174.1-alpha.0

- packages/metrics/src/Metrics.ts
This PR replaces the internal usage of the [`isDate`](https://nodejs.org/api/util.html#utiltypesisdatevalue) utility function from the standard Node.js library in favor of a more widely supported `instanceof Date` check.
The two methods are functionally equivalent and this change improves compatibility of the Metrics utility with alternative experimental runtimes such as LLRT.
**Issue number:** #3461
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on …
> refactor(metrics): swap `isDate` for `instanceof Date`

- packages/tracer/src/Tracer.ts
- packages/tracer/src/config/EnvironmentVariablesService.ts
- packages/tracer/src/provider/ProviderService.ts
- packages/tracer/tests/helpers/mockRequests.ts
- packages/tracer/tests/unit/ProviderService.test.ts
This PR updates the implementation of the global fetch instrumentation in Tracer so that the `X-Amzn-Trace-Id` header is automatically populated and added to requests when Tracer is enabled.
This allows X-Ray to attribute the segment/span to the correct parent and build the correct service map for a request.
Prior to this PR the header was not added and this resulted in disjointed traces. This happened only when using the Fetch API, but not when using the `https` module - which is why this is considered a bug.
The linked issue contains more info on why we did not add this in the first place and what was missing.
**Issue number:** fixes …
> fix(tracer): forward `X-Amzn-Trace-Id` header when instrumenting fetch

- package-lock.json
- packages/parser/package.json
- packages/parser/tests/unit/schema/appsync.test.ts
Remove thes `fake-jsr` dependency from the parser package.
- Remove `faker` from parser `package.json`
- Update two test cases using the `faker-js` lib.
- Regenerate `pacakge-lcok.json` file
Reviewer in #3388 requested we remove library completely.
**Issue number:** #3480
---
> chore(parser): remove faker dependency

- packages/parser/src/schemas/apigwv2.ts
- packages/parser/tests/unit/schema/apigwv2.test.ts
This PR allows to parse `identitySource` with null value in `APIGatewayRequestAuthorizerEventV2Schema`. 
**Issue number:** closes #3483 
---
> fix(parser): identitySource can be null in APIGatewayRequestAuthorizerEventV2Schema

- packages/commons/package.json
- packages/commons/src/unmarshallDynamoDB.ts
- packages/commons/tests/unit/unmarshallDynamoDB.test.ts
- packages/parser/src/envelopes/dynamodb.ts
- packages/parser/src/schemas/dynamodb.ts
- packages/parser/src/types/envelope.ts
- packages/parser/tests/events/dynamodb/base.json
- packages/parser/tests/unit/envelopes/dynamodb.test.ts
- packages/parser/tests/unit/helpers.test.ts
- packages/parser/tests/unit/schema/dynamodb.test.ts
This PR updates the logic of the `DynamoDBStreamSchema` and `DynamoDBStreamEnvelope` built-in schemas so that they automatically handle DynamoDB attribute values for the customer and convert them to JavaScript native objects during the parsing and validation.
As part of the PR, I have also improved the error messages in the parser to include the index of the record being processed as well as the full path of the issue when parsing fails. For example, now the error would be something like:
```ts
new ParseError('Failed to parse DynamoDB Stream envelope', {
cause: new ZodError([
{
code: 'invalid_type',
expected: 'object',
received: 'undefined',
path: ['Records', 0, 'dynamodb'],
message: 'Required',
}
]),
})
```
and like this for failed …
> fix(parser): DynamoDBStream schema & envelope

- packages/parser/src/envelopes/apigw.ts
- packages/parser/src/envelopes/apigwv2.ts
- packages/parser/src/envelopes/envelope.ts
- packages/parser/tests/unit/envelopes/apigw.test.ts
- packages/parser/tests/unit/envelopes/apigwv2.test.ts
- packages/parser/tests/unit/schema/apigw.test.ts
- packages/parser/tests/unit/schema/apigwv2.test.ts
This PR refactors the API Gateway (REST) & API Gateway v2 (HTTP) envelopes so that they don't force the transform of the `body` field and thus can handle plain text and base64 binary-encoded bodies.
The body is now left as a string and it's up to the caller to set the appropriate transform in the Zod schema passed to the envelope, for example to 
```ts
import { z } from 'zod';
import { JSONStringified } from '@aws-lambda-powertools/parser/helpers';
const schema = z.object({
message: z.string()
});
ApiGatewayEnvelope.parse(event, JSONStringified(schema));
```
If there's demand for it, in the future we can consider adding an helper for base64 decoding.
Additionally I standardized the error structure by always throwing a `ParseError` with …
> fix(parser): API Gateway Envelopes handle non-JSON

- packages/parser/src/schemas/kinesis-firehose.ts
- packages/parser/tests/events/kinesis/firehose-sqs-invalid.json
- packages/parser/tests/unit/schema/kinesis.test.ts
This PR fixes a bug, where KinesisFirehoseSQSSchema would return original data, when SQS message is invalid. 
**Issue number:** closes #3249 
---
> fix(parser): Firehose SQS should fail for invalid SQS message

- layers/src/layer-publisher-stack.ts
This PR adds back the `compatibleArchitectures` field to our Lambda layers since all the regions we support today also support the field in their API.
**Issue number:** closes #1400
---
> chore(layers): add compatible architecture field

- .github/workflows/make-release.yml
- .github/workflows/make-version.yml
- .github/workflows/publish-package.yml
- .github/workflows/publish_layer.yml
- .github/workflows/quality_check.yml
- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- .github/workflows/reusable_deploy_layer_stack.yml
- .github/workflows/reusable_publish_docs.yml
- .github/workflows/run-e2e-tests.yml
This PR updates the hash for the `actions/cached-node-modules` GitHub Actions to use the latest version. This will allow us to continue using the composite action, which now uses a more recent version of `actions/cached`.
**Issue number:** closes #3548
---
> chore: update `actions/cached-node-modules` GitHub Action

- packages/idempotency/src/persistence/BasePersistenceLayer.ts
This PR changes the access modifier of the `getHashedIdempotencyKey()` method in the `packages/idempotency/src/persistence/BasePersistenceLayer.ts` class so that customers can extend it and provide their own implementation for how the idempotency key is created.
```ts
import { DynamoDBPersistenceLayer } from '@aws-lambda-powertools/idempotency/dynamodb';
import type { JSONValue } from '@aws-lambda-powertools/commons/types';
class MyOwnPersistenceLayer extends DynamoDBPersistenceLayer {
getHashedIdempotencyKey(data: JSONValue): string {
return 'foo'; // this string will be used as idempotency key - use with caution
}
}
// use MyOwnPersistenceLayer as you would DynamoDBPersistenceLayer
```
As with all the `protected` methods, you are free …
> improv(idempotency): mark `getHashedIdempotencyKey()` method as protected

- docs/core/logger.md
- examples/snippets/logger/customTimezoneOutput.json
- examples/snippets/logger/reorderLogKeysOutput.json
- examples/snippets/logger/unserializableValues.json
- packages/logger/src/formatter/PowertoolsLogFormatter.ts
- packages/logger/tests/unit/formatters.test.ts
- packages/logger/tests/unit/initializeLogger.test.ts
This PR updates the order of the keys in the default log formatter of Logger so that the most important information about the log entry are surfaced first. Specifically, we are now prioritizing the placement of the `level`, `message`, `timestamp`, and `service` rather than lower cardinality data such as `cold_start`, `function_arn` and others.
Since we are dealing with JSON-structured logs that are expected to be queried once parsed, changing the order should not constitute a breaking change.
**Issue number:** closes #3091
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> improv(logger): switch key order for better readability

- docs/utilities/parameters.md
- examples/snippets/parameters/customProviderVault.ts
- examples/snippets/parameters/customProviderVaultUsage.ts
- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/base/BaseProvider.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/types/BaseProvider.ts
This PR improves slightly the experience in Parameters by allowing customers to create custom providers without having to specify a no-op parameter.
In addition to doing this, I also renamed the parameter to `awsSdkV3ClientPrototype` for added clarity, and improved the documentation around it.
**Issue number:** closes #2400
---
> improv(parser): allow extending base provider with no AWS SDK client

- .github/workflows/bootstrap_region.yml
This PR updates the `bootstrap_region.yml` workflow with three changes:
- The `copy_layers` step is now dependant on the `bootstrap` one
- The  `bootstrap` step checks out the repo and uses the CDK version present - this avoids pinning the CDK version
- The `copy_layers` step uses a specific version of the shared action identified by its commit hash, rather than the `latest` one
**Issue number:** closes #3573
--- …
> chore(ci): remove pinned actions & pkg versions

- .github/workflows/update_ssm.yml
Fixes the path for the latest SSM Param path.
There was an error in the path for the latest path when publishing SSM params, it omitted typescript from the path.
**Issue number:** #3439 
---
> fix(ci): Fix path for latest SSM param

- .github/workflows/bootstrap_region.yml
Adds `contents: read` permission to jobs in region build to enable the workflow to "release".
**Issue number:** #3200 
---
> fix(ci): Add permissions to jobs

- .github/workflows/bootstrap_region.yml
This PR removes an extra `@` character from the version/hash of a shared action.
**Issue number:** closes #3573
---
> chore(ci): fix double `@` in action hash

- .github/workflows/reusable-run-linting-check-and-unit-tests.yml
- lerna.json
- package-lock.json
- package.json
- packages/validation/README.md
- packages/validation/package.json
- packages/validation/src/index.ts
- packages/validation/tests/tsconfig.json
- packages/validation/tests/unit/index.test.ts
- packages/validation/tsconfig.esm.json
- packages/validation/tsconfig.json
- packages/validation/vitest.config.ts
This PR adds a new npm workspace to the project, dedicated to a new utility.
As result of the [RFC](https://github.com/aws-powertools/powertools-lambda-typescript/discussions/3519) and by looking at the feature set on Python, the Validation utility takes dependencies on `ajv` and our own `@aws-lambda-powertools/jmespath` modules.
For now the contents of the package are just a placeholder, and the package is set to `private`, which means it's not published.
Over the coming days I'll be creating issues for the actual implementation and open them to the community.
**Issue number:** closes #3591
---
By submitting this pull request, I …
> chore(validation): add workspace pkg

- docs/core/logger.md
- packages/logger/src/formatter/LogFormatter.ts
This PR adds a notice to both docs and API docs for Logger to let customers know that they should avoid directly mutating attributes when formatting a log entry, but rather they should make deep copies if mutation is necessary.
**Issue number:** #3588
---
> docs(logger): add notice about mutating attributes in log formatter

- docs/utilities/idempotency.md
- examples/snippets/idempotency/customKeyPrefixDecorator.ts
- examples/snippets/idempotency/customKeyPrefixFnWrapper.ts
- examples/snippets/idempotency/customKeyPrefixMiddleware.ts
This PR adds a new section to the Idempotency docs under "Advanced" to explain how to use the `keyPrefix` feature we just added to the Idempotency utility.
Below a screenshot of how the section looks like once rendered:
**Issue number:** closes #3610
---
> docs(idempotency): document keyPrefix feature

- docs/core/logger.md
- examples/snippets/logger/logSampling.ts
- packages/logger/src/Logger.ts
- packages/logger/src/middleware/middy.ts
- packages/logger/tests/unit/injectLambdaContext.test.ts
…in logger context## Summary
This PR modifies the `sampleRate` behaviour for the logger and will now sample per invocation, instead of execution environment. When using `injectLambdaContext` either as decorator or as middleware, we now automatically refresh sample rate.
**Issue number:** closes #3278 
---
> feat(logger): refresh sample rate calculation per invocation

- packages/commons/src/awsSdkUtils.ts
- packages/commons/src/index.ts
- packages/commons/tests/unit/awsSdkUtils.test.ts
This PR adds a mechanism to set the `AWS_SDK_UA_APP_ID` env variable when one is set so that AWS SDK clients include the value when making requests. The env variable is set when importing Powertools and allows us to send our user agent along with requests. 
This new mechanism appends a `NO-OP` user agent, and the PR also implements new logic to add feature-specific user agents only when the `NO-OP` is not present. The UA attached to requests looks like this `app/PT/NO-OP/2.14.0`.
**Issue number:** #3650
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> chore(maintenance): set app sdk ua env variable when none is set

- packages/logger/src/Logger.ts
- packages/logger/src/types/Logger.ts
- packages/logger/tests/unit/logBuffer.test.ts
This PR enables the buffering feature for the logger utility.
It allows the user to configure the buffering functionality in the logger constructor.
The core of this PR is adding allow the behaviour of log buffering to be configured.
1. Add  `logBufferOptions` object to the Logger config
2. Enable log buffering by default
3. Make `flushBuffer` method public
**Issue number:** closes #3634 
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged …
> feat(logger): Enable log buffering feature

- .github/workflows/bootstrap_region.yml
- .github/workflows/layer_balance.yml
- Appends environment to the existing region build workflow
- Creates a new workflow that balances regions
**Issue number:** #3200
---
> fix(ci): Update layer balance scripts

- .github/dependabot.yml
- .github/workflows/run-e2e-tests.yml
- package-lock.json
- packages/testing/package.json
- packages/testing/src/TestStack.ts
This PR replaces the usage of the `@aws-cdk/cli-lib-alpha` with the newer `@aws-cdk/toolkit-lib` that was announced in developer preview [earlier today](https://github.com/aws/aws-cdk-cli/discussions/154).
This new toolkit is expected to be the way of interacting with CDK programmatically moving forward, so it makes sense for us to adopt it and remove the older `@aws-cdk/cli-lib-alpha`.
The switch is pretty much a drop-in replacement for us, since we were already abstracting away the CLI from the tests. The bulk of the changes are in the `TestStack` class in the internal `testing` package, which now uses the new module.
With this new toolkit we unlocked also two new benefits:
- since the new package uses the `latest` dist tag on npmjs.com …
> chore(ci): adopt new CDK Toolkit Library

- packages/parser/src/schemas/s3.ts
- packages/parser/tests/events/s3/s3-lifecycle-event.json
- packages/parser/tests/unit/schema/s3.test.ts
Update S3 Event Schema
* Allow literal `s3.amazonaws.com` in `sourceIPAddress` field
* Make `sequencer` field optional.
**Issue number:**  closes #3643 
---
> fix(parser): Update S3 Event Schema

- packages/logger/src/Logger.ts
- packages/logger/src/constants.ts
- packages/logger/src/types/Logger.ts
- packages/logger/tests/unit/logBuffer.test.ts
This PR adds a new parameter to the `injectLambdaContext()` class method decorator that allows customers to optionally flush a log buffer whenever their function handler throws an error.
The PR also makes slight updates to some of the docstrings in the Logger class that were added during previous PRs, and updates the unit tests for the feature to reduce nesting.
**Issue number:** closes #3635
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged …
> feat(logger): flush buffer on uncaught error decorator

- packages/commons/src/Utility.ts
- packages/commons/tests/unit/Utility.test.ts
- packages/logger/src/Logger.ts
- packages/metrics/src/Metrics.ts
- packages/tracer/src/Tracer.ts
This PR updates the implementation of the shared `Utility` class to streamline it and remove redundant methods.
**Issue number:** closes #3668
---
> chore(maintenance): simplify Utility class

- packages/logger/src/Logger.ts
- packages/logger/src/middleware/middy.ts
- packages/logger/tests/unit/logBuffer.test.ts
This PR adds support for flushing the log buffer when an uncaught error is encountered using middy middleware.
* Add `flushBufferOnUncaughtError` option to middy `injectLambdaContext` options
* Add `clearBuffer` method to the logger. This is needed to clear the buffer in the `onAfter` handler. An alternative I considered was changing the logic of the buffer to only handle one trace id at a time. If a log is buffered with a new trace ID, then the buffer could be reset. 
* Split the `injectLambdaContextAfterOrOnError` into separate handlers . Simplify the names all the handlers.
* The `target` parameter of `injectLambdaContext` can be an array of loggers. I wasn't clear on the correct behaviour if there are multiple loggers provided. At the …
> feat(logger): Flush buffer on uncaught error in Middy middleware

- packages/idempotency/src/IdempotencyHandler.ts
- packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
- packages/idempotency/src/persistence/IdempotencyRecord.ts
- packages/idempotency/src/types/IdempotencyRecord.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
- packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
This PR updates the `IdempotencyRecord` class so that it optionally accepts a `sortKey` parameter. This parameter is provided only when using the `DynamoDBPersistenceLayer` and when using a composite key (pk + sk).
This fixes a bug that prevented the `IdempotencyAlreadyInProgressError` and `IdempotencyItemAlreadyExistsError` from constructing the appropriate error message. Both errors now include both keys in the error message, making it easier for customers to detect idempotent requests or troubleshoot issues.
**Issue number:** fixes #3691
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> fix(idempotency): include sk in error msgs when using composite key

- docs/utilities/validation.md
- examples/snippets/validation/advancedBringAjvInstance.ts
- examples/snippets/validation/advancedCustomFormats.ts
- examples/snippets/validation/advancedExternalRefs.ts
- examples/snippets/validation/gettingStartedDecorator.ts
- examples/snippets/validation/gettingStartedEnvelope.ts
- examples/snippets/validation/gettingStartedEnvelopeBuiltin.ts
- examples/snippets/validation/gettingStartedMiddy.ts
- examples/snippets/validation/gettingStartedStandalone.ts
- examples/snippets/validation/samples/gettingStartedEnvelopeEvent.json
- examples/snippets/validation/samples/gettingStartedSQSEnvelopeEvent.json
- examples/snippets/validation/samples/schemaWithCustomFormat.json
- examples/snippets/validation/schemas.ts
- examples/snippets/validation/schemasWithExternalRefs.ts
- mkdocs.yml
This PR revisits the documentation page for the upcoming Validation utility and extracts the code snippets in the `examples/snippets` directory.
Prior to this PR we already had a draft of the documentation that was written before the implementation. As part of this PR I reviewed each code snippet and the text to make sure it's accurate with what was implemented.
**Issue number:** closes #3716
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged …
> docs(validation): add main docs page

- .github/workflows/reusable_publish_docs.yml
This PR removes a step from the workflow that publishes the docs which I forgot to remove in an earlier PR, and that is causing the workflow to fail.
**Issue number:** closes #3714
---
> chore(ci): remove old api copy step

- packages/logger/tests/e2e/sampleRate.decorator.test.FunctionCode.ts
- packages/logger/tests/e2e/sampleRate.decorator.test.ts
- packages/testing/src/TestStack.ts
This PR updates the e2e test for Logger, related to log sampling, to account for the new mechanism introduced in #3278. The test was using the decorator - which now refreshes the sampling calculation at each request - but was also calling the refresh method manually, which caused double sampling in some cases and causing the test to fail.
As a side quest, I also slightly improved the logs for the e2e tests. In #3665 we adopted a new CLI toolkit and back then I silenced most of the logs except when running in debug mode. Over time I realized that I'd have preferred to have some indication that the stacks were being created/destroyed, so I improved the logs to do that. Now they look like this:
Enabling debug mode when re-running still …
> test: fix transient fails in log sampling tests

- .github/workflows/layers_govcloud.yml
- Moves the `publish-layer-version` command to use `--cli-json-input`
- Improves validation step by outputting a table
**Issue number:** #3423 
---
> fix(ci): Switch GovCloud publish-layer-version to --cli-input-json

- .github/workflows/layers_govcloud.yml
- Fix region typo
**Issue number:** #3423 
---
> fix(ci): region typo in govcloud

- .github/workflows/layer_govcloud_verify.yml
- .github/workflows/layers_govcloud.yml
Simplifies GovCloud Deploy workflow
- Moves to matrix build
- Changes validation to create a table output
- Uploads layer description as an artifact
**Issue number:** #3423 
---
> chore(ci): Simpllified GovCloud Deploy

- docs/roadmap.md
This PR updates the roadmap page in our documentation to reflect the latest status, and specifically mark as completed the features we shipped in Q1.
Moving forward we expect to refresh the roadmap on a monthly basis, provided we have meaningful updates to share.
**Issue number:** closes #3775
---
> docs: update roadmap end Q1

- packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
Makes getKey protected so that deriving classes can determine their own key strategy.
Makes getKey protected so that deriving classes can determine their own key strategy.
**Issue number:** closes #3781
---
> feat: make getKey protected on DynamoDbPersistenceLayer

- docs/utilities/parser.md
- packages/parser/src/schemas/cognito.ts
- packages/parser/src/schemas/index.ts
- packages/parser/tests/events/cognito/base.json
- packages/parser/tests/unit/schema/cognito.test.ts
This PR adds comprehensive Cognito trigger schemas to the Parser utility. The new schemas are implemented using Zod and ensure that AWS Cognito Lambda triggers conform to the expected event structures. The updates cover all 12 trigger types, including:
Pre-Signup Trigger: Validates events when users sign up.
Post-Confirmation Trigger: Validates events after user confirmation.
Pre-Authentication Trigger: Validates events prior to authentication.
Post-Authentication Trigger: Validates events after authentication.
Pre-Token Generation Trigger (V1 & V2): Validates events before token generation.
Migrate User Trigger: Validates events for user migration during sign-in or forgot-password flows.
Custom Message Trigger: Validates events for custom message modifications.
Custom Email Sender …
> feat(parser): add Cognito pre-signup trigger schema

- packages/logger/src/Logger.ts
- packages/logger/tests/unit/logBuffer.test.ts
When the Advanced Logging Control is less verbose than the Logger Log buffer, buffered logs will not be visible. This PR adds a warning that is emitted when this scenario is detected.
There's an existing warning message if the ALC Log Level is less verbose than the Logger Log Level.
* Emit a warning when ALC Log level is less verbose than buffer level
* Add a test for this behaviour
**Issue number:**  #3821 
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created …
> fix(logger): warn customers when the ALC log level is less verbose than log buffer

- packages/testing/src/TestStack.ts
This PR updates the logic in our e2e test suite to create a dedicated output folder for each test case.
Here's a successful test run with the newer logic: https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/14629275606
**Issue number:** closes #3853
---
> chore: update cdk output dir

- packages/parser/src/schemas/kafka.ts
This PR updates the parser kafka schema to make the `key` property optional.
I wasn't sure whether a test case was warranted. Happy to add one
Mark `key` property optional
**Issue number:** #3841 
---
> fix(parser): Make Kafka key property optional

- .github/scripts/release_patch_package_json.js
- docs/environment-variables.md
- docs/features/event-handler/appsync-events.md
- docs/getting-started/lambda-layers.md
- examples/snippets/event-handler/appsync-events/accessEventAndContext.ts
- examples/snippets/event-handler/appsync-events/debugLogging.ts
- examples/snippets/event-handler/appsync-events/templates/gettingStarted.yaml
- examples/snippets/package.json
- package-lock.json
This PR updates the following items after the last release:
- update CloudFormation template for AppSync Events + Lambda
- update one code snippet in the AppSync Events page, fix typo in key features, add clarification about `REQUEST_RESPONSE`
- add the new package as dev dependencies of the internal `examples/snippets` workspace following release
- update the Lambda layer ARNs for the new release (script to be fixed as part of #3772)
- mark `@aws-lambda-powertools/event-handler` as GA in next release
- update `POWERTOOLS_DEV` table formatting
**Issue number:** closes #3863
---
By submitting this pull request, I confirm that you can …
> chore: update snippets & event-handler docs

- packages/event-handler/package.json
- packages/parser/package.json
- packages/validation/package.json
This PR restores the `typeVersions` field in the `package.json` files of Parser and adds it for the first time to the Validation and Event Handler utilities.
This field, while functionally equivalent to the new `exports` syntax used in these three packages, is required for older `tsconfig.json` configuration that default to `modeResolution: "Node"`.
**Issue number:** closes #3865
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might …
> chore: restore typeVersions for old ts config

- docs/we_made_this.md
This PR adds the unofficial Powertools for AWS MCP server created by @walmsles to the community content of our docs.
Thank you for adding this!
**Issue number:** closes #3846
---
> chore(docs): add powertools community mcp

- package-lock.json
- package.json
- typedoc.json
This PR removes the `typedoc-plugin-zod` dev dependency which was causing our docs builds to silently fail while adding very little to the overall docs experience. See linked issue for full details.
**Issue number:** closes  #3877
---
> chore: remove typedoc zod plugin

- package-lock.json
- packages/event-handler/package.json
- packages/idempotency/package.json
- packages/jmespath/package.json
- packages/logger/package.json
- packages/metrics/package.json
- packages/parameters/package.json
- packages/parser/package.json
- packages/tracer/package.json
- packages/validation/package.json
This PR updates the `package.json` for all utilities that depend on the `commons` package so that they now require the same version of the package as their own.
Since we version all our utilities together, this ensures that whenever there's an update to `commons` that updated version is installed with the correct version of each utility. Prior to this fix, the version range used the `^`  symbol, which meant that depending on how customers updated a utility (i.e. `logger`) npm might not have updated `commons` in case of a minor version update.
The change should be seamless and not require any change on the customer side, since it'll be effective starting from the next release.
> Please add the issue number below, if no issue is present the …
> chore: pin version of commons dependency

- docs/we_made_this.md
This PR fixes the YouTube embeds in the community contents page so that they should load correctly.
**Issue number:** closes #3881
---
> chore(docs): fix youtube iframes

- packages/event-handler/src/appsync-events/AppSyncEventsResolver.ts
- packages/event-handler/tests/unit/AppSyncEventsResolver.test.ts
This PR updates the implementation of the `AppSyncEventsResolver` class to always ignore the response returned by an `onSubscribe` handler defined by customers. This is required to avoid customers inadvertently rejecting the subscription.
**Issue number:** fixes #3884
---
> fix(event-handler): ignore return type from onSubscribe handler

- packages/event-handler/src/types/appsync-events.ts
This PR updates the type of the `identity` field in the types for AppSync Events in the Event Handler package to account for the fact that the field can have different contents based on the authorizer used in the API.
The PR also adds a short explanation of what kind of values customers can expect from the field in the docstring of the event.
**Issue number:** closes #3921
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be …
> refactor(event-handler): mark identity field as unknown in event

- docs/features/event-handler/appsync-events.md
- examples/snippets/event-handler/appsync-events/aggregatedProcessingWithPartialResults.ts
- examples/snippets/event-handler/appsync-events/unauthorizedException.ts
- packages/event-handler/src/types/appsync-events.ts
This PR adds a new paragraph and code snippet to the Event Handler AppSync Events resolver docs to show how to drop one or more events - or the entire batch - when using aggregated processing.
The PR also updates the type that was modified in #3922 to include `Record<string, unknown>` for easier usage and updates one of the snippets for unauthorized errors to have a more realistic example.
**Issue number:** #3923
--- …
> docs(event-handler): add examples on how to drop messages

- mkdocs.yml
Fix mkdocs site_url.
Append latest to url so that llms.txt generates the correct url.
**Issue number:** #3952 
---
> chore: add latest to site_url

- docs/features/kafka.md
- examples/snippets/kafka/advancedBasicErrorHandling.ts
- examples/snippets/kafka/advancedHandlingLargeMessages.ts
- examples/snippets/kafka/advancedParserErrorHandling.ts
- examples/snippets/kafka/advancedTestingYourCode.ts
- examples/snippets/kafka/advancedWorkingWithArkType.ts
- examples/snippets/kafka/advancedWorkingWithRecordMetadata.ts
- examples/snippets/kafka/advancedWorkingWithValibot.ts
- examples/snippets/kafka/advancedWorkingWithZod.ts
- examples/snippets/kafka/gettingStartedPrimitiveValues.ts
- examples/snippets/kafka/templates/advancedBatchSizeConfiguration.yaml
- packages/kafka/README.md
- packages/kafka/src/consumer.ts
- packages/kafka/src/errors.ts
- packages/kafka/tests/unit/consumer.test.ts
This PR completes the documentation page and the README file for the Kafka feature.
I have reviewed all the sections and code snippets and aligned it to the one in Python.
**Issue number:** closes #4064
---
> docs(kafka): finalize Kafka docs

- packages/logger/src/formatter/LogFormatter.ts
This PR updates the date formatter in the `LogFormatter` base class to use [`hourCycle`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#hourcycle) set to `h23` and removes `hour12` which was set to `false`.
This allows customers to correctly format timestamps containing midnight as `00` rather than `24` in all supported Node.js runtimes.
**Issue number:** closes #4083
---
**Disclaimer**: We value your time and bandwidth. As …
> fix(logger): set `hourCycle` to h23 when tz is not UTC

- docs/getting-started/installation.md
- docs/getting-started/lambda-layers.md
This PR adds a new section to the Lambda layers docs page to give guidance on how to manage dependencies when using the layers.
The PR also updates a couple missing packages in the "Install" page of the docs.
**Issue number:** closes #4025
---
> docs: clarify version mismatch risks

- .github/workflows/layers_partition_verify.yml
- .github/workflows/layers_partitions.yml
This PR fixes a typo in the workflows that deploy and verify Lambda layers in the AWS GovCloud & AWS China partitions.
**Issue number:** closes #4125
---
> chore: fix typo in partitioned layers workflow

- .gitignore
- README.md
- docs/media/join-discord.svg
- docs/roadmap.md
This PR updates the roadmap documentation to reflect recently completed features and standardizes the Discord badge across documentation.
The PR also updates the Dockerfile that builds the doc to use a more recent version of Node.js.
**Issue number:** Closes #4132
---
> docs: update roadmap with completed features and Discord badge

- packages/metrics/src/Metrics.ts
Replace `Object.assign` usage in `dimensionSets` reducer with direct property assignment to improve time complexity from O(n²) to O(n). The previous implementation copied all accumulator properties on each iteration, while the new approach mutates the accumulator directly using a `for...of` loop.
This change maintains identical behavior while significantly improving performance for metrics with multiple dimension sets, especially in high-throughput Lambda functions.
This PR addresses a performance bottleneck in the Metrics utility where `Object.assign` was used in a reducer pattern, causing O(n²) time complexity. The fix follows the established coding guidelines that recommend avoiding `Object.assign` in accumulators and using `for...of` …
> refactor(metrics): optimize `addDimensions` method to avoid O(n²) complexity

- .github/workflows/make-release.yml
- .github/workflows/publish-package.yml
This PR updates the `make-release` and `publish-package` Github workflows to switch from using publish commands from `lerna` to the native `npm` publish command to publish the packages to the npm registry.
- Updated the `lerna publish` command to `npm publish` in the `make-release.yml` and `publish-package.yml` Github workflows
- For generating provenance statements, the `--provenance` flag was used
-  The `from-package` from lerna was removed as `npm publish` uses the `--workspaces` flag to publish all the workspaces which are not marked as `private`. If a package with the same version is tried to be published, it will throw an error
- To publish an individual package through `publish-package.yml`, the `--workspace <workspace-path>` was used
#4171 
---
By submitting …
> refactor(ci): Updated the publish command in the CI to use `npm publish` instead of `lerna publish`

- package-lock.json
- packages/parser/package.json
This PR updates the `peerDependencies` range for `zod` in the Parser utility to `4.x`. This change is needed because contrary to what stated in [this section](https://zod.dev/v4/versioning?id=versioning-in-zod-4) of Zod v4 versioning page the 3.x line still defaults to Zod v3 instead of Zod v4, which breaks compatibility with Parser (see full discussion in the linked issue).
After the change, customers who try to install Zod 3.x while having Parser installed will get a npm error similar to the one below:
```sh
npm i zod@3.25.76
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @aws-lambda-powertools/parser@2.24.0
npm error Found: zod@3.25.76
npm error node_modules/zod
npm error …
```
> fix(parser): set zod peer range to 4.x

- examples/snippets/parameters/testingYourCodeClientHandler.ts
- packages/parameters/tests/unit/BaseProvider.test.ts
This PR removes some unused assignments and add error handling to the SAST findings from SonarCloud.
- Removed unused variable `envVarsService` from `packages/parameters/tests/unit/BaseProvider.test.ts`
- Added a `console.error` for an unhandled error in `examples/snippets/parameters/testingYourCodeClientHandler.ts`
Closes #4203 
---
> improv(maintenance): Removed some unused assignments and added missing error handling

- packages/metrics/src/Metrics.ts
- packages/metrics/tests/unit/creatingMetrics.test.ts
- packages/metrics/tests/unit/customTimestamp.test.ts
- packages/metrics/tests/unit/dimensions.test.ts
- packages/metrics/tests/unit/initializeMetrics.test.ts
Adds warning messages to the Metrics `setDefaultDimensions` method when overwriting existing default dimensions, ensuring consistency and parity with `addDimension`/`addDimensions` methods.
This pull request improves the robustness of the `setDefaultDimensions` method in the Metrics utility by:
- Moved setEnvConfig() and setConsole() calls from setOptions() to the constructor to ensure logger is initialized before any method uses it.
- Ensuring it gracefully handles `undefined`, `null`, and invalid values for default dimensions.
- Updated the `setDefaultDimensions()` method in the Metrics utility to emit a warning when a default dimension is being overwritten.
- Logging a warning if an invalid dimension name or value is provided (i.e., non-string or empty).
- Adding new unit tests to …
> fix(metrics): emit warning when default dimensions are overwritten

- .github/workflows/layers_partitions.yml
This PR adds a condition in the Partitioned Layer Publish workflow to run the Layer version verification only on Prod and skip it on Gamma.
- Added a condition checking if the passed environment variable is set to Prod before running the Layer version verification
**Issue number:** closes #4320 
---
> improv(ci): Skip Layer version checks for the Gamma environment

- packages/idempotency/src/persistence/BasePersistenceLayer.ts
- packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
This PR prevents errors when initializing the persistence layer class in non Lambda execution environment (eg: test environments where AWS_LAMBDA_FUNCTION_NAME is not defined)
- Passed an empty string as the default value when setting the value of `idempotencyKeyPrefix` and removed the required error message
- Added test to verify the fallback behaviour
**Issue number:** closes #4326 
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues …
> improv(idempotency): Prevent error when AWS_LAMBDA_FUNCTION_NAME is not passed in the Idempotency Persistence Layer

- packages/event-handler/src/rest/BaseRouter.ts
- packages/event-handler/src/rest/constants.ts
- packages/event-handler/src/types/rest.ts
- packages/event-handler/tests/unit/rest/BaseRouter.test.ts
- packages/event-handler/tests/unit/rest/ErrorHandlerRegistry.test.ts
This begins the work for for repsonse handling piece of the REST API event handler. As with other event handlers we need to pass the raw event and the lambda context as option into the handler. We will also pass a `Request` object in, should users prefer to use this web standard when defining their handlers.
- Updated the type definition of `RouteHandler` and `ErrorHandler` to support passing the new parameters in.
- Tightened the return type of `RouteHandler` from `any` to `Response | JSONObject`
- Updated the unit tests to reflect these new changes
- Added factory function to unit tests for creating events of type `APIGatewayProxyEvent`
- Removed `trace` and `connect` HTTP methods [see note]
When attempting to create a `Request` object for the `trace` and `connect` tests, I received an …
> fix(event-handler): pass event, context and request objects into handler

- .github/workflows/run-e2e-tests.yml
This PR updates the `run-e2e-tests.yml` workflow to swap the AWS Account used to run end to end tests with a new one. Additionally, the PR streamlines the workflow by:
- setting an environment where the new secret is set
- simplifying the logic to checkout a specific PR number
- improving the description of the input
- improving step labels with info on the matrix step being run
**Issue number:** closes #4346
--- …
> ci: switch e2e env in run-e2e-tests workflow

- .github/scripts/update_layer_arn.sh
- .github/workflows/make-release.yml
- .github/workflows/publish_layer.yml
- .github/workflows/reusable_deploy_layer_stack.yml
This PR automated the manual process of checking the current layer version, increment the version and input it to the release workflow. Instead, it makes use of an SSM Parameter to automate the process.
This PR updates the layer arn update script to retrieve the current layer arn from SSM Parameter and increment it by 1 to use it as a new layer version instead of getting it passed from the workflow input. Manually doing the increment and passing it to the workflow can be error prone, so it automates that step.
**Issue number:** closes #4339 
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> improv(ci): Automate the layer version tracking during the Make Release workflow

- .github/workflows/layers_partition_verify.yml
- .github/workflows/layers_partitions.yml
- .github/workflows/update_ssm.yml
This PR adds comments for the justification of the excessive secret exposure alert as [identified by CodeQL](https://github.com/aws-powertools/powertools-lambda-typescript/security/code-scanning/195). The finding is a false positive since the secrets are scoped down to specific environments which has only the secrets that it needs.
- Added comments in the workflow file about the justification of the use of dynamically accessed secrets
**Issue number:** closes #4365 
---
**Disclaimer**: We value …
> improv(ci): Added comments in workflow files triggering Excessive Secret Exposure Alert

- .github/scripts/update_layer_arn.sh
- .github/workflows/publish_layer.yml
- .github/workflows/reusable_deploy_layer_stack.yml
- .github/workflows/update_ssm.yml
- docs/maintainers.md
This PR automates the process of updating the SSM Parameter Workflow and replaces the need for manually invoking the SSM Parameter workflow.
- Added jobs to update the beta and prod ssm parameter by invoking the ssm update workflow
- Changed the deploy layer workflow to output layer version instead of layer arn
- Passed the version to the ssm update workflow and the docs update script
- Removed the steps for SSM Parameter update from the maintainer documentations
> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed.
**Issue number:** closes #4322 
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> improv(ci): Automate the SSM Parameter Update step of the release workflow

- .github/workflows/publish_layer.yml
This PR fixes the permission issue that caused the Make Release workflow to fail.
- Adds the `content: write, id-token: write` permissions to the parent job as needed by the reusable workflow
**Issue number:** closes #4384 
---
> improv(ci): Fixed the Make Release workflow permission issue

- packages/parser/src/helpers/index.ts
- packages/parser/src/schemas/kinesis.ts
- packages/parser/tests/unit/helpers.test.ts
This PR adds a helper function which decodes a base64 encoded payload and parses the decoded payload with the schema passed to the function
- Added the helper function to decompress, decode and parse a base64 encoded payload
- Added tests for the helper function
**Issue number:** closes #4412 
---
> feat(parser): implemented a helper function `Base64Encoded` to decode base64 encoded payloads

- .github/workflows/reusable_publish_docs.yml
This PR updates the variables used for the version update in the docs to fix the issue with the version dropdown.
- Changed `$VERSION` and `$ALIAS` to `${{ env.ALIAS }}` and `${{ env.VERSION }}`
**Issue number:** closes #4416 
---
> improv(docs): Fixed the version dropdown in the docs

- packages/event-handler/src/rest/utils.ts
- packages/event-handler/tests/unit/rest/utils.test.ts
Improves the type guard that checks whether we have received a valid`APIGatewayProxyEvent` by handling all its nullable fields.
- Updated the `isAPIGatewayProxyEvent` function
- Added new tests to ensure we catch all possible nullable fields.
**Issue number:** closes #4454
---
> fix(event-handler): handle nullable fields in APIGatewayProxyEvent

- packages/event-handler/package.json
- packages/event-handler/src/rest/RouteHandlerRegistry.ts
- packages/event-handler/src/rest/Router.ts
- packages/event-handler/src/rest/converters.ts
- packages/event-handler/src/rest/index.ts
- packages/event-handler/src/types/index.ts
- packages/event-handler/src/types/rest.ts
- packages/event-handler/tests/unit/rest/ErrorHandlerRegistry.test.ts
- packages/event-handler/tests/unit/rest/RouteHandlerRegistry.test.ts
- packages/event-handler/tests/unit/rest/Router/basic-routing.test.ts
- packages/event-handler/tests/unit/rest/Router/decorators.test.ts
- packages/event-handler/tests/unit/rest/Router/error-handling.test.ts
- packages/event-handler/tests/unit/rest/Router/logging.test.ts
- packages/event-handler/tests/unit/rest/Router/middleware.test.ts
- packages/event-handler/tests/unit/rest/converters.test.ts
- packages/event-handler/tests/unit/rest/errors.test.ts
- packages/event-handler/tests/unit/rest/utils.test.ts
This PR exposes the REST API event handler under the namespace `experimental-rest`:
```ts
import {Router} from '@aws-lambda-powertools/event-handler/experimental-rest';
```
- Created an `index.ts` file so classes and functions can be imported from the the top level namespace
- Updated the `exports` and `typesVersions` sections of `package.json`
- Where applicable, updated the tests to use the the `index.ts` file to import classes and utilities.
- Renamed conversion functions `*ToResponse` to `*ToWebResponse`.
**Issue number:** closes #4456
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues …
> chore(event-handler): expose rest handler functionality

- packages/event-handler/src/rest/Router.ts
- packages/event-handler/src/rest/utils.ts
- packages/event-handler/src/types/rest.ts
- packages/event-handler/tests/unit/rest/ErrorHandlerRegistry.test.ts
- packages/event-handler/tests/unit/rest/Router/basic-routing.test.ts
- packages/event-handler/tests/unit/rest/Router/decorators.test.ts
- packages/event-handler/tests/unit/rest/Router/error-handling.test.ts
- packages/event-handler/tests/unit/rest/Router/middleware.test.ts
- packages/event-handler/tests/unit/rest/utils.test.ts
This PR reflects the change of type from `HandlerOptions` to `RequestContext` made in #4439 by updating class variables, JSDocs and the tests.
- Update all unit tests that define handlers or middleware to use `reqCtx` instead of `options` as the name for any parameter of type `RequestContext`
- Updated the type definitions `reqCtx` instead of `options` as the name for any parameter of type `RequestContext`
- Updated the JSDocs and examples to reflect this change
**Issue number:** closes #4459
---
> chore(event-handler): rename variables to reflect that options object is now a RequestContext

- packages/event-handler/src/rest/Router.ts
- packages/event-handler/src/rest/converters.ts
- packages/event-handler/tests/unit/rest/Router/decorators.test.ts
- packages/event-handler/tests/unit/rest/Router/middleware.test.ts
- packages/event-handler/tests/unit/rest/converters.test.ts
Fixes bug where global middleware did not run on every request but only if a specific route had been registered. Route handlers are executed as part of a special middleware that is always appended to the end of the middleware stack, if a route handler was not found we would throw a NotFound error and skip the middleware altogether.
In the process of fixing this issue, I also found a bug where if a handler returned a `Response` object we did not merge the headers from the middleware that had run before into the `res.headers` object.
- Removed the code that threw a not found error if a route handler was not found
- Moved the logic to handle returning a 404 to the handler middleware. Returned a 404 `Response` object rather than throwing to allow middleware stack to run to completion as …
> fix(event-handler): run global middleware on all requests for REST API

- packages/idempotency/src/makeIdempotent.ts
- packages/idempotency/tests/unit/IdempotencyHandler.test.ts
Fixes documentation error where `dataKeywordArgument` is referenced but doesn't exist in the type definitions. 
- Replaced `dataKeywordArgument` references with `config.eventKeyJmesPath` in documentation
- Removed unused `dataKeywordArgument` reference from test file
**Issue number:** closes #4533
---
> docs(idempotency): fix dataKeywordArgument reference and remove unused test code

- packages/commons/src/Utility.ts
- packages/commons/src/envUtils.ts
- packages/commons/src/index.ts
- packages/commons/tests/types/LambdaInterface.test.ts
- packages/commons/tests/unit/awsSdkUtils.test.ts
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`commons`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed.
**Issue number:** closes #4552
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on …
> style(commons): apply stricter linting

- packages/validation/src/middleware.ts
- packages/validation/tests/unit/decorator.test.ts
- packages/validation/tests/unit/middleware.test.ts
This PR resolves all the linting issues resulting from the new rules being introduced in #4545
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`validation`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4561
---
> style(validation): apply stricter linting

- packages/testing/src/TestStack.ts
- packages/testing/src/setupEnv.ts
- packages/testing/src/xray-traces-utils.ts
> [!important]
> This PR is expected to have failing CI, and this package (`testing`) doesn't have a CI step that runs on PRs. It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4559
---
> style(testing): apply stricter linting

- packages/parser/src/envelopes/sns-sqs.ts
- packages/parser/src/parserDecorator.ts
- packages/parser/src/schemas/appsync-events.ts
- packages/parser/src/schemas/appsync.ts
- packages/parser/src/schemas/cognito.ts
- packages/parser/src/schemas/kafka.ts
- packages/parser/src/types/parser.ts
- packages/parser/tests/types/parser.test-d.ts
- packages/parser/tests/unit/parser.decorator.test.ts
- packages/parser/tests/unit/parser.middy.test.ts
- packages/parser/tests/unit/parser.test.ts
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`parser`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4558
---
> style(parser): apply stricter linting

- packages/jmespath/src/Expression.ts
- packages/jmespath/src/Functions.ts
- packages/jmespath/src/Lexer.ts
- packages/jmespath/src/ParsedResult.ts
- packages/jmespath/src/Parser.ts
- packages/jmespath/src/PowertoolsFunctions.ts
- packages/jmespath/src/TreeInterpreter.ts
- packages/jmespath/src/ast.ts
- packages/jmespath/src/constants.ts
- packages/jmespath/src/envelopes.ts
- packages/jmespath/src/errors.ts
- packages/jmespath/src/search.ts
- packages/jmespath/src/types.ts
- packages/jmespath/src/utils.ts
While working on this, I also updated the dosctrings to use the standard notation of `@param name - description`.
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`jmespath`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4553
---
> style(jmespath): apply stricter linting & improve docstrings

- packages/tracer/src/Tracer.ts
- packages/tracer/src/middleware/middy.ts
- packages/tracer/src/provider/ProviderService.ts
- packages/tracer/src/types/Tracer.ts
- packages/tracer/tests/e2e/decorator.test.ts
- packages/tracer/tests/e2e/manual.test.ts
- packages/tracer/tests/helpers/mockRequests.ts
- packages/tracer/tests/unit/ProviderService.test.ts
- packages/tracer/tests/unit/Tracer.test.ts
- packages/tracer/tests/unit/middy.test.ts
- packages/tracer/vitest.config.ts
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`tracer`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4560
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on …
> style(tracer): apply stricter linting

- packages/metrics/src/Metrics.ts
- packages/metrics/src/middleware/middy.ts
- packages/metrics/tests/e2e/basicFeatures.decorator.test.functionCode.ts
- packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
- packages/metrics/tests/e2e/basicFeatures.manual.test.functionCode.ts
- packages/metrics/tests/e2e/basicFeatures.manual.test.ts
- packages/metrics/tests/helpers/metricsUtils.ts
- packages/metrics/tests/unit/logMetrics.test.ts
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`metrics`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4556
---
**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on …
> style(metrics): apply stricter linting

- packages/event-handler/src/rest/ErrorHandlerRegistry.ts
- packages/event-handler/src/rest/RouteHandlerRegistry.ts
- packages/event-handler/src/rest/Router.ts
- packages/event-handler/src/rest/utils.ts
- packages/event-handler/tests/unit/rest/Router/basic-routing.test.ts
- packages/event-handler/tests/unit/rest/utils.test.ts
This PR adds an `includeRouter` method to allows merging routes, context, and middleware from one router instance into another. 
- Added `merge` methods on the Route Handler and Error Handler registries to merge error handlers and routes
- Added `includeRouter` method on the Router to merge context, registries and middlewares
**Issue number:** closes #4481 
---
> feat(event-handler): added `includeRouter` method to split routes

- packages/parameters/src/appconfig/AppConfigProvider.ts
- packages/parameters/src/appconfig/getAppConfig.ts
- packages/parameters/src/dynamodb/DynamoDBProvider.ts
- packages/parameters/src/secrets/SecretsProvider.ts
- packages/parameters/src/secrets/getSecret.ts
- packages/parameters/src/ssm/SSMProvider.ts
- packages/parameters/src/ssm/getParameter.ts
- packages/parameters/src/ssm/getParameters.ts
- packages/parameters/src/ssm/getParametersByName.ts
- packages/parameters/src/ssm/setParameter.ts
- packages/parameters/src/types/AppConfigProvider.ts
- packages/parameters/src/types/BaseProvider.ts
- packages/parameters/src/types/DynamoDBProvider.ts
- packages/parameters/src/types/SSMProvider.ts
- packages/parameters/src/types/SecretsProvider.ts
- packages/parameters/tests/e2e/appConfigProvider.class.test.ts
- packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
- packages/parameters/tests/e2e/secretsProvider.class.test.ts
- packages/parameters/tests/e2e/ssmProvider.class.test.ts
- packages/parameters/tests/unit/AppConfigProvider.test.ts
- packages/parameters/tests/unit/DynamoDBProvider.test.ts
- packages/parameters/tests/unit/SSMProvider.test.ts
- packages/parameters/tests/unit/SecretsProvider.test.ts
- packages/parameters/tests/unit/setParameter.test.ts
- packages/parameters/typedoc.json
While working on this, I also fixed the docstrings for the module which were in a very old state that used notation no longer required/compatible with Typedoc.
> [!important]
> This PR is expected to have failing CI, focus only on the CI steps for this package (`parameters`). It's safe to merge since it's not going on `main` but on `ci/fix_linting`.
**Issue number:** closes #4557
---
**Disclaimer**: …
> style(parameters): apply stricter linting

- packages/event-handler/src/appsync-events/Router.ts
- packages/event-handler/src/appsync-graphql/AppSyncGraphQLResolver.ts
- packages/event-handler/src/appsync-graphql/index.ts
- packages/event-handler/src/bedrock-agent/BedrockAgentFunctionResolver.ts
- packages/event-handler/src/rest/converters.ts
- packages/event-handler/src/rest/middleware/cors.ts
- packages/event-handler/src/rest/utils.ts
- packages/event-handler/src/types/bedrock-agent.ts
- packages/event-handler/src/types/rest.ts
- packages/event-handler/tests/unit/appsync-events/AppSyncEventsResolver.test.ts
- packages/event-handler/tests/unit/appsync-graphql/AppSyncGraphQLResolver.test.ts
- packages/event-handler/tests/unit/bedrock-agent/BedrockAgentFunctionResolver.test.ts
- packages/event-handler/tests/unit/rest/RouteHandlerRegistry.test.ts
- packages/event-handler/tests/unit/rest/Router/basic-routing.test.ts
- packages/event-handler/tests/unit/rest/Router/decorators.test.ts
- packages/event-handler/tests/unit/rest/Router/error-handling.test.ts
- packages/event-handler/tests/unit/rest/Router/middleware.test.ts
- packages/event-handler/tests/unit/rest/converters.test.ts
- packages/event-handler/tests/unit/rest/helpers.ts
- packages/event-handler/tests/unit/rest/middleware/compress.test.ts
- packages/event-handler/tests/unit/rest/utils.test.ts
This PR resolves all the linting issues resulting from the new rules being introduced in #4545
- Removed `async` from functions not doing `await`
**Issue number:** closes #4575 
---
>  style(event-handler): apply stricter linting

- packages/tracer/tests/e2e/decorator.test.functionCode.ts
- packages/tracer/tests/e2e/decorator.test.ts
- packages/tracer/tests/e2e/manual.test.functionCode.ts
- packages/tracer/tests/e2e/middy.test.functionCode.ts
- packages/tracer/tests/e2e/middy.test.ts
- packages/tracer/tests/helpers/httpRequest.ts
This PR updates the url of the Powertools for AWS docs used in some e2e tests so that the tests can continue working.
As part of the work, I also had to add some user agent & headers to one of the requests so that it's processed correctly - not adding them would result in a 403.
The old domain has now a permanent redirect that caused the tests to fail (see last few runs in the Actions tab).
**Issue number:** closes #4605
---
**Disclaimer**: We value your time and bandwidth. As such, any pull …
> test: update domain in e2e tests
