aws-powertools/powertools-lambda-typescript

.github/workflows/on-release-prod.yml
`0.3.1` -> `0.3.2` publication didn't bumped and published commons and tracer.
Probably a lerna issue ignoring `--force-publish` option. This PR remove  `--conventional-graduate` which seems to be the option that make `--force-publish` option to not behave properly.
Run with  `--conventional-graduate`
```
npx lerna version --force-publish=\* --no-git-tag-version --no-push  --conventional-commits --conventional-graduate
lerna notice cli v4.0.0
lerna info current version 0.3.2
lerna WARN conventional-graduate all packages
lerna info Graduating all prereleased packages
lerna info Looking for changed packages since v0.3.2
lerna success No changed packages to version 
```
Run without it
```
npx lerna version --force-publish=\* --no-git-tag-version --no-push  --conventional-commits …
```
=> chore(cicd): fix lerna version not bumping and publishing all packages

examples/cdk/package-lock.json, examples/cdk/package.json, packages/metrics/package-lock.json, packages/tracing/package-lock.json
Reverts awslabs/aws-lambda-powertools-typescript#532
=> Revert "build(deps-dev): bump aws-cdk from 1.139.0 to 1.143.0"

CHANGELOG.md, examples/cdk/CHANGELOG.md, examples/cdk/package-lock.json, examples/cdk/package.json, examples/sam/CHANGELOG.md, examples/sam/package-lock.json, examples/sam/package.json, lerna.json, packages/commons/CHANGELOG.md, packages/commons/package.json, packages/logger/CHANGELOG.md, packages/logger/package.json, packages/metrics/CHANGELOG.md, packages/metrics/package.json, packages/tracer/CHANGELOG.md, packages/tracer/package.json
This reverts commit 17f01b76fd758c68edb804e4bd606e099bada469.
Reverting last commit as the tag process in the CI/CD pipelines failed.
[#XXXXX](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/XXXXX)  
[#ZZZZZ](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/ZZZZZ)
---
=> Revert "chore(release): v0.12.0-rc.0 [skip ci]"

README.md, docs/index.md, packages/commons/README.md, packages/logger/README.md, packages/metrics/README.md, packages/tracer/README.md
Replace all occurrences of the Slack link with a link to the new Discord space. Add a Discord badge to the README.
Review changes and build documentation locally to verify the new link is presented correctly.
**Issue number:**  #1073 
N/A
---
=> docs(home): add discord invitation link

docs/index.md
This PR is needed to update the layer version to the one that aligns with the latest release `v1.4.0`.
Until #1124 is resolved, this is a manual process.
Check docs after the release has been completed & docs published.
N/A
---
=> chore(docs): update docs with newer layer version

mkdocs.yml
As detailed in #1207, with the advent of the new year, the year in the footer of the docs website needed updating. This PR does just that.
PS: Happy new year 🎉!
See `dev` version of the docs once merged.
**Issue number:** #1207 
---
=> chore(docs): update year in docs

.github/workflows/publish_layer.yaml
As described in #1231, the `publish_layer.yaml` workflow contains an hardcoded version for the CDK CLI. Given that the CDK version in the project was recently updated, the version in the workflow and the one on the project were now out of sync.
As a short term solution to be able to publish the layers, this PR bumps the version and leaves it hardcoded.
I have written down the task to remove the hardcoded version in favor of using the one installed in the project, and managed in the `package.json` of the `layer-publisher` folder, in #1226.
**Issue number:** #1231
---
=> chore(layers): bump hardcoded cdk version in `publish_layer.yaml`

.github/workflows/reusable_deploy_layer_stack.yml
As described in #1233, the `reusable_deploy_layer_stack.yml ` workflow contains an hardcoded version for the CDK CLI. Given that the CDK version in the project was recently updated, the version in the workflow and the one on the project were now out of sync.
As a short term solution to be able to publish the layers, this PR bumps the version and leaves it hardcoded.
I have written down the task to remove the hardcoded version in favor of using the one installed in the project, and managed in the `package.json` of the `layer-publisher` folder, in #1226.
Fixes #1233
Unfortunately, at the moment, the only way to test this is to try to deploy the layers.
**Issue number:** #1233
---
By submitting this pull request, I …
=> chore(layers): bump hardcoded version in `reusable_deploy_layer_stack.yml`

.devcontainer/devcontainer.json, .gitpod.yml
Removed tslint-plugin from gitpod definition and devcontainer definition. 
- ms-vscode.vscode-typescript-tslint-plugin
TSLint [has been deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) in favor of ESLint and the extension has also been deprecated in favor of ESLint's tooling.
`ms-vscode.vscode-typescript-tslint-plugin` is excluded by deleting it from gitpod.ym and devcontainer.json artifacts:
- gitpod: https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.gitpod.yml
- devcontainer: https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.devcontainer/devcontainer.json
**Issue number:** #1276 
---
By submitting this pull request, I confirm that you can use, modify, …
=> chore: remove unused extensions from Gitpod/CodeSpaces

.github/workflows/on-merge-to-main.yml, .github/workflows/on_doc_merge.yml
#1324 introduced some changes to the workflows that publish layers and docs. Some of the changes included incorrect references in some of the jobs dependencies which weren't caught during review and showed up on the GitHub actions only after merging the PR (examples: [1](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4271035677), [2](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4272651663), [3](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/4271248297)).
Once merged this PR should close #1124.
Merge the PR and see if there are additional errors.
**Issue number:** #1124
---
By submitting this pull request, I confirm that you can use, …
=> chore(ci): fixed workflow dependencies

.github/PULL_REQUEST_TEMPLATE.md
As discussed in the linked issue, there was room for improvement in the communication around PRs and issues at the time of contributing. This PR adds a disclaimer to the PR template that aims at making more explicit to contributors that a PR should be preceded by a triaged issue.
This PR resolves #1350.
See the bottom of this PR description, where I have manually pasted the same markdown that I have added to the template. The PR template will be in effect starting from the next PR after this one is merged.
**Issue number:** #1350
--- …
=> chore: add disclaimer to PR template

examples/cdk/README.md
Fix for issue #1311 - update README for CDK with the correct cleanup process.
**Issue number:** #1311
---
=> chore(examples): fix cdk cleanup command

layers/src/layer-publisher-stack.ts, layers/tests/unit/layer-publisher.test.ts
This PR adds `LicenseInfo` and `CompatibleArchitectures` fields to the layer. 
**Issue number:** closes #1371 
---
=> chore(layer): add license and architecture fields

.github/workflows/make-release.yml, package-lock.json, package.json, packages/commons/package.json, packages/idempotency/package.json, packages/logger/package.json, packages/metrics/package.json, packages/parameters/package.json, packages/tracer/package.json
As detailed in the linked issue, the version of `lerna` used prior to this PR was over a year old. As such it wasn't receiving any updates and this was causing some **development only** vulnerabilities to appear in the `npm audit`.
This PR updates the package to the latest version and removes some redundant npm scripts and command flags.
I have tested this setup locally by versioning & publishing to a `verdaccio` registry. I have a good amount of confidence but we'll have to test this definitively during the next release.
Once merged this PR closes #1393
**Issue number:** #1393
---
**Disclaimer**: We value your …
=> chore(ci): update lerna to latest version

examples/cdk/package-lock.json, package-lock.json
One of the dependencies in our tree requires an update due to a prototype pollution type of issue. This is an indirect development only dependency, as such it's not part of the Powertools utilities shipped to npm and to our customers.
Regardless of that, we want to keep things as in order as possible and would like to remove it by updating it to a patched version.
Dependabot tried to open a similar PR and do the update, however even though a patch was applied the dependency was not updated and recreating the PR fails. In the meanwhile, the package at the second level of depth of our dependency tree has updated the problematic dependency, so it's reasonable to perform the update of the lock file manually.
The PR will be merged only when the unit tests below are green as well as having a …
=> build(deps): bump xml2js from 0.4.19 to 0.5.0

.github/workflows/dispatch_analytics.yml
This PR introduces a conditional statement in the GitHub analytics workflow that we use to collect metics about the repository. This workflow should run only in this repo, however prior to this PR, the workflow was running and failing also on forks of the repo.
This PR adds a check to the scheduled workflow that will cause the workflow to end in case the repo name is not the main one.
**Issue number:** #1438
---
=> chore(ci): add condition to check if analytics workflow is running on main repo

docs/core/logger.md, docs/core/metrics.md, docs/core/tracer.md, docs/index.md
As reported in the linked issue, some of the code snippets being highlighted in the docs had incorrect positioning. This meant that attention was directed towards wrong or non existing lines in those snippets.
The PR is the result of a review of all published pages and introduces a number of changes in the highlighted sections.
Once merged the it closes #1466.
**Issue number:** #1466
---
=> chore(docs): review docs highlighted code snippets

.github/workflows/on_doc_merge.yml, .github/workflows/reusable-publish-docs.yml
Adds fix for S3 Docs. The on_docs_push workflow has an unknown issue, but passing the secrets directly resolves it.
**Issue number:** #1468 
---
=> chore(docs): fix workflow secrets

package-lock.json
This PR brings changes to the project's lock file that resulted from running `npm audit fix`, which will also patch [GHSA-x3cc-x39p-42qx](https://github.com/advisories/GHSA-x3cc-x39p-42qx).
Once merged the PR closes #1496.
**Issue number:** #1496
---
=> build(internal): bump `@aws-sdk/client-*`

.github/workflows/reusable-publish-docs.yml
This is a followup PR to #1494 that adds back a missing line to the workflow that publishes the docs to the new S3 destination. The workflow [was failing](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/5284844790) because of this missing line.
**Issue number:** #1490
---
=> chore(docs): added back s3 bucket to workflow

.github/workflows/reusable_export_pr_details.yml
Found a lingering reference to the old repo name
**Issue number:** #1471 
---
=> fix: update reference in workflow

.github/workflows/reusable-publish-docs.yml
I've added a new stanza to reusable_publish_docs.yml to ensure the versions.json is created.
**Issue number:** #1520 
---
=> fix(docs): upload versions.json

CONTRIBUTING.md, package.json
As described in the linked issue, the contribution document was missing info on how to build and package the utilities locally, a workflow that can be useful for maintainers, contributors, and customers who might want to test unreleased versions of the toolkit.
The PR adds a new dedicated section to this topic as well as revisiting some of the sections and flow of the document overall.
**Issue number:** #1525
---
=> docs: refresh contributing docs

.github/CODEOWNERS
This PR updates the `CODEOWNERS` file to reflect the new name of the GitHub team. This way PRs can now be automatically sent for review to the team.
**Issue number:** #1542
---
=> chore: update `CODEOWNERS` file

docs/snippets/package.json, examples/cdk/package.json, examples/sam/package.json, package-lock.json, packages/commons/package.json, packages/idempotency/package.json, packages/metrics/package.json, packages/parameters/package.json, packages/parameters/tests/unit/AppConfigProvider.test.ts, packages/parameters/tests/unit/getAppConfig.test.ts, packages/tracer/package.json
As described in the linked issue, the dependencies related to the AWS SDK, which are used extensively in the workspace need updating. This PR bumps their version to the latest available.
The PR also updates two more packages related to mocking the AWS SDK and changes the way that `Uint8Array` items are created in the unit tests of the `AppConfigProvider` to reflect the new types in the SDK. The change doesn't have any customer-facing effect.
**Issue number:** #1560
---
=> chore(tests): upgrade `@aws-sdk/*` pacakges

.github/workflows/reusable-publish-docs.yml
Before:
After a docs upload to S3, the version picker would be out of date.
After:
The version picker will contain the newest version number.
**Issue number:**  None
---
=> fix(docs): fix alias in versions.json

package-lock.json
Forgot to cleanup lock file in the previous pr
---
=> chore(maintenance): remove vm2 from package-lock.json

package-lock.json, package.json
As described in the linked issue, a series of previous PRs that removed dependencies from the project caused the unintended side effect of breaking the e2e tests. This PR temporarily reintroduces these dependencies so that we can continue running our tests while we work on looking for alternatives.
**Issue number:** #1614
---
=> chore(ci): restore dependencies & fix e2e tests

packages/commons/src/version.ts
This PR bumps the version exposed as module in the `commons` package to the one that will be released shortly.
As detailed in the linked issue, this is currently a manual process, but we plan on automating it soon.
**Issue number:** closes #1627
---
=> chore(commons): bump version prior to release

.github/actions/cached-node-modules/action.yml, packages/commons/src/version.ts
As mentioned in the linked description, this PR adds the new Batch Processing utility to the build process so that when running the CI the package is built together with the others.
**Issue number:** closes #1629
---
=> chore(ci): add batch to build

README.md, docs/index.md, packages/batch/README.md, packages/commons/README.md, packages/idempotency/README.md, packages/logger/README.md, packages/metrics/README.md, packages/parameters/README.md, packages/tracer/README.md
This PR adds a new supporter to the README files published to npmjs.com as well as the main page of the docs.
Thank you tecRacer GmbH & Co. KG for supporting Powertools!
**Issue number:** #1650
---
=> chore(docs): added tecRacer GmbH & Co. KG to project supporters

.github/workflows/dispatch_analytics.yml, .github/workflows/reusable-publish-docs.yml, .github/workflows/reusable_deploy_layer_stack.yml, .github/workflows/run-e2e-tests.yml
As mentioned in the title and linked issue, the `aws-actions/configure-aws-credentials` action has received a major update. This PR bumps and pins the version to the latest available and introduces a setting to continue masking the AWS Account id of the role being assumed.
**Issue number:** #1662
---
=> chore(ci): bump `aws-actions/configure-aws-credentials` action

packages/tracer/src/helpers.ts
As described in the linked issue, currently the Tracer utility comes with an helper function that allows to create a new instance of the Tracer class. We are marking this helper function as deprecated with the intent of removing it in the next major release.
**Issue number:** #1691
---
=> chore(tracer): mark createTracer helper function as deprecated

packages/commons/src/version.ts
This change brings the minor version bump for the next release. 
**Issue number:** closes #1697 
---
=> chore: bump version in commons for user agent

.github/workflows/make-v2-release.yml
This PR makes a small change to one of the commands in the v2 Alpha release workflow. The change reflect the command used to build packages, which was mistakenly updated to `build:prod`, and that has now changed back to `build`.
**Issue number:** #1717
---
=> chore(ci): update v2 release workflow

tsconfig.json
As discussed in the linked issue, this PR sets the `removeComments` compiler option in the main `tsconfig.json` file to `false`.
This instructs the TypeScript compiler to maintain comments (aka docstrings) in the DTS. Comments are still removed from the actual `.js` outputs and can be further stripped by bundlers.
**Issue number:** #1753
---
=> chore(maintenance): set `removeComments` to `false` in `tsconfig.json`

package-lock.json, package.json
This PR bumps the version of the `@middy/core` package in the development dependencies of the project to version 4.x. This allows us to finally run integration tests using that version of Middy together with Powertools, which means that we can also officially support it.
**Issue number:** closes #1674
---
=> chore(maintenance): bump Middy v4 & run tests

package-lock.json, packages/tracer/package.json
This PR bumps the dependency to the `aws-xray-sdk-core` in the Tracer utility to the latest version released at the time of writing `3.5.3`. This release includes a PR (aws/aws-xray-sdk-node#619) that our team has contributed to the X-Ray SDK that allows customers to include `BigInt` objects in the metadata of segments.
Prior to this release the X-Ray SDK would throw a runtime exception when it encountered a `BigInt` causing data loss.
**Issue number:** closes #1713
---
=> build(tracer): bump `aws-xray-sdk-core` to latest

package-lock.json, packages/idempotency/package.json, packages/metrics/package.json, packages/parameters/package.json, packages/testing/package.json, packages/tracer/package.json
This PR bumps the version of the development dependencies related to the AWS SDK to the latest version.
After bumping I have run the integration tests on this branch which are passing:
https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/6704674250
**Issue number:** #1770
---
=> build(maintenance): bump `@aws-sdk/*` dev dependencies

.devcontainer/Dockerfile
This PR fixes the broken install command in the Dockerfile we use for Codespaces and Gitpod
**Issue number:** closes #1914 
---
=> chore(maintenance): fix install command for .devcontainer setup

.github/dependabot.yml
This PR applies 2 changes to the Dependabot config in an effort to further fine tune its behavior:
- Set `labels: [ ]` to disable labelling the PRs. This is done because labels are applied to the PR by another automation after the PR is opened and/or updated
- Add `@smithy/**` to the `aws-sdk` dependency group. This is done so that these dependencies are updated together with the SDK
**Issue number:** #1858
---
=> chore(maintenance): fine tune dependabot config

README.md, docs/index.md, packages/commons/README.md, packages/logger/README.md, packages/metrics/README.md, packages/tracer/README.md
This PR adds a link to the [AWS Lambda performance tuning](https://github.com/aws-samples/optimizations-for-lambda-functions/tree/main) sample to the main README files as well as the docs.
This demo shows common optimization techniques related to bundling and generally handling a high number of TPS.
The demo was created for a Chalk Talk for re:invent 2023 (SVS319).
**Issue number:** #1103
---
=> chore(docs): add link to performance tuning demo

.github/workflows/reusable_deploy_layer_stack.yml
This PR applies the change recommended in the actions/upload-artifact [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#overwriting-an-artifact). As part of the new version the action treats artifacts as immutable, however in our layers workflow we intentionally upload an artifact with the same name.
This PR sets the `overwrite: true` flag to revert to v3 behavior.
**Issue number:** #1966
---
=> chore(maintenance): add overwrite to artifact arn in layer pipeline

package-lock.json
As detailed in the linked issue, the `ip` module, a transitive **development dependency**, brought in by `lerna` is vulnerable to [GHSA-78xj-cgh5-2h22](https://github.com/advisories/GHSA-78xj-cgh5-2h22).
Dependabot was not automatically opening a PR for this dependency so I'm opening this PR to manually bump it (`npm audit fix`).
**Issue number:** #2064
---
=> chore(deps-dev): bump socks & ip-address

.github/workflows/make-version.yml
Reverts aws-powertools/powertools-lambda-typescript#2105
----
This PR adds the new version to the `version.ts` file. 
**Issue number:** closes #2103 
---
=> chore(ci): revert add new version to version.ts file

packages/commons/src/version.ts
This PR manually bumps the version in the `commons` package. This version is used to set the UA header.
**Issue number:** #2103
---
=> chore(commons): bump ua version

.github/workflows/make-version.yml, docs/snippets/package.json
This PR marks the `docs/snippets` package as private so that it's excluded by the publishing process. This change is needed because we recently included the package as part of the lerna workspace but doesn't constitute a change in which packages are actually published.
The PR also fixes the command that bumps the version in the UA.
**Issue number:** #2160
---
=> chore(docs): mark `docs/snippets` package as private

packages/parser/src/envelopes/kafka.ts, packages/parser/src/types/schema.ts, packages/parser/tests/unit/envelopes/apigwt.test.ts
This PR adds type exports for the built in schemas. I have slightly changed the names by adding `Event` suffix. This is similar to the data classes used in python and supports the typing of the `event` object of the handler.
We don't need all the schema object to be reexported as types, because `z.infer` will catch all the nested structure implicitly. 
**Issue number:** closes #1837 
---
=> feat(parser): add types for built-in schemas

docs/utilities/jmespath.md, packages/jmespath/package.json
This PR changes the visibility configuration of the new JMESPath utility to public so that it can be published to npm during the next release.
The PR also removes the warning banner that stated that the utility was not available from the utility docs.
**Issue number:** #1645
---
=> chore(maintenance): make jmespath utility public

.github/workflows/on_schedule_monthly_roadmap_reminder.yml
This adds our first centralized workflow to generate a monthly reminder (1st day each month) to update roadmap.
It also provides a helpful list of top feature requests, most active issues, long-running PRs, etc.. It excludes any issues/PRs that have the following labels:
* `do-not-merge`
* `need-issue`
* `need-rfc`
* `need-customer-feedback`
Live here: https://github.com/aws-powertools/powertools-lambda-python/issues/4077
**Issue number:** #2329
---
=> chore(ci): add monthly roadmap reminder central action

docs/core/metrics.md, docs/index.md, docs/overrides/main.html, docs/upgrade.md
This PR addresses some areas of improvements on our docs, that for lack of critical mass when looked in isolation, have been merged together in a single PR:
When upgrading to v2 and using subpath exports, customers using `eslint` might encounter issues due to it not fully supporting subpath exports. The PR adds a new section to the upgrade guide for those customers.
When testing code that uses the Metrics utility, it is sometimes hard to silence or mock/spy the logs emitted by the utility due to it not using the globalThis.console object. This PR provides more guidance on how to silence or spy logs emitted by the utility.
The Lambda layer ARN in some of the code snippets, as well as the `externalModules` setting and the runtime version in …
=> chore(docs): miscellaneous updates and clarifications on docs

.github/dependabot.yml
Implements the multi-directory config for dependabot. Closes #2454
**Issue number:** #2454 
---
=> chore(ci): Adopt multi directory config for dependabot

.github/workflows/reusable_deploy_layer_stack.yml, docs/index.md
This reverts commit 208c57a28eb7140bf4a2a93a4201a06fced049b9, which will allow us to release the layers in a future release.
**Issue number:** #2674
---
=> chore(layers): revert deploy Lambda layers in `ap-south-2` and `me-central-1`

.markdownlintignore, package.json, packages/commons/README.md, packages/jmespath/README.md
As a last step of the API docs & README overhaul, this PR includes all the README files in the markdownlint.
**Issue number:** #2381
---
=> chore(docs): remove markdownlint exclusions

docs/core/logger.md, docs/core/metrics.md, docs/core/tracer.md, docs/index.md, docs/overrides/main.html, docs/upgrade.md, docs/utilities/idempotency.md, docs/utilities/parser.md, examples/snippets/metrics/customLogger.ts, examples/snippets/metrics/testingMetrics.ts, mkdocs.yml
This PR makes a number of minor changes to the docs in a few pages. Specifically:
- Added the newly added environment variable (`POWERTOOLS_METRICS_ENABLED`) in the main page & feature page
- Added a section dedicated to the `POWERTOOLS_DEV` env variable in the main page, similar to the Python docs
- Updated the Lambda layer code snippet for Amplify to use Gen 2
- Removed the banner at the top of the page for the v1 EoE which was now 3mo old
- Removed the "new" marker from the workshop link (1y old) and the Parser section (6+mo old)
- Added a section in the Metrics utility page that explains how to use a custom logger,
- Updated the "testing your code" section with details on the `POWERTOOLS_METRICS_ENABLED` env variable
- Updated …
=> docs: multiple minor improvements

examples/app/package.json, layers/package.json, package-lock.json, packages/testing/package.json
This PR manually bumps the AWS CDK dependencies to, once again, align their versions so that we can move forward with the release.
**Issue number:** #3117
---
=> chore(deps): bump the aws-cdk group

package-lock.json, packages/testing/package.json
This PR manually bumps the `aws-cdk-lib` and `@aws-cdk/lib-cli-alpha` as well as deduping the former so that only one copy of it is present in our dependency tree:
```
npm ls aws-cdk-lib                                                                                                                                                                                                                                                      <aws:aws-powertools+typescript-beta-Admin>
aws-lambda-powertools-typescript@0.0.1 /Users/aamorosi/Codes/aws-lambda-powertools-typescript
├─┬ @aws-lambda-powertools/testing-utils@2.13.0 -> ./packages/testing
│ └── aws-cdk-lib@2.176.0
├─┬ layers@2.13.0 -> ./layers
│ └── aws-cdk-lib@2.176.0 deduped
└─┬ …
```
=> chore(deps): bump aws-cdk-lib & co

packages/parser/src/schemas/apigw.ts, packages/parser/src/schemas/index.ts
This PR renames and exports the `APIGatewayEventRequestContextSchema` so that customers can extend the `APIGatewayProxyEventSchema` and provide a more accurate schema for events coming from a Lambda Authorizer when working with API Gateway REST APIs.
**Issue number:** closes #3409
---
=> improv(parser): export APIGatewayEventRequestContextSchema

docs/utilities/validation.md, packages/validation/README.md
This PR adds a first draft of the documentation page for the upcoming Validation utility.
This page, while published, is not referenced anywhere nor linked in the actual documentation and can be accessed only by knowing the URL. Even if stumbled upon, it contains a disclaimer stating it's an unreleased feature.
The idea of having this page is that it will help contributors understand the implementation and serve as reference.
> [!note]
> We will do a full review and team editing before actually publishing and after the implementation is complete.
**Issue number:** #3605
---
By submitting this pull request, I confirm that you can use, …
=> docs(validation): add draft of feature page

.github/workflows/reusable_deploy_layer_stack.yml, .github/workflows/update_ssm.yml, docs/index.md
This PR adds the new regions to the workflow to deploy layers and the documentation.
**Issue number:** #3200 
---
=> chore: add new AWS regions to layer workflow and documentation

.github/workflows/layers_govcloud.yml
Converts array of runtimes into string
**Issue number:** #3423 
---
=> chore(ci): fix compat runtimes in govcloud layer creation

mkdocs.yml
This PR adds the new Bedrock Agents functions page to the llmtxt generation.
**Issue number:** closes #3990
---
=> docs: add bedrock agents page to llmtxt

.github/semantic.yml
This PR adds a new scope for `kafka` under the `semantic.yml` config, so we can validate PRs related to this package.
**Issue number:** closes #4062 
---
=> chore: add kafka scope to semantic config

README.md, docs/index.md, packages/batch/README.md, packages/commons/README.md, packages/event-handler/README.md, packages/idempotency/README.md, packages/jmespath/README.md, packages/kafka/README.md, packages/logger/README.md, packages/metrics/README.md, packages/parameters/README.md, packages/parser/README.md, packages/tracer/README.md, packages/validation/README.md
This PR updates the docs homepage and all README files to include [FraudFalcon](https://fraudfalcon.app/) as new customer reference.
Thank you @AlessandroVol23 for submitting FraudFalcon and using Powertools for AWS!
**Issue number:** closes #4282
---
=> docs: add FraudFalcon customer reference

docs/getting-started/lambda-layers.md, examples/app/cdk/example-stack.ts, examples/app/template.yaml
Bumps the layer version as the create PR in the workflow didn't work
**Issue number:** closes #4487 
---
=> chore(ci): update layer ARN on documentation
